// ===================================================================
// Qategori Nihongo - Kotoba (Kosakata) JLPT N3
// 10 kategori. Tiap kotoba: kat, kanji, kana, romaji, arti, contohJp, contohRomaji, contohId
// ===================================================================
window.N3_KOTOBA = [

// ================= 1. KATA KERJA (DOUSHI) =================
{kat:"Kata Kerja", kanji:"届く", kana:"とどく", romaji:"todoku", arti:"sampai, terkirim", contohJp:"荷物が今日届きました。", contohRomaji:"Nimotsu ga kyou todokimashita.", contohId:"Paketnya sampai hari ini."},
{kat:"Kata Kerja", kanji:"決まる", kana:"きまる", romaji:"kimaru", arti:"ditentukan, diputuskan", contohJp:"来月の予定がまだ決まっていません。", contohRomaji:"Raigetsu no yotei ga mada kimatte imasen.", contohId:"Jadwal bulan depan belum ditentukan."},
{kat:"Kata Kerja", kanji:"決める", kana:"きめる", romaji:"kimeru", arti:"memutuskan", contohJp:"引っ越し先をもう決めましたか。", contohRomaji:"Hikkoshi saki o mou kimemashita ka.", contohId:"Apakah kamu sudah memutuskan tempat pindahan?"},
{kat:"Kata Kerja", kanji:"増える", kana:"ふえる", romaji:"fueru", arti:"bertambah", contohJp:"最近、外国人の観光客が増えている。", contohRomaji:"Saikin, gaikokujin no kankoukyaku ga fuete iru.", contohId:"Akhir-akhir ini, wisatawan asing semakin bertambah."},
{kat:"Kata Kerja", kanji:"減る", kana:"へる", romaji:"heru", arti:"berkurang", contohJp:"子供の数が減っている。", contohRomaji:"Kodomo no kazu ga hette iru.", contohId:"Jumlah anak-anak berkurang."},
{kat:"Kata Kerja", kanji:"増やす", kana:"ふやす", romaji:"fuyasu", arti:"menambah", contohJp:"貯金を増やしたい。", contohRomaji:"Chokin o fuyashitai.", contohId:"Saya ingin menambah tabungan."},
{kat:"Kata Kerja", kanji:"減らす", kana:"へらす", romaji:"herasu", arti:"mengurangi", contohJp:"体重を減らすために運動している。", contohRomaji:"Taijuu o herasu tame ni undou shite iru.", contohId:"Saya olahraga untuk mengurangi berat badan."},
{kat:"Kata Kerja", kanji:"慣れる", kana:"なれる", romaji:"nareru", arti:"terbiasa", contohJp:"日本の生活にだいぶ慣れました。", contohRomaji:"Nihon no seikatsu ni daibu naremashita.", contohId:"Saya sudah cukup terbiasa dengan kehidupan di Jepang."},
{kat:"Kata Kerja", kanji:"続ける", kana:"つづける", romaji:"tsuzukeru", arti:"melanjutkan", contohJp:"日本語の勉強を続けています。", contohRomaji:"Nihongo no benkyou o tsuzukete imasu.", contohId:"Saya terus melanjutkan belajar bahasa Jepang."},
{kat:"Kata Kerja", kanji:"続く", kana:"つづく", romaji:"tsuzuku", arti:"berlanjut", contohJp:"雨は明日も続くそうです。", contohRomaji:"Ame wa ashita mo tsuzuku sou desu.", contohId:"Katanya hujan akan berlanjut sampai besok."},
{kat:"Kata Kerja", kanji:"気づく", kana:"きづく", romaji:"kizuku", arti:"menyadari", contohJp:"財布を忘れたことに気づいた。", contohRomaji:"Saifu o wasureta koto ni kizuita.", contohId:"Saya menyadari bahwa saya lupa membawa dompet."},
{kat:"Kata Kerja", kanji:"育てる", kana:"そだてる", romaji:"sodateru", arti:"membesarkan, mendidik", contohJp:"子供を育てるのは大変だ。", contohRomaji:"Kodomo o sodateru no wa taihen da.", contohId:"Membesarkan anak itu berat."},
{kat:"Kata Kerja", kanji:"育つ", kana:"そだつ", romaji:"sodatsu", arti:"tumbuh (besar)", contohJp:"田舎で育ちました。", contohRomaji:"Inaka de sodachimashita.", contohId:"Saya tumbuh besar di desa."},
{kat:"Kata Kerja", kanji:"進む", kana:"すすむ", romaji:"susumu", arti:"maju, berjalan (proses)", contohJp:"工事は順調に進んでいる。", contohRomaji:"Kouji wa junchou ni susunde iru.", contohId:"Proyek konstruksi berjalan lancar."},
{kat:"Kata Kerja", kanji:"迎える", kana:"むかえる", romaji:"mukaeru", arti:"menyambut, menjemput", contohJp:"空港まで迎えに行きます。", contohRomaji:"Kuukou made mukae ni ikimasu.", contohId:"Saya akan menjemput ke bandara."},
{kat:"Kata Kerja", kanji:"訪ねる", kana:"たずねる", romaji:"tazuneru", arti:"mengunjungi, mendatangi", contohJp:"先生のお宅を訪ねた。", contohRomaji:"Sensei no otaku o tazuneta.", contohId:"Saya berkunjung ke rumah guru."},
{kat:"Kata Kerja", kanji:"頼む", kana:"たのむ", romaji:"tanomu", arti:"meminta tolong, memesan", contohJp:"同僚に仕事を頼んだ。", contohRomaji:"Douryou ni shigoto o tanonda.", contohId:"Saya minta tolong pekerjaan kepada rekan kerja."},
{kat:"Kata Kerja", kanji:"頼る", kana:"たよる", romaji:"tayoru", arti:"bergantung pada", contohJp:"親に頼らず生活したい。", contohRomaji:"Oya ni tayorazu seikatsu shitai.", contohId:"Saya ingin hidup tanpa bergantung pada orang tua."},
{kat:"Kata Kerja", kanji:"断る", kana:"ことわる", romaji:"kotowaru", arti:"menolak", contohJp:"誘いを断るのは気まずい。", contohRomaji:"Sasoi o kotowaru no wa kimazui.", contohId:"Menolak ajakan itu rasanya canggung."},
{kat:"Kata Kerja", kanji:"謝る", kana:"あやまる", romaji:"ayamaru", arti:"meminta maaf", contohJp:"遅れたことを謝った。", contohRomaji:"Okureta koto o ayamatta.", contohId:"Saya meminta maaf karena terlambat."},
{kat:"Kata Kerja", kanji:"誘う", kana:"さそう", romaji:"sasou", arti:"mengajak", contohJp:"友達を映画に誘った。", contohRomaji:"Tomodachi o eiga ni sasotta.", contohId:"Saya mengajak teman menonton film."},
{kat:"Kata Kerja", kanji:"選ぶ", kana:"えらぶ", romaji:"erabu", arti:"memilih", contohJp:"好きな色を選んでください。", contohRomaji:"Suki na iro o erande kudasai.", contohId:"Silakan pilih warna yang kamu suka."},
{kat:"Kata Kerja", kanji:"比べる", kana:"くらべる", romaji:"kuraberu", arti:"membandingkan", contohJp:"値段を比べてから買った。", contohRomaji:"Nedan o kurabete kara katta.", contohId:"Saya membeli setelah membandingkan harga."},
{kat:"Kata Kerja", kanji:"疑う", kana:"うたがう", romaji:"utagau", arti:"meragukan, curiga", contohJp:"彼の話を疑ってしまった。", contohRomaji:"Kare no hanashi o utagatte shimatta.", contohId:"Saya jadi meragukan ceritanya."},
{kat:"Kata Kerja", kanji:"信じる", kana:"しんじる", romaji:"shinjiru", arti:"percaya", contohJp:"友達を信じている。", contohRomaji:"Tomodachi o shinjite iru.", contohId:"Saya percaya pada teman saya."},
{kat:"Kata Kerja", kanji:"抱える", kana:"かかえる", romaji:"kakaeru", arti:"memeluk, menanggung (masalah)", contohJp:"多くの問題を抱えている。", contohRomaji:"Ooku no mondai o kakaete iru.", contohId:"Saya sedang menanggung banyak masalah."},
{kat:"Kata Kerja", kanji:"支える", kana:"ささえる", romaji:"sasaeru", arti:"menopang, mendukung", contohJp:"家族が私を支えてくれた。", contohRomaji:"Kazoku ga watashi o sasaete kureta.", contohId:"Keluarga saya menopang saya."},
{kat:"Kata Kerja", kanji:"冷える", kana:"ひえる", romaji:"hieru", arti:"menjadi dingin", contohJp:"夜は体が冷えるので気をつけて。", contohRomaji:"Yoru wa karada ga hieru node ki o tsukete.", contohId:"Malam hari badan mudah dingin, jadi hati-hati."},
{kat:"Kata Kerja", kanji:"冷やす", kana:"ひやす", romaji:"hiyasu", arti:"mendinginkan", contohJp:"ビールを冷蔵庫で冷やしておいた。", contohRomaji:"Biiru o reizouko de hiyashite oita.", contohId:"Saya sudah mendinginkan bir di kulkas."},
{kat:"Kata Kerja", kanji:"温める", kana:"あたためる", romaji:"atatameru", arti:"menghangatkan", contohJp:"お弁当を電子レンジで温めた。", contohRomaji:"Obentou o denshi renji de atatameta.", contohId:"Saya menghangatkan bekal dengan microwave."},
{kat:"Kata Kerja", kanji:"濡れる", kana:"ぬれる", romaji:"nureru", arti:"basah", contohJp:"雨で服が濡れてしまった。", contohRomaji:"Ame de fuku ga nurete shimatta.", contohId:"Baju saya basah karena hujan."},
{kat:"Kata Kerja", kanji:"乾く", kana:"かわく", romaji:"kawaku", arti:"kering", contohJp:"洗濯物がまだ乾いていない。", contohRomaji:"Sentakumono ga mada kawaite inai.", contohId:"Cucian masih belum kering."},
{kat:"Kata Kerja", kanji:"汚れる", kana:"よごれる", romaji:"yogoreru", arti:"kotor", contohJp:"靴が泥で汚れた。", contohRomaji:"Kutsu ga doro de yogoreta.", contohId:"Sepatu saya kotor karena lumpur."},
{kat:"Kata Kerja", kanji:"壊れる", kana:"こわれる", romaji:"kowareru", arti:"rusak", contohJp:"時計が壊れてしまった。", contohRomaji:"Tokei ga kowarete shimatta.", contohId:"Jamnya jadi rusak."},
{kat:"Kata Kerja", kanji:"壊す", kana:"こわす", romaji:"kowasu", arti:"merusak", contohJp:"子供がおもちゃを壊した。", contohRomaji:"Kodomo ga omocha o kowashita.", contohId:"Anak itu merusak mainannya."},
{kat:"Kata Kerja", kanji:"折れる", kana:"おれる", romaji:"oreru", arti:"patah", contohJp:"強い風で木の枝が折れた。", contohRomaji:"Tsuyoi kaze de ki no eda ga oreta.", contohId:"Ranting pohon patah karena angin kencang."},
{kat:"Kata Kerja", kanji:"折る", kana:"おる", romaji:"oru", arti:"mematahkan, melipat", contohJp:"紙を半分に折った。", contohRomaji:"Kami o hanbun ni otta.", contohId:"Saya melipat kertas jadi dua."},
{kat:"Kata Kerja", kanji:"従う", kana:"したがう", romaji:"shitagau", arti:"mematuhi, mengikuti", contohJp:"規則に従ってください。", contohRomaji:"Kisoku ni shitagatte kudasai.", contohId:"Mohon patuhi peraturannya."},
{kat:"Kata Kerja", kanji:"努める", kana:"つとめる", romaji:"tsutomeru", arti:"berusaha keras", contohJp:"安全のために努めています。", contohRomaji:"Anzen no tame ni tsutomete imasu.", contohId:"Kami berusaha keras demi keselamatan."},
{kat:"Kata Kerja", kanji:"確かめる", kana:"たしかめる", romaji:"tashikameru", arti:"memastikan", contohJp:"予約を確かめておいた。", contohRomaji:"Yoyaku o tashikamete oita.", contohId:"Saya sudah memastikan reservasinya."},
{kat:"Kata Kerja", kanji:"認める", kana:"みとめる", romaji:"mitomeru", arti:"mengakui", contohJp:"自分の失敗を認めた。", contohRomaji:"Jibun no shippai o mitometa.", contohId:"Saya mengakui kegagalan saya sendiri."},
{kat:"Kata Kerja", kanji:"喜ぶ", kana:"よろこぶ", romaji:"yorokobu", arti:"bergembira", contohJp:"合格の知らせに喜んだ。", contohRomaji:"Goukaku no shirase ni yorokonda.", contohId:"Saya bergembira mendengar kabar kelulusan."},

// ================= 2. KATA SIFAT -I =================
{kat:"Kata Sifat -i", kanji:"恐ろしい", kana:"おそろしい", romaji:"osoroshii", arti:"menakutkan", contohJp:"あの事故は恐ろしかった。", contohRomaji:"Ano jiko wa osoroshikatta.", contohId:"Kecelakaan itu sangat menakutkan."},
{kat:"Kata Sifat -i", kanji:"羨ましい", kana:"うらやましい", romaji:"urayamashii", arti:"iri, ingin seperti", contohJp:"彼の才能が羨ましい。", contohRomaji:"Kare no sainou ga urayamashii.", contohId:"Saya iri dengan bakatnya."},
{kat:"Kata Sifat -i", kanji:"恥ずかしい", kana:"はずかしい", romaji:"hazukashii", arti:"malu", contohJp:"人前で歌うのは恥ずかしい。", contohRomaji:"Hitomae de utau no wa hazukashii.", contohId:"Bernyanyi di depan orang itu memalukan."},
{kat:"Kata Sifat -i", kanji:"もったいない", kana:"もったいない", romaji:"mottainai", arti:"sayang (mubazir)", contohJp:"食べ物を捨てるのはもったいない。", contohRomaji:"Tabemono o suteru no wa mottainai.", contohId:"Membuang makanan itu sayang sekali."},
{kat:"Kata Sifat -i", kanji:"くだらない", kana:"くだらない", romaji:"kudaranai", arti:"tidak berguna, sepele", contohJp:"くだらないことで喧嘩しないで。", contohRomaji:"Kudaranai koto de kenka shinaide.", contohId:"Jangan bertengkar karena hal sepele."},
{kat:"Kata Sifat -i", kanji:"情けない", kana:"なさけない", romaji:"nasakenai", arti:"menyedihkan, memalukan (diri sendiri)", contohJp:"ミスばかりで情けない。", contohRomaji:"Misu bakari de nasakenai.", contohId:"Terus melakukan kesalahan, rasanya menyedihkan."},
{kat:"Kata Sifat -i", kanji:"頼もしい", kana:"たのもしい", romaji:"tanomoshii", arti:"dapat diandalkan", contohJp:"彼はとても頼もしい先輩だ。", contohRomaji:"Kare wa totemo tanomoshii senpai da.", contohId:"Dia senior yang sangat dapat diandalkan."},
{kat:"Kata Sifat -i", kanji:"詳しい", kana:"くわしい", romaji:"kuwashii", arti:"detail, paham betul", contohJp:"彼は歴史に詳しい。", contohRomaji:"Kare wa rekishi ni kuwashii.", contohId:"Dia sangat paham tentang sejarah."},
{kat:"Kata Sifat -i", kanji:"鋭い", kana:"するどい", romaji:"surudoi", arti:"tajam", contohJp:"鋭い質問をされた。", contohRomaji:"Surudoi shitsumon o sareta.", contohId:"Saya ditanya pertanyaan yang tajam."},
{kat:"Kata Sifat -i", kanji:"鈍い", kana:"にぶい", romaji:"nibui", arti:"tumpul, lamban", contohJp:"このナイフは鈍くて切れない。", contohRomaji:"Kono naifu wa nibukute kirenai.", contohId:"Pisau ini tumpul, tidak bisa memotong."},
{kat:"Kata Sifat -i", kanji:"深い", kana:"ふかい", romaji:"fukai", arti:"dalam", contohJp:"この川は深いから気をつけて。", contohRomaji:"Kono kawa wa fukai kara ki o tsukete.", contohId:"Sungai ini dalam, jadi hati-hati."},
{kat:"Kata Sifat -i", kanji:"浅い", kana:"あさい", romaji:"asai", arti:"dangkal", contohJp:"プールの浅い所で泳いだ。", contohRomaji:"Puuru no asai tokoro de oyoida.", contohId:"Saya berenang di bagian kolam yang dangkal."},
{kat:"Kata Sifat -i", kanji:"濃い", kana:"こい", romaji:"koi", arti:"pekat, kental", contohJp:"濃いコーヒーが好きだ。", contohRomaji:"Koi koohii ga suki da.", contohId:"Saya suka kopi yang pekat."},
{kat:"Kata Sifat -i", kanji:"薄い", kana:"うすい", romaji:"usui", arti:"tipis, encer", contohJp:"このお茶は少し薄い。", contohRomaji:"Kono ocha wa sukoshi usui.", contohId:"Teh ini agak encer."},
{kat:"Kata Sifat -i", kanji:"苦い", kana:"にがい", romaji:"nigai", arti:"pahit", contohJp:"この薬は苦い。", contohRomaji:"Kono kusuri wa nigai.", contohId:"Obat ini pahit."},
{kat:"Kata Sifat -i", kanji:"酸っぱい", kana:"すっぱい", romaji:"suppai", arti:"asam", contohJp:"レモンは酸っぱい。", contohRomaji:"Remon wa suppai.", contohId:"Lemon itu asam."},
{kat:"Kata Sifat -i", kanji:"眠い", kana:"ねむい", romaji:"nemui", arti:"mengantuk", contohJp:"夜遅くまで働いて眠い。", contohRomaji:"Yoru osoku made hataraite nemui.", contohId:"Saya mengantuk karena bekerja sampai larut malam."},
{kat:"Kata Sifat -i", kanji:"厚い", kana:"あつい", romaji:"atsui", arti:"tebal", contohJp:"厚い本を読んでいる。", contohRomaji:"Atsui hon o yonde iru.", contohId:"Saya sedang membaca buku yang tebal."},
{kat:"Kata Sifat -i", kanji:"硬い", kana:"かたい", romaji:"katai", arti:"keras", contohJp:"このパンは硬くなってしまった。", contohRomaji:"Kono pan wa kataku natte shimatta.", contohId:"Roti ini jadi keras."},
{kat:"Kata Sifat -i", kanji:"柔らかい", kana:"やわらかい", romaji:"yawarakai", arti:"lembut, empuk", contohJp:"このソファーは柔らかい。", contohRomaji:"Kono sofaa wa yawarakai.", contohId:"Sofa ini empuk."},

// ================= 3. KATA SIFAT -NA =================
{kat:"Kata Sifat -na", kanji:"熱心", kana:"ねっしん", romaji:"nesshin", arti:"tekun, antusias", contohJp:"彼女は熱心に勉強している。", contohRomaji:"Kanojo wa nesshin ni benkyou shite iru.", contohId:"Dia belajar dengan tekun."},
{kat:"Kata Sifat -na", kanji:"真剣", kana:"しんけん", romaji:"shinken", arti:"serius", contohJp:"真剣な顔で話を聞いた。", contohRomaji:"Shinken na kao de hanashi o kiita.", contohId:"Saya mendengarkan dengan wajah serius."},
{kat:"Kata Sifat -na", kanji:"正確", kana:"せいかく", romaji:"seikaku", arti:"akurat, tepat", contohJp:"正確な情報が必要だ。", contohRomaji:"Seikaku na jouhou ga hitsuyou da.", contohId:"Kita butuh informasi yang akurat."},
{kat:"Kata Sifat -na", kanji:"適当", kana:"てきとう", romaji:"tekitou", arti:"asal-asalan, sesuai", contohJp:"適当な返事をしないで。", contohRomaji:"Tekitou na henji o shinaide.", contohId:"Jangan menjawab asal-asalan."},
{kat:"Kata Sifat -na", kanji:"積極的", kana:"せっきょくてき", romaji:"sekkyokuteki", arti:"proaktif, aktif", contohJp:"積極的に発言してください。", contohRomaji:"Sekkyokuteki ni hatsugen shite kudasai.", contohId:"Silakan berbicara secara aktif."},
{kat:"Kata Sifat -na", kanji:"消極的", kana:"しょうきょくてき", romaji:"shoukyokuteki", arti:"pasif", contohJp:"彼は消極的な性格だ。", contohRomaji:"Kare wa shoukyokuteki na seikaku da.", contohId:"Dia berkepribadian pasif."},
{kat:"Kata Sifat -na", kanji:"具体的", kana:"ぐたいてき", romaji:"gutaiteki", arti:"konkret", contohJp:"具体的な例を挙げてください。", contohRomaji:"Gutaiteki na rei o agete kudasai.", contohId:"Tolong berikan contoh yang konkret."},
{kat:"Kata Sifat -na", kanji:"抽象的", kana:"ちゅうしょうてき", romaji:"chuushouteki", arti:"abstrak", contohJp:"説明が抽象的でわかりにくい。", contohRomaji:"Setsumei ga chuushouteki de wakarinikui.", contohId:"Penjelasannya abstrak, jadi sulit dipahami."},
{kat:"Kata Sifat -na", kanji:"単純", kana:"たんじゅん", romaji:"tanjun", arti:"sederhana", contohJp:"理由は単純だ。", contohRomaji:"Riyuu wa tanjun da.", contohId:"Alasannya sederhana."},
{kat:"Kata Sifat -na", kanji:"複雑", kana:"ふくざつ", romaji:"fukuzatsu", arti:"rumit", contohJp:"手続きが複雑で困った。", contohRomaji:"Tetsuzuki ga fukuzatsu de komatta.", contohId:"Prosedurnya rumit, jadi saya kesulitan."},
{kat:"Kata Sifat -na", kanji:"平等", kana:"びょうどう", romaji:"byoudou", arti:"setara", contohJp:"みんなを平等に扱うべきだ。", contohRomaji:"Minna o byoudou ni atsukau beki da.", contohId:"Semua orang harus diperlakukan setara."},
{kat:"Kata Sifat -na", kanji:"公平", kana:"こうへい", romaji:"kouhei", arti:"adil", contohJp:"公平な judgement をしてほしい。", contohRomaji:"Kouhei na handan o shite hoshii.", contohId:"Saya ingin keputusan yang adil."},
{kat:"Kata Sifat -na", kanji:"十分", kana:"じゅうぶん", romaji:"juubun", arti:"cukup", contohJp:"時間は十分にある。", contohRomaji:"Jikan wa juubun ni aru.", contohId:"Waktunya cukup banyak."},
{kat:"Kata Sifat -na", kanji:"不満", kana:"ふまん", romaji:"fuman", arti:"tidak puas", contohJp:"給料に不満がある。", contohRomaji:"Kyuuryou ni fuman ga aru.", contohId:"Saya tidak puas dengan gaji."},
{kat:"Kata Sifat -na", kanji:"満足", kana:"まんぞく", romaji:"manzoku", arti:"puas", contohJp:"結果に満足している。", contohRomaji:"Kekka ni manzoku shite iru.", contohId:"Saya puas dengan hasilnya."},
{kat:"Kata Sifat -na", kanji:"得意", kana:"とくい", romaji:"tokui", arti:"mahir, jago", contohJp:"料理が得意です。", contohRomaji:"Ryouri ga tokui desu.", contohId:"Saya jago memasak."},
{kat:"Kata Sifat -na", kanji:"苦手", kana:"にがて", romaji:"nigate", arti:"tidak jago, kurang suka", contohJp:"数学が苦手です。", contohRomaji:"Suugaku ga nigate desu.", contohId:"Saya tidak jago matematika."},
{kat:"Kata Sifat -na", kanji:"素直", kana:"すなお", romaji:"sunao", arti:"jujur, penurut", contohJp:"素直な子供だ。", contohRomaji:"Sunao na kodomo da.", contohId:"Anak yang jujur dan penurut."},
{kat:"Kata Sifat -na", kanji:"意外", kana:"いがい", romaji:"igai", arti:"di luar dugaan", contohJp:"意外な結果になった。", contohRomaji:"Igai na kekka ni natta.", contohId:"Hasilnya di luar dugaan."},
{kat:"Kata Sifat -na", kanji:"完全", kana:"かんぜん", romaji:"kanzen", arti:"sempurna, lengkap", contohJp:"完全に理解できた。", contohRomaji:"Kanzen ni rikai dekita.", contohId:"Saya sudah memahaminya sepenuhnya."},
{kat:"Kata Sifat -na", kanji:"盛ん", kana:"さかん", romaji:"sakan", arti:"berkembang pesat, gemar", contohJp:"この地域は農業が盛んだ。", contohRomaji:"Kono chiiki wa nougyou ga sakan da.", contohId:"Daerah ini pertaniannya berkembang pesat."},

// ================= 4. KATA BENDA: KEHIDUPAN SEHARI-HARI =================
{kat:"Kehidupan Sehari-hari", kanji:"家賃", kana:"やちん", romaji:"yachin", arti:"uang sewa rumah", contohJp:"家賃を毎月払っている。", contohRomaji:"Yachin o maitsuki haratte iru.", contohId:"Saya membayar sewa rumah tiap bulan."},
{kat:"Kehidupan Sehari-hari", kanji:"引っ越し", kana:"ひっこし", romaji:"hikkoshi", arti:"pindah rumah", contohJp:"来月引っ越しをする予定です。", contohRomaji:"Raigetsu hikkoshi o suru yotei desu.", contohId:"Saya berencana pindah rumah bulan depan."},
{kat:"Kehidupan Sehari-hari", kanji:"近所", kana:"きんじょ", romaji:"kinjo", arti:"tetangga, sekitar", contohJp:"近所の人と仲良くしている。", contohRomaji:"Kinjo no hito to nakayoku shite iru.", contohId:"Saya akrab dengan tetangga."},
{kat:"Kehidupan Sehari-hari", kanji:"生活", kana:"せいかつ", romaji:"seikatsu", arti:"kehidupan", contohJp:"日本での生活に慣れてきた。", contohRomaji:"Nihon de no seikatsu ni narete kita.", contohId:"Saya mulai terbiasa dengan kehidupan di Jepang."},
{kat:"Kehidupan Sehari-hari", kanji:"習慣", kana:"しゅうかん", romaji:"shuukan", arti:"kebiasaan", contohJp:"早起きの習慣をつけたい。", contohRomaji:"Hayaoki no shuukan o tsuketai.", contohId:"Saya ingin membiasakan bangun pagi."},
{kat:"Kehidupan Sehari-hari", kanji:"趣味", kana:"しゅみ", romaji:"shumi", arti:"hobi", contohJp:"私の趣味は釣りです。", contohRomaji:"Watashi no shumi wa tsuri desu.", contohId:"Hobi saya adalah memancing."},
{kat:"Kehidupan Sehari-hari", kanji:"予定", kana:"よてい", romaji:"yotei", arti:"jadwal, rencana", contohJp:"今週末の予定は特にない。", contohRomaji:"Konshuumatsu no yotei wa toku ni nai.", contohId:"Saya tidak ada rencana khusus akhir pekan ini."},
{kat:"Kehidupan Sehari-hari", kanji:"都合", kana:"つごう", romaji:"tsugou", arti:"kondisi, kesempatan (waktu)", contohJp:"都合がよければ来てください。", contohRomaji:"Tsugou ga yokereba kite kudasai.", contohId:"Kalau waktunya memungkinkan, silakan datang."},
{kat:"Kehidupan Sehari-hari", kanji:"用事", kana:"ようじ", romaji:"youji", arti:"urusan, keperluan", contohJp:"急な用事ができた。", contohRomaji:"Kyuu na youji ga dekita.", contohId:"Ada urusan mendadak."},
{kat:"Kehidupan Sehari-hari", kanji:"育児", kana:"いくじ", romaji:"ikuji", arti:"mengasuh anak", contohJp:"育児は本当に大変だ。", contohRomaji:"Ikuji wa hontou ni taihen da.", contohId:"Mengasuh anak itu benar-benar berat."},
{kat:"Kehidupan Sehari-hari", kanji:"家事", kana:"かじ", romaji:"kaji", arti:"pekerjaan rumah tangga", contohJp:"家事を分担している。", contohRomaji:"Kaji o buntan shite iru.", contohId:"Kami membagi pekerjaan rumah tangga."},
{kat:"Kehidupan Sehari-hari", kanji:"掃除", kana:"そうじ", romaji:"souji", arti:"bersih-bersih", contohJp:"週末に部屋を掃除する。", contohRomaji:"Shuumatsu ni heya o souji suru.", contohId:"Saya membersihkan kamar di akhir pekan."},
{kat:"Kehidupan Sehari-hari", kanji:"洗濯", kana:"せんたく", romaji:"sentaku", arti:"mencuci (baju)", contohJp:"毎朝洗濯をします。", contohRomaji:"Maiasa sentaku o shimasu.", contohId:"Saya mencuci baju setiap pagi."},
{kat:"Kehidupan Sehari-hari", kanji:"節約", kana:"せつやく", romaji:"setsuyaku", arti:"berhemat", contohJp:"生活費を節約している。", contohRomaji:"Seikatsuhi o setsuyaku shite iru.", contohId:"Saya berhemat biaya hidup."},
{kat:"Kehidupan Sehari-hari", kanji:"貯金", kana:"ちょきん", romaji:"chokin", arti:"menabung", contohJp:"毎月少しずつ貯金している。", contohRomaji:"Maitsuki sukoshizutsu chokin shite iru.", contohId:"Saya menabung sedikit demi sedikit tiap bulan."},
{kat:"Kehidupan Sehari-hari", kanji:"材料", kana:"ざいりょう", romaji:"zairyou", arti:"bahan", contohJp:"料理の材料を買いに行く。", contohRomaji:"Ryouri no zairyou o kai ni iku.", contohId:"Saya pergi membeli bahan masakan."},
{kat:"Kehidupan Sehari-hari", kanji:"暮らし", kana:"くらし", romaji:"kurashi", arti:"kehidupan sehari-hari", contohJp:"一人暮らしを始めた。", contohRomaji:"Hitori-gurashi o hajimeta.", contohId:"Saya mulai hidup sendiri."},
{kat:"Kehidupan Sehari-hari", kanji:"用意", kana:"ようい", romaji:"youi", arti:"persiapan", contohJp:"出かける用意をする。", contohRomaji:"Dekakeru youi o suru.", contohId:"Saya bersiap-siap untuk pergi."},
{kat:"Kehidupan Sehari-hari", kanji:"準備", kana:"じゅんび", romaji:"junbi", arti:"persiapan", contohJp:"試験の準備をしている。", contohRomaji:"Shiken no junbi o shite iru.", contohId:"Saya sedang mempersiapkan ujian."},
{kat:"Kehidupan Sehari-hari", kanji:"片付け", kana:"かたづけ", romaji:"katazuke", arti:"beres-beres", contohJp:"部屋の片付けをした。", contohRomaji:"Heya no katazuke o shita.", contohId:"Saya membereskan kamar."},
{kat:"Kehidupan Sehari-hari", kanji:"世話", kana:"せわ", romaji:"sewa", arti:"merawat, mengurus", contohJp:"犬の世話をしている。", contohRomaji:"Inu no sewa o shite iru.", contohId:"Saya merawat anjing."},
{kat:"Kehidupan Sehari-hari", kanji:"迷惑", kana:"めいわく", romaji:"meiwaku", arti:"gangguan, merepotkan", contohJp:"近所に迷惑をかけないように。", contohRomaji:"Kinjo ni meiwaku o kakenai you ni.", contohId:"Supaya tidak merepotkan tetangga."},
{kat:"Kehidupan Sehari-hari", kanji:"苦情", kana:"くじょう", romaji:"kujou", arti:"keluhan", contohJp:"騒音についての苦情が来た。", contohRomaji:"Souon ni tsuite no kujou ga kita.", contohId:"Ada keluhan tentang kebisingan."},

// ================= 5. KATA BENDA: MASYARAKAT & PEKERJAAN =================
{kat:"Masyarakat & Pekerjaan", kanji:"就職", kana:"しゅうしょく", romaji:"shuushoku", arti:"mendapat pekerjaan", contohJp:"来年就職する予定です。", contohRomaji:"Rainen shuushoku suru yotei desu.", contohId:"Saya berencana mulai kerja tahun depan."},
{kat:"Masyarakat & Pekerjaan", kanji:"転職", kana:"てんしょく", romaji:"tenshoku", arti:"pindah kerja", contohJp:"転職を考えている。", contohRomaji:"Tenshoku o kangaete iru.", contohId:"Saya sedang mempertimbangkan pindah kerja."},
{kat:"Masyarakat & Pekerjaan", kanji:"昇進", kana:"しょうしん", romaji:"shoushin", arti:"promosi jabatan", contohJp:"部長に昇進した。", contohRomaji:"Buchou ni shoushin shita.", contohId:"Dia dipromosikan menjadi kepala bagian."},
{kat:"Masyarakat & Pekerjaan", kanji:"給料", kana:"きゅうりょう", romaji:"kyuuryou", arti:"gaji", contohJp:"今月の給料が出た。", contohRomaji:"Kongetsu no kyuuryou ga deta.", contohId:"Gaji bulan ini sudah keluar."},
{kat:"Masyarakat & Pekerjaan", kanji:"残業", kana:"ざんぎょう", romaji:"zangyou", arti:"lembur", contohJp:"今日は残業しなければならない。", contohRomaji:"Kyou wa zangyou shinakereba naranai.", contohId:"Hari ini saya harus lembur."},
{kat:"Masyarakat & Pekerjaan", kanji:"出張", kana:"しゅっちょう", romaji:"shucchou", arti:"perjalanan dinas", contohJp:"来週大阪へ出張します。", contohRomaji:"Raishuu Oosaka e shucchou shimasu.", contohId:"Minggu depan saya dinas ke Osaka."},
{kat:"Masyarakat & Pekerjaan", kanji:"会議", kana:"かいぎ", romaji:"kaigi", arti:"rapat", contohJp:"午後から会議があります。", contohRomaji:"Gogo kara kaigi ga arimasu.", contohId:"Ada rapat mulai siang nanti."},
{kat:"Masyarakat & Pekerjaan", kanji:"契約", kana:"けいやく", romaji:"keiyaku", arti:"kontrak", contohJp:"契約書にサインした。", contohRomaji:"Keiyakusho ni sain shita.", contohId:"Saya menandatangani surat kontrak."},
{kat:"Masyarakat & Pekerjaan", kanji:"責任", kana:"せきにん", romaji:"sekinin", arti:"tanggung jawab", contohJp:"自分の仕事に責任を持つ。", contohRomaji:"Jibun no shigoto ni sekinin o motsu.", contohId:"Bertanggung jawab atas pekerjaan sendiri."},
{kat:"Masyarakat & Pekerjaan", kanji:"担当", kana:"たんとう", romaji:"tantou", arti:"penanggung jawab, bagian", contohJp:"営業を担当しています。", contohRomaji:"Eigyou o tantou shite imasu.", contohId:"Saya bertugas di bagian penjualan."},
{kat:"Masyarakat & Pekerjaan", kanji:"経営", kana:"けいえい", romaji:"keiei", arti:"manajemen usaha", contohJp:"父は小さな店を経営している。", contohRomaji:"Chichi wa chiisana mise o keiei shite iru.", contohId:"Ayah saya mengelola toko kecil."},
{kat:"Masyarakat & Pekerjaan", kanji:"経済", kana:"けいざい", romaji:"keizai", arti:"ekonomi", contohJp:"経済のニュースをよく見る。", contohRomaji:"Keizai no nyuusu o yoku miru.", contohId:"Saya sering menonton berita ekonomi."},
{kat:"Masyarakat & Pekerjaan", kanji:"景気", kana:"けいき", romaji:"keiki", arti:"kondisi ekonomi", contohJp:"最近景気が悪いそうだ。", contohRomaji:"Saikin keiki ga warui sou da.", contohId:"Katanya belakangan ini kondisi ekonomi sedang buruk."},
{kat:"Masyarakat & Pekerjaan", kanji:"制度", kana:"せいど", romaji:"seido", arti:"sistem, aturan", contohJp:"新しい制度が始まった。", contohRomaji:"Atarashii seido ga hajimatta.", contohId:"Sistem baru sudah mulai berlaku."},
{kat:"Masyarakat & Pekerjaan", kanji:"法律", kana:"ほうりつ", romaji:"houritsu", arti:"hukum", contohJp:"法律を守るべきだ。", contohRomaji:"Houritsu o mamoru beki da.", contohId:"Kita harus mematuhi hukum."},
{kat:"Masyarakat & Pekerjaan", kanji:"権利", kana:"けんり", romaji:"kenri", arti:"hak", contohJp:"働く人の権利を守る。", contohRomaji:"Hataraku hito no kenri o mamoru.", contohId:"Melindungi hak para pekerja."},
{kat:"Masyarakat & Pekerjaan", kanji:"義務", kana:"ぎむ", romaji:"gimu", arti:"kewajiban", contohJp:"税金を払うのは国民の義務だ。", contohRomaji:"Zeikin o harau no wa kokumin no gimu da.", contohId:"Membayar pajak adalah kewajiban warga negara."},
{kat:"Masyarakat & Pekerjaan", kanji:"環境", kana:"かんきょう", romaji:"kankyou", arti:"lingkungan", contohJp:"環境を守ることが大切だ。", contohRomaji:"Kankyou o mamoru koto ga taisetsu da.", contohId:"Menjaga lingkungan itu penting."},
{kat:"Masyarakat & Pekerjaan", kanji:"資源", kana:"しげん", romaji:"shigen", arti:"sumber daya", contohJp:"石油は貴重な資源だ。", contohRomaji:"Sekiyu wa kichou na shigen da.", contohId:"Minyak bumi adalah sumber daya berharga."},
{kat:"Masyarakat & Pekerjaan", kanji:"人口", kana:"じんこう", romaji:"jinkou", arti:"populasi", contohJp:"この町の人口は減っている。", contohRomaji:"Kono machi no jinkou wa hette iru.", contohId:"Populasi kota ini semakin berkurang."},
{kat:"Masyarakat & Pekerjaan", kanji:"高齢化", kana:"こうれいか", romaji:"koureika", arti:"penuaan populasi", contohJp:"日本では高齢化が進んでいる。", contohRomaji:"Nihon dewa koureika ga susunde iru.", contohId:"Di Jepang, penuaan populasi terus berkembang."},
{kat:"Masyarakat & Pekerjaan", kanji:"差別", kana:"さべつ", romaji:"sabetsu", arti:"diskriminasi", contohJp:"差別をなくすべきだ。", contohRomaji:"Sabetsu o nakusu beki da.", contohId:"Diskriminasi harus dihapuskan."},
{kat:"Masyarakat & Pekerjaan", kanji:"事故", kana:"じこ", romaji:"jiko", arti:"kecelakaan", contohJp:"昨日交通事故があった。", contohRomaji:"Kinou koutsuu jiko ga atta.", contohId:"Kemarin ada kecelakaan lalu lintas."},
{kat:"Masyarakat & Pekerjaan", kanji:"事件", kana:"じけん", romaji:"jiken", arti:"kasus, insiden", contohJp:"大きな事件が起きた。", contohRomaji:"Ookina jiken ga okita.", contohId:"Terjadi kasus besar."},
{kat:"Masyarakat & Pekerjaan", kanji:"災害", kana:"さいがい", romaji:"saigai", arti:"bencana", contohJp:"自然災害に備える。", contohRomaji:"Shizen saigai ni sonaeru.", contohId:"Bersiap menghadapi bencana alam."},
{kat:"Masyarakat & Pekerjaan", kanji:"被害", kana:"ひがい", romaji:"higai", arti:"kerugian, korban", contohJp:"台風で大きな被害が出た。", contohRomaji:"Taifuu de ookina higai ga deta.", contohId:"Terjadi kerugian besar akibat topan."},
{kat:"Masyarakat & Pekerjaan", kanji:"対策", kana:"たいさく", romaji:"taisaku", arti:"langkah penanggulangan", contohJp:"事故を防ぐための対策を考える。", contohRomaji:"Jiko o fusegu tame no taisaku o kangaeru.", contohId:"Memikirkan langkah pencegahan kecelakaan."},

// ================= 6. KATA KETERANGAN (FUKUSHI) =================
{kat:"Kata Keterangan", kanji:"次第に", kana:"しだいに", romaji:"shidai ni", arti:"secara bertahap", contohJp:"天気は次第に良くなるでしょう。", contohRomaji:"Tenki wa shidai ni yoku naru deshou.", contohId:"Cuaca akan membaik secara bertahap."},
{kat:"Kata Keterangan", kanji:"徐々に", kana:"じょじょに", romaji:"jojo ni", arti:"perlahan-lahan", contohJp:"病気は徐々に回復している。", contohRomaji:"Byouki wa jojo ni kaifuku shite iru.", contohId:"Sakitnya berangsur-angsur pulih."},
{kat:"Kata Keterangan", kanji:"急に", kana:"きゅうに", romaji:"kyuu ni", arti:"tiba-tiba", contohJp:"急に雨が降ってきた。", contohRomaji:"Kyuu ni ame ga futte kita.", contohId:"Tiba-tiba turun hujan."},
{kat:"Kata Keterangan", kanji:"突然", kana:"とつぜん", romaji:"totsuzen", arti:"tiba-tiba, mendadak", contohJp:"突然電気が消えた。", contohRomaji:"Totsuzen denki ga kieta.", contohId:"Listrik tiba-tiba mati."},
{kat:"Kata Keterangan", kanji:"実は", kana:"じつは", romaji:"jitsu wa", arti:"sebenarnya", contohJp:"実は、もう転職を決めました。", contohRomaji:"Jitsu wa, mou tenshoku o kimemashita.", contohId:"Sebenarnya, saya sudah memutuskan untuk pindah kerja."},
{kat:"Kata Keterangan", kanji:"実際に", kana:"じっさいに", romaji:"jissai ni", arti:"pada kenyataannya", contohJp:"実際に行ってみないとわからない。", contohRomaji:"Jissai ni itte minai to wakaranai.", contohId:"Tidak akan tahu kalau belum benar-benar pergi ke sana."},
{kat:"Kata Keterangan", kanji:"確かに", kana:"たしかに", romaji:"tashika ni", arti:"memang benar", contohJp:"確かに彼の言う通りだ。", contohRomaji:"Tashika ni kare no iu toori da.", contohId:"Memang benar seperti yang dia katakan."},
{kat:"Kata Keterangan", kanji:"案外", kana:"あんがい", romaji:"angai", arti:"di luar dugaan", contohJp:"試験は案外簡単だった。", contohRomaji:"Shiken wa angai kantan datta.", contohId:"Ujiannya di luar dugaan, ternyata mudah."},
{kat:"Kata Keterangan", kanji:"相変わらず", kana:"あいかわらず", romaji:"aikawarazu", arti:"seperti biasa, tak berubah", contohJp:"相変わらず元気そうですね。", contohRomaji:"Aikawarazu genki sou desu ne.", contohId:"Kamu terlihat sehat seperti biasa ya."},
{kat:"Kata Keterangan", kanji:"相当", kana:"そうとう", romaji:"soutou", arti:"cukup, lumayan", contohJp:"相当疲れているようだ。", contohRomaji:"Soutou tsukarete iru you da.", contohId:"Sepertinya dia cukup lelah."},
{kat:"Kata Keterangan", kanji:"なるべく", kana:"なるべく", romaji:"narubeku", arti:"sebisa mungkin", contohJp:"なるべく早く来てください。", contohRomaji:"Narubeku hayaku kite kudasai.", contohId:"Tolong datang sebisa mungkin lebih awal."},
{kat:"Kata Keterangan", kanji:"思い切り", kana:"おもいきり", romaji:"omoikiri", arti:"sepuas-puasnya, habis-habisan", contohJp:"休みの日は思い切り遊びたい。", contohRomaji:"Yasumi no hi wa omoikiri asobitai.", contohId:"Di hari libur saya ingin bermain sepuasnya."},
{kat:"Kata Keterangan", kanji:"思わず", kana:"おもわず", romaji:"omowazu", arti:"tanpa sadar", contohJp:"驚いて思わず声を出した。", contohRomaji:"Odoroite omowazu koe o dashita.", contohId:"Saya kaget dan tanpa sadar berteriak."},
{kat:"Kata Keterangan", kanji:"わざと", kana:"わざと", romaji:"wazato", arti:"dengan sengaja", contohJp:"わざと聞こえないふりをした。", contohRomaji:"Wazato kikoenai furi o shita.", contohId:"Saya sengaja pura-pura tidak mendengar."},
{kat:"Kata Keterangan", kanji:"わざわざ", kana:"わざわざ", romaji:"wazawaza", arti:"repot-repot (khusus melakukan)", contohJp:"わざわざ来てくれてありがとう。", contohRomaji:"Wazawaza kite kurete arigatou.", contohId:"Terima kasih sudah repot-repot datang."},
{kat:"Kata Keterangan", kanji:"せっかく", kana:"せっかく", romaji:"sekkaku", arti:"sudah susah payah, kesempatan baik", contohJp:"せっかく作ったのに食べてくれない。", contohRomaji:"Sekkaku tsukutta noni tabete kurenai.", contohId:"Sudah susah payah dibuat, tapi tidak mau dimakan."},
{kat:"Kata Keterangan", kanji:"一応", kana:"いちおう", romaji:"ichiou", arti:"sekadar, untuk jaga-jaga", contohJp:"一応確認しておきます。", contohRomaji:"Ichiou kakunin shite okimasu.", contohId:"Saya akan memastikan dulu untuk jaga-jaga."},
{kat:"Kata Keterangan", kanji:"とりあえず", kana:"とりあえず", romaji:"toriaezu", arti:"untuk sementara", contohJp:"とりあえずビールを注文した。", contohRomaji:"Toriaezu biiru o chuumon shita.", contohId:"Untuk sementara saya pesan bir dulu."},
{kat:"Kata Keterangan", kanji:"結局", kana:"けっきょく", romaji:"kekkyoku", arti:"akhirnya, pada akhirnya", contohJp:"結局、旅行は中止になった。", contohRomaji:"Kekkyoku, ryokou wa chuushi ni natta.", contohId:"Pada akhirnya, perjalanannya dibatalkan."},
{kat:"Kata Keterangan", kanji:"一方", kana:"いっぽう", romaji:"ippou", arti:"di sisi lain", contohJp:"兄は真面目な一方、弟は自由だ。", contohRomaji:"Ani wa majime na ippou, otouto wa jiyuu da.", contohId:"Kakak rajin, di sisi lain adik bebas."},
{kat:"Kata Keterangan", kanji:"お互いに", kana:"おたがいに", romaji:"otagai ni", arti:"saling", contohJp:"お互いに助け合いましょう。", contohRomaji:"Otagai ni tasukeaimashou.", contohId:"Mari kita saling membantu."},

// ================= 7. KATA SAMBUNG & UNGKAPAN =================
{kat:"Kata Sambung", kanji:"それにしても", kana:"それにしても", romaji:"sore ni shite mo", arti:"meskipun begitu", contohJp:"それにしても、今日は暑いね。", contohRomaji:"Sore ni shite mo, kyou wa atsui ne.", contohId:"Meskipun begitu, hari ini panas ya."},
{kat:"Kata Sambung", kanji:"ところが", kana:"ところが", romaji:"tokoroga", arti:"namun (di luar dugaan)", contohJp:"晴れると思った。ところが、雨が降った。", contohRomaji:"Hareru to omotta. Tokoroga, ame ga futta.", contohId:"Saya kira akan cerah. Namun, malah turun hujan."},
{kat:"Kata Sambung", kanji:"ところで", kana:"ところで", romaji:"tokorode", arti:"ngomong-ngomong", contohJp:"ところで、来週の予定はどうですか。", contohRomaji:"Tokorode, raishuu no yotei wa dou desu ka.", contohId:"Ngomong-ngomong, bagaimana rencana minggu depan?"},
{kat:"Kata Sambung", kanji:"それどころか", kana:"それどころか", romaji:"sore dokoro ka", arti:"bukan hanya itu, malah...", contohJp:"疲れが取れない。それどころか、もっと悪くなった。", contohRomaji:"Tsukare ga torenai. Sore dokoro ka, motto waruku natta.", contohId:"Lelahnya tidak hilang. Malah, jadi semakin buruk."},
{kat:"Kata Sambung", kanji:"したがって", kana:"したがって", romaji:"shitagatte", arti:"oleh karena itu", contohJp:"雨が降った。したがって、試合は中止だ。", contohRomaji:"Ame ga futta. Shitagatte, shiai wa chuushi da.", contohId:"Hujan turun. Oleh karena itu, pertandingan dibatalkan."},
{kat:"Kata Sambung", kanji:"すなわち", kana:"すなわち", romaji:"sunawachi", arti:"dengan kata lain", contohJp:"彼は私の父の兄、すなわち伯父です。", contohRomaji:"Kare wa watashi no chichi no ani, sunawachi oji desu.", contohId:"Dia kakak dari ayah saya, dengan kata lain paman saya."},
{kat:"Kata Sambung", kanji:"つまり", kana:"つまり", romaji:"tsumari", arti:"singkatnya", contohJp:"つまり、彼は反対だということだ。", contohRomaji:"Tsumari, kare wa hantai da to iu koto da.", contohId:"Singkatnya, dia menentang."},
{kat:"Kata Sambung", kanji:"反対に", kana:"はんたいに", romaji:"hantai ni", arti:"sebaliknya", contohJp:"反対に、私はその意見に賛成だ。", contohRomaji:"Hantai ni, watashi wa sono iken ni sansei da.", contohId:"Sebaliknya, saya setuju dengan pendapat itu."},
{kat:"Kata Sambung", kanji:"さて", kana:"さて", romaji:"sate", arti:"nah, baiklah", contohJp:"さて、そろそろ始めましょう。", contohRomaji:"Sate, sorosoro hajimemashou.", contohId:"Nah, ayo kita mulai sekarang."},
{kat:"Kata Sambung", kanji:"なお", kana:"なお", romaji:"nao", arti:"selain itu, perlu dicatat", contohJp:"なお、詳細は後日お知らせします。", contohRomaji:"Nao, shousai wa gojitsu oshirase shimasu.", contohId:"Selain itu, rincian akan diberitahukan kemudian."},
{kat:"Kata Sambung", kanji:"ただし", kana:"ただし", romaji:"tadashi", arti:"tetapi (dengan syarat)", contohJp:"参加できます。ただし、予約が必要です。", contohRomaji:"Sanka dekimasu. Tadashi, yoyaku ga hitsuyou desu.", contohId:"Bisa ikut serta. Tetapi, perlu reservasi."},
{kat:"Kata Sambung", kanji:"むしろ", kana:"むしろ", romaji:"mushiro", arti:"malah, lebih tepatnya", contohJp:"忙しいというより、むしろ暇だ。", contohRomaji:"Isogashii to iu yori, mushiro hima da.", contohId:"Bukannya sibuk, malah lebih tepatnya senggang."},
{kat:"Kata Sambung", kanji:"あるいは", kana:"あるいは", romaji:"arui wa", arti:"atau (mungkin)", contohJp:"明日、あるいは明後日行きます。", contohRomaji:"Ashita, arui wa asatte ikimasu.", contohId:"Saya akan pergi besok, atau lusa."},
{kat:"Kata Sambung", kanji:"もしくは", kana:"もしくは", romaji:"moshiku wa", arti:"atau", contohJp:"ペン、もしくは鉛筆を使ってください。", contohRomaji:"Pen, moshiku wa enpitsu o tsukatte kudasai.", contohId:"Silakan gunakan pena, atau pensil."},
{kat:"Kata Sambung", kanji:"ゆえに", kana:"ゆえに", romaji:"yue ni", arti:"oleh karena itu (formal)", contohJp:"証拠がない。ゆえに、彼は無罪だ。", contohRomaji:"Shouko ga nai. Yue ni, kare wa muzai da.", contohId:"Tidak ada bukti. Oleh karena itu, dia tidak bersalah."},

// ================= 8. KATA SERAPAN (KATAKANA-GO) =================
{kat:"Kata Serapan", kanji:"システム", kana:"システム", romaji:"shisutemu", arti:"sistem", contohJp:"新しいシステムを導入した。", contohRomaji:"Atarashii shisutemu o dounyuu shita.", contohId:"Sistem baru sudah diperkenalkan."},
{kat:"Kata Serapan", kanji:"サービス", kana:"サービス", romaji:"saabisu", arti:"layanan", contohJp:"このホテルはサービスがいい。", contohRomaji:"Kono hoteru wa saabisu ga ii.", contohId:"Layanan hotel ini bagus."},
{kat:"Kata Serapan", kanji:"スケジュール", kana:"スケジュール", romaji:"sukejuuru", arti:"jadwal", contohJp:"スケジュールを確認してください。", contohRomaji:"Sukejuuru o kakunin shite kudasai.", contohId:"Tolong periksa jadwalnya."},
{kat:"Kata Serapan", kanji:"イメージ", kana:"イメージ", romaji:"imeeji", arti:"citra, gambaran", contohJp:"会社のイメージを大切にする。", contohRomaji:"Kaisha no imeeji o taisetsu ni suru.", contohId:"Menjaga citra perusahaan."},
{kat:"Kata Serapan", kanji:"アイデア", kana:"アイデア", romaji:"aidea", arti:"ide", contohJp:"いいアイデアが浮かんだ。", contohRomaji:"Ii aidea ga ukanda.", contohId:"Saya mendapat ide bagus."},
{kat:"Kata Serapan", kanji:"チャンス", kana:"チャンス", romaji:"chansu", arti:"kesempatan", contohJp:"このチャンスを逃したくない。", contohRomaji:"Kono chansu o nogashitakunai.", contohId:"Saya tidak mau melewatkan kesempatan ini."},
{kat:"Kata Serapan", kanji:"バランス", kana:"バランス", romaji:"baransu", arti:"keseimbangan", contohJp:"仕事と生活のバランスが大切だ。", contohRomaji:"Shigoto to seikatsu no baransu ga taisetsu da.", contohId:"Keseimbangan kerja dan kehidupan itu penting."},
{kat:"Kata Serapan", kanji:"ストレス", kana:"ストレス", romaji:"sutoresu", arti:"stres", contohJp:"最近ストレスが溜まっている。", contohRomaji:"Saikin sutoresu ga tamatte iru.", contohId:"Akhir-akhir ini stres saya menumpuk."},
{kat:"Kata Serapan", kanji:"リサイクル", kana:"リサイクル", romaji:"risaikuru", arti:"daur ulang", contohJp:"ペットボトルをリサイクルする。", contohRomaji:"Petto botoru o risaikuru suru.", contohId:"Botol plastik didaur ulang."},
{kat:"Kata Serapan", kanji:"エネルギー", kana:"エネルギー", romaji:"enerugii", arti:"energi", contohJp:"太陽エネルギーを利用する。", contohRomaji:"Taiyou enerugii o riyou suru.", contohId:"Memanfaatkan energi matahari."},
{kat:"Kata Serapan", kanji:"データ", kana:"データ", romaji:"deeta", arti:"data", contohJp:"データを分析する。", contohRomaji:"Deeta o bunseki suru.", contohId:"Menganalisis data."},
{kat:"Kata Serapan", kanji:"レベル", kana:"レベル", romaji:"reberu", arti:"level, tingkat", contohJp:"日本語のレベルが上がった。", contohRomaji:"Nihongo no reberu ga agatta.", contohId:"Level bahasa Jepang saya sudah naik."},
{kat:"Kata Serapan", kanji:"トラブル", kana:"トラブル", romaji:"toraburu", arti:"masalah, gangguan", contohJp:"機械にトラブルが起きた。", contohRomaji:"Kikai ni toraburu ga okita.", contohId:"Terjadi gangguan pada mesin."},
{kat:"Kata Serapan", kanji:"パターン", kana:"パターン", romaji:"pataan", arti:"pola", contohJp:"いつも同じパターンで失敗する。", contohRomaji:"Itsumo onaji pataan de shippai suru.", contohId:"Selalu gagal dengan pola yang sama."},
{kat:"Kata Serapan", kanji:"マナー", kana:"マナー", romaji:"manaa", arti:"sopan santun, etika", contohJp:"食事のマナーを守る。", contohRomaji:"Shokuji no manaa o mamoru.", contohId:"Menjaga etika makan."},
{kat:"Kata Serapan", kanji:"プライバシー", kana:"プライバシー", romaji:"puraibashii", arti:"privasi", contohJp:"プライバシーを守ってほしい。", contohRomaji:"Puraibashii o mamotte hoshii.", contohId:"Saya ingin privasi saya dijaga."},
{kat:"Kata Serapan", kanji:"ボランティア", kana:"ボランティア", romaji:"borantia", arti:"relawan", contohJp:"ボランティア活動に参加した。", contohRomaji:"Borantia katsudou ni sanka shita.", contohId:"Saya ikut kegiatan relawan."},
{kat:"Kata Serapan", kanji:"キャンセル", kana:"キャンセル", romaji:"kyanseru", arti:"membatalkan", contohJp:"予約をキャンセルした。", contohRomaji:"Yoyaku o kyanseru shita.", contohId:"Saya membatalkan reservasi."},
{kat:"Kata Serapan", kanji:"コミュニケーション", kana:"コミュニケーション", romaji:"komyunikeeshon", arti:"komunikasi", contohJp:"コミュニケーションが大切だ。", contohRomaji:"Komyunikeeshon ga taisetsu da.", contohId:"Komunikasi itu penting."},
{kat:"Kata Serapan", kanji:"タイミング", kana:"タイミング", romaji:"taimingu", arti:"waktu yang tepat, timing", contohJp:"タイミングが悪かった。", contohRomaji:"Taimingu ga warukatta.", contohId:"Timingnya kurang tepat."},

// ================= 9. ONOMATOPE (GIONGO/GITAIGO) =================
{kat:"Onomatope", kanji:"どきどき", kana:"どきどき", romaji:"dokidoki", arti:"deg-degan", contohJp:"面接の前で胸がどきどきした。", contohRomaji:"Mensetsu no mae de mune ga dokidoki shita.", contohId:"Dada saya deg-degan sebelum wawancara."},
{kat:"Onomatope", kanji:"わくわく", kana:"わくわく", romaji:"wakuwaku", arti:"berdebar senang, tak sabar", contohJp:"旅行のことを考えるとわくわくする。", contohRomaji:"Ryokou no koto o kangaeru to wakuwaku suru.", contohId:"Saya jadi tak sabar kalau memikirkan liburan."},
{kat:"Onomatope", kanji:"いらいら", kana:"いらいら", romaji:"iraira", arti:"kesal, gelisah", contohJp:"渋滞でいらいらした。", contohRomaji:"Juutai de iraira shita.", contohId:"Saya kesal karena macet."},
{kat:"Onomatope", kanji:"のんびり", kana:"のんびり", romaji:"nonbiri", arti:"santai", contohJp:"休みの日はのんびり過ごしたい。", contohRomaji:"Yasumi no hi wa nonbiri sugoshitai.", contohId:"Di hari libur saya ingin bersantai."},
{kat:"Onomatope", kanji:"ぐっすり", kana:"ぐっすり", romaji:"gussuri", arti:"tidur nyenyak", contohJp:"疲れてぐっすり眠った。", contohRomaji:"Tsukarete gussuri nemutta.", contohId:"Saya lelah dan tidur nyenyak."},
{kat:"Onomatope", kanji:"がっかり", kana:"がっかり", romaji:"gakkari", arti:"kecewa", contohJp:"試験に落ちてがっかりした。", contohRomaji:"Shiken ni ochite gakkari shita.", contohId:"Saya kecewa karena gagal ujian."},
{kat:"Onomatope", kanji:"うっかり", kana:"うっかり", romaji:"ukkari", arti:"lengah, ceroboh", contohJp:"うっかり傘を忘れた。", contohRomaji:"Ukkari kasa o wasureta.", contohId:"Saya lengah dan lupa membawa payung."},
{kat:"Onomatope", kanji:"しっかり", kana:"しっかり", romaji:"shikkari", arti:"dengan kuat, sungguh-sungguh", contohJp:"しっかり勉強してください。", contohRomaji:"Shikkari benkyou shite kudasai.", contohId:"Belajarlah dengan sungguh-sungguh."},
{kat:"Onomatope", kanji:"はっきり", kana:"はっきり", romaji:"hakkiri", arti:"jelas", contohJp:"はっきりと意見を言った。", contohRomaji:"Hakkiri to iken o itta.", contohId:"Saya menyampaikan pendapat dengan jelas."},
{kat:"Onomatope", kanji:"びっくり", kana:"びっくり", romaji:"bikkuri", arti:"kaget", contohJp:"大きな音にびっくりした。", contohRomaji:"Ookina oto ni bikkuri shita.", contohId:"Saya kaget mendengar suara keras."},
{kat:"Onomatope", kanji:"すっきり", kana:"すっきり", romaji:"sukkiri", arti:"lega, segar", contohJp:"シャワーを浴びてすっきりした。", contohRomaji:"Shawaa o abite sukkiri shita.", contohId:"Saya merasa segar setelah mandi shower."},
{kat:"Onomatope", kanji:"ぺらぺら", kana:"ぺらぺら", romaji:"perapera", arti:"lancar (bahasa)", contohJp:"彼は英語がぺらぺらだ。", contohRomaji:"Kare wa eigo ga perapera da.", contohId:"Dia lancar berbahasa Inggris."},
{kat:"Onomatope", kanji:"ばらばら", kana:"ばらばら", romaji:"barabara", arti:"berantakan, tercerai-berai", contohJp:"意見がばらばらでまとまらない。", contohRomaji:"Iken ga barabara de matomaranai.", contohId:"Pendapatnya berbeda-beda dan sulit disatukan."},
{kat:"Onomatope", kanji:"ぎりぎり", kana:"ぎりぎり", romaji:"girigiri", arti:"mepet (waktu/batas)", contohJp:"ぎりぎりで電車に間に合った。", contohRomaji:"Girigiri de densha ni maniatta.", contohId:"Saya berhasil mengejar kereta dengan mepet."},
{kat:"Onomatope", kanji:"にこにこ", kana:"にこにこ", romaji:"nikoniko", arti:"tersenyum-senyum", contohJp:"彼女はいつもにこにこしている。", contohRomaji:"Kanojo wa itsumo nikoniko shite iru.", contohId:"Dia selalu tersenyum-senyum."},

// ================= 10. KATA BENDA: PERASAAN & ABSTRAK =================
{kat:"Perasaan & Abstrak", kanji:"印象", kana:"いんしょう", romaji:"inshou", arti:"kesan", contohJp:"いい印象を与えたい。", contohRomaji:"Ii inshou o ataetai.", contohId:"Saya ingin memberikan kesan yang baik."},
{kat:"Perasaan & Abstrak", kanji:"感想", kana:"かんそう", romaji:"kansou", arti:"kesan, pendapat (setelah mengalami)", contohJp:"映画の感想を聞かせて。", contohRomaji:"Eiga no kansou o kikasete.", contohId:"Ceritakan kesanmu tentang filmnya."},
{kat:"Perasaan & Abstrak", kanji:"態度", kana:"たいど", romaji:"taido", arti:"sikap", contohJp:"彼の態度が気になる。", contohRomaji:"Kare no taido ga ki ni naru.", contohId:"Sikapnya membuat saya khawatir."},
{kat:"Perasaan & Abstrak", kanji:"性格", kana:"せいかく", romaji:"seikaku", arti:"kepribadian", contohJp:"彼女は明るい性格だ。", contohRomaji:"Kanojo wa akarui seikaku da.", contohId:"Dia berkepribadian ceria."},
{kat:"Perasaan & Abstrak", kanji:"能力", kana:"のうりょく", romaji:"nouryoku", arti:"kemampuan", contohJp:"彼には高い能力がある。", contohRomaji:"Kare ni wa takai nouryoku ga aru.", contohId:"Dia memiliki kemampuan yang tinggi."},
{kat:"Perasaan & Abstrak", kanji:"才能", kana:"さいのう", romaji:"sainou", arti:"bakat", contohJp:"音楽の才能がある。", contohRomaji:"Ongaku no sainou ga aru.", contohId:"Dia memiliki bakat musik."},
{kat:"Perasaan & Abstrak", kanji:"自信", kana:"じしん", romaji:"jishin", arti:"percaya diri", contohJp:"自信を持って話してください。", contohRomaji:"Jishin o motte hanashite kudasai.", contohId:"Bicaralah dengan percaya diri."},
{kat:"Perasaan & Abstrak", kanji:"我慢", kana:"がまん", romaji:"gaman", arti:"menahan diri, sabar", contohJp:"痛みを我慢した。", contohRomaji:"Itami o gaman shita.", contohId:"Saya menahan rasa sakit."},
{kat:"Perasaan & Abstrak", kanji:"緊張", kana:"きんちょう", romaji:"kinchou", arti:"tegang, gugup", contohJp:"面接でとても緊張した。", contohRomaji:"Mensetsu de totemo kinchou shita.", contohId:"Saya sangat gugup saat wawancara."},
{kat:"Perasaan & Abstrak", kanji:"興味", kana:"きょうみ", romaji:"kyoumi", arti:"minat", contohJp:"日本の文化に興味がある。", contohRomaji:"Nihon no bunka ni kyoumi ga aru.", contohId:"Saya tertarik pada budaya Jepang."},
{kat:"Perasaan & Abstrak", kanji:"感情", kana:"かんじょう", romaji:"kanjou", arti:"emosi", contohJp:"感情をコントロールするのは難しい。", contohRomaji:"Kanjou o kontorooru suru no wa muzukashii.", contohId:"Mengendalikan emosi itu sulit."},
{kat:"Perasaan & Abstrak", kanji:"意識", kana:"いしき", romaji:"ishiki", arti:"kesadaran", contohJp:"安全への意識を高める。", contohRomaji:"Anzen e no ishiki o takameru.", contohId:"Meningkatkan kesadaran akan keselamatan."},
{kat:"Perasaan & Abstrak", kanji:"傾向", kana:"けいこう", romaji:"keikou", arti:"kecenderungan", contohJp:"最近この傾向が強くなっている。", contohRomaji:"Saikin kono keikou ga tsuyoku natte iru.", contohId:"Belakangan ini kecenderungan ini semakin kuat."},
{kat:"Perasaan & Abstrak", kanji:"状態", kana:"じょうたい", romaji:"joutai", arti:"keadaan", contohJp:"体の状態が良くない。", contohRomaji:"Karada no joutai ga yokunai.", contohId:"Keadaan tubuh saya kurang baik."},
{kat:"Perasaan & Abstrak", kanji:"欲", kana:"よく", romaji:"yoku", arti:"keinginan, nafsu", contohJp:"食欲がない。", contohRomaji:"Shokuyoku ga nai.", contohId:"Saya tidak ada nafsu makan."},
];
