// ===================================================================
// Qategori Nihongo - Reading (読解) JLPT N3
// Furigana: {漢字|かんじ} (kata dalam kurung kurawal, bacaan setelah |, okurigana di luar kurung)
// tipe: tanbun (bacaan pendek), chuubun (menengah), chouubun (panjang), jouhou (pencarian informasi)
// ===================================================================
window.N3_READING = [

{id:"n3r01", tipe:"tanbun", topik:"Email kantor",
 judul:"{会議|かいぎ}の{時間|じかん}{変更|へんこう}のお{知|し}らせ",
 teks:"{営業部|えいぎょうぶ}の{皆|みな}さまへ\n{来週|らいしゅう}{火曜日|かようび}の{会議|かいぎ}は、{部長|ぶちょう}の{都合|つごう}で、{午前|ごぜん}10{時|じ}から{午後|ごご}2{時|じ}に{変更|へんこう}になりました。{場所|ばしょ}は{変|か}わらず、{三階|さんがい}の{会議室|かいぎしつ}です。{資料|しりょう}は{前日|ぜんじつ}までにメールで{送|おく}ってください。{午前|ごぜん}に{予定|よてい}を{入|い}れていた{人|ひと}は、{調整|ちょうせい}をお{願|ねが}いします。\n{山田|やまだ}",
 terjemahan:"Kepada seluruh anggota Departemen Penjualan.\nRapat hari Selasa minggu depan, karena kepentingan kepala departemen, diubah dari pukul 10 pagi menjadi pukul 2 siang. Tempatnya tidak berubah, yaitu ruang rapat di lantai tiga. Kirimkan materi lewat email paling lambat sehari sebelumnya. Bagi yang sudah membuat jadwal di pagi hari, mohon disesuaikan.\nYamada",
 soal:[
  {q:"{会議|かいぎ}はどうなりましたか。", opt:["{場所|ばしょ}が{変|か}わった","{時間|じかん}が{午後|ごご}に{変|か}わった","{中止|ちゅうし}になった","{日|ひ}にちが{変|か}わった"], correct:1, exp:"Teks menyebut 午前10時から午後2時に変更. Tempat tidak berubah (場所は変わらず), dan harinya tetap Selasa."},
  {q:"{会議|かいぎ}に{出|で}る{人|ひと}は、{前日|ぜんじつ}までに{何|なに}をしなければなりませんか。", opt:["{場所|ばしょ}を{予約|よやく}する","{部長|ぶちょう}に{連絡|れんらく}する","{資料|しりょう}をメールで{送|おく}る","{午前|ごぜん}の{予定|よてい}をやめる"], correct:2, exp:"資料は前日までにメールで送ってください. Penyesuaian jadwal pagi diminta, tetapi tidak dibatasi 'sampai sehari sebelumnya'."}
 ]},

{id:"n3r02", tipe:"tanbun", topik:"Esai pribadi",
 judul:"{朝|あさ}のジョギング",
 teks:"{私|わたし}は{去年|きょねん}から、{毎朝|まいあさ}{近|ちか}くの{公園|こうえん}で{走|はし}っています。{始|はじ}めたころは、{五分|ごふん}も{続|つづ}かなくて、すぐにやめたいと{思|おも}いました。でも、{友達|ともだち}に「{速|はや}く{走|はし}ろうとしないで、{歩|ある}くようにゆっくり{走|はし}ればいい」と{言|い}われてから、{楽|たの}しくなりました。{今|いま}は{三十分|さんじゅっぷん}{走|はし}っても{疲|つか}れません。{体|からだ}だけでなく、{気持|きも}ちも{元気|げんき}になった{気|き}がします。",
 terjemahan:"Sejak tahun lalu, setiap pagi saya berlari di taman dekat rumah. Di awal, saya tidak sanggup bertahan bahkan lima menit dan langsung ingin berhenti. Tetapi sejak teman berkata, \"Jangan berusaha berlari cepat, larilah pelan seperti berjalan saja,\" lari jadi menyenangkan. Sekarang, berlari 30 menit pun saya tidak lelah. Rasanya bukan hanya badan, perasaan pun jadi bersemangat.",
 soal:[
  {q:"「{私|わたし}」が{走|はし}るのを{続|つづ}けられるようになったのはなぜですか。", opt:["{公園|こうえん}が{家|いえ}の{近|ちか}くにあったから","{友達|ともだち}と{一緒|いっしょ}に{走|はし}るようになったから","ゆっくり{走|はし}ってもいいと{言|い}われたから","{毎日|まいにち}{三十分|さんじゅっぷん}{走|はし}ったから"], correct:2, exp:"Teman menyarankan 歩くようにゆっくり走ればいい, setelah itu 楽しくなりました. Teman hanya memberi saran, bukan berlari bersama."},
  {q:"{今|いま}の「{私|わたし}」について、{正|ただ}しいものはどれですか。", opt:["{三十分|さんじゅっぷん}{走|はし}っても{疲|つか}れない","{五分|ごふん}しか{走|はし}れない","{体|からだ}は{元気|げんき}だが、{気持|きも}ちは{疲|つか}れている","{速|はや}く{走|はし}れるようになった"], correct:0, exp:"今は三十分走っても疲れません. Bagian 気持ちも元気になった menolak pilihan ketiga."}
 ]},

{id:"n3r03", tipe:"tanbun", topik:"Pengumuman",
 judul:"{市立図書館|しりつとしょかん}からのお{知|し}らせ",
 teks:"{図書館|としょかん}は、{来月|らいげつ}1{日|にち}から{三週間|さんしゅうかん}、{工事|こうじ}のため{休|やす}みます。この{間|あいだ}は、{本|ほん}を{借|か}りることも{返|かえ}すこともできません。ただし、{入口|いりぐち}の{横|よこ}にある{返却|へんきゃく}ポストには、いつでも{本|ほん}を{返|かえ}すことができます。{借|か}りている{本|ほん}の{返|かえ}す{日|ひ}は、{自動的|じどうてき}に{工事|こうじ}のあとになります。",
 terjemahan:"Perpustakaan akan tutup selama tiga minggu mulai tanggal 1 bulan depan karena ada pekerjaan konstruksi. Selama itu, buku tidak dapat dipinjam maupun dikembalikan. Namun, di kotak pengembalian di samping pintu masuk, buku bisa dikembalikan kapan saja. Tanggal pengembalian buku yang sedang dipinjam otomatis menjadi setelah pekerjaan konstruksi.",
 soal:[
  {q:"{工事|こうじ}の{間|あいだ}、{図書館|としょかん}の{利用者|りようしゃ}はどうすることができますか。", opt:["{本|ほん}を{借|か}りることだけできる","{返却|へんきゃく}ポストに{本|ほん}を{返|かえ}すことができる","{図書館|としょかん}の{中|なか}で{本|ほん}が{読|よ}める","{何|なに}もできない"], correct:1, exp:"Ada 返却ポスト di samping pintu masuk yang bisa dipakai いつでも. Meminjam tidak bisa, dan perpustakaan tutup."},
  {q:"{借|か}りている{本|ほん}の{返|かえ}す{日|ひ}はどうなりますか。", opt:["{来月|らいげつ}1{日|にち}になる","{工事|こうじ}の{前|まえ}になる","{工事|こうじ}のあとになる","{変|か}わらない"], correct:2, exp:"自動的に工事のあとになります. Jadi tanggal pengembalian otomatis mundur."}
 ]},

{id:"n3r04", tipe:"jouhou", topik:"Iklan / brosur",
 judul:"{料理教室|りょうりきょうしつ}のご{案内|あんない}",
 teks:"A コース　{和食|わしょく}　{毎週|まいしゅう}{月曜日|げつようび}　{夜|よる}7{時|じ}～9{時|じ}　4{回|かい}　6,000{円|えん}\nB コース　{洋食|ようしょく}　{毎週|まいしゅう}{水曜日|すいようび}　{午前|ごぜん}10{時|じ}～12{時|じ}　4{回|かい}　7,000{円|えん}\nC コース　お{菓子|かし}　{第|だい}1・3{土曜日|どようび}　{午後|ごご}1{時|じ}～4{時|じ}　2{回|かい}　5,000{円|えん}\n{申|もう}し{込|こ}みは、{始|はじ}まる{前|まえ}の{週|しゅう}の{金曜日|きんようび}までです。{材料費|ざいりょうひ}は{料金|りょうきん}に{含|ふく}まれています。{学生|がくせい}は、{料金|りょうきん}が1{割|わり}{安|やす}くなります。",
 terjemahan:"Kelas A: masakan Jepang, setiap Senin, pukul 7–9 malam, 4 pertemuan, 6.000 yen.\nKelas B: masakan Barat, setiap Rabu, pukul 10–12 pagi, 4 pertemuan, 7.000 yen.\nKelas C: kue/manisan, Sabtu pertama dan ketiga, pukul 1–4 siang, 2 pertemuan, 5.000 yen.\nPendaftaran paling lambat Jumat di minggu sebelum kelas dimulai. Biaya bahan sudah termasuk dalam tarif. Pelajar mendapat diskon 10%.",
 soal:[
  {q:"{平日|へいじつ}の{夜|よる}に{和食|わしょく}を{習|なら}いたい{会社員|かいしゃいん}は、どのコースを{選|えら}べばいいですか。", opt:["Aコース","Bコース","Cコース","どのコースもだめ"], correct:0, exp:"和食 = Kelas A, setiap Senin malam (平日の夜). Kelas B pagi hari, Kelas C hari Sabtu."},
  {q:"{学生|がくせい}のマリアさんがBコースを{申|もう}し{込|こ}むと、{料金|りょうきん}はいくらですか。", opt:["6,300{円|えん}","7,000{円|えん}","6,000{円|えん}","5,400{円|えん}"], correct:0, exp:"Kelas B 7.000 yen, diskon 1割 (10%) = 700 yen, jadi 6.300 yen."}
 ]},

{id:"n3r05", tipe:"chuubun", topik:"Masyarakat",
 judul:"{電子書籍|でんししょせき}と{紙|かみ}の{本|ほん}",
 teks:"{最近|さいきん}、{電子書籍|でんししょせき}を{読|よ}む{人|ひと}が{増|ふ}えています。スマートフォンやタブレットがあれば、いつでもどこでも{本|ほん}が{読|よ}めるし、{何冊|なんさつ}{持|も}っていても{重|おも}くならないからです。{私|わたし}も、{旅行|りょこう}のときは{電子書籍|でんししょせき}を{使|つか}っています。\nしかし、{紙|かみ}の{本|ほん}にも{良|よ}いところがあります。{紙|かみ}をめくる{感|かん}じや、{紙|かみ}のにおいが{好|す}きだという{人|ひと}は{多|おお}いです。また、{画面|がめん}を{長|なが}い{間|あいだ}{見|み}ていると{目|め}が{疲|つか}れますが、{紙|かみ}の{本|ほん}ではそれが{少|すく}ないと{言|い}われています。\n{私|わたし}は、{場面|ばめん}によって{使|つか}い{分|わ}けるのが{一番|いちばん}いいと{思|おも}います。",
 terjemahan:"Belakangan ini orang yang membaca buku elektronik semakin banyak. Sebab, jika punya ponsel pintar atau tablet, buku bisa dibaca kapan saja di mana saja, dan berapa pun buku yang dibawa tidak jadi berat. Saya sendiri memakai buku elektronik saat bepergian.\nNamun, buku kertas juga punya kelebihan. Banyak orang menyukai sensasi membalik halaman dan aroma kertas. Selain itu, menatap layar lama-lama membuat mata lelah, sedangkan pada buku kertas hal itu dikatakan lebih sedikit.\nMenurut saya, yang paling baik adalah menggunakannya sesuai situasi.",
 soal:[
  {q:"{電子書籍|でんししょせき}を{読|よ}む{人|ひと}が{増|ふ}えている{理由|りゆう}は{何|なん}ですか。", opt:["{紙|かみ}の{本|ほん}より{値段|ねだん}が{安|やす}いから","{目|め}が{疲|つか}れないから","いつでもどこでも{読|よ}めて、{重|おも}くないから","{旅行|りょこう}が{増|ふ}えたから"], correct:2, exp:"Alasan yang disebut: いつでもどこでも読める dan 何冊持っていても重くならない. Harga tidak dibahas."},
  {q:"{紙|かみ}の{本|ほん}の{良|よ}いところとして、{文章|ぶんしょう}に{書|か}かれていないものはどれですか。", opt:["{紙|かみ}をめくる{感|かん}じ","{紙|かみ}のにおい","{目|め}が{疲|つか}れにくいこと","{値段|ねだん}が{安|やす}いこと"], correct:3, exp:"Disebut: sensasi membalik kertas, aroma kertas, mata tidak mudah lelah. Soal harga tidak disebut."},
  {q:"{筆者|ひっしゃ}の{考|かんが}えに{合|あ}うものはどれですか。", opt:["{電子書籍|でんししょせき}だけを{使|つか}うのがいい","{紙|かみ}の{本|ほん}だけを{使|つか}うのがいい","{場面|ばめん}に{合|あ}わせて{使|つか}い{分|わ}けるのがいい","どちらも{使|つか}わないほうがいい"], correct:2, exp:"Kalimat terakhir: 場面によって使い分けるのが一番いい."}
 ]},

{id:"n3r06", tipe:"chuubun", topik:"Kehidupan",
 judul:"{初|はじ}めての{一人暮|ひとりぐ}らし",
 teks:"{大学|だいがく}に{入|はい}って、{初|はじ}めて{一人暮|ひとりぐ}らしを{始|はじ}めた。{最初|さいしょ}の{一週間|いっしゅうかん}は{自由|じゆう}で{楽|たの}しかったが、すぐに{大変|たいへん}なことに{気|き}がついた。{料理|りょうり}も{掃除|そうじ}も{洗濯|せんたく}も、{全部|ぜんぶ}{自分|じぶん}でしなければならないのだ。\n{実家|じっか}にいたころは、{母|はは}が{毎日|まいにち}ご{飯|はん}を{作|つく}ってくれた。{当|あ}たり{前|まえ}だと{思|おも}っていたが、{今|いま}になって{母|はは}の{苦労|くろう}がよくわかる。{先週|せんしゅう}、{電話|でんわ}で「ありがとう」と{言|い}ったら、{母|はは}は「{急|きゅう}にどうしたの」と{笑|わら}っていた。",
 terjemahan:"Setelah masuk universitas, saya mulai hidup sendiri untuk pertama kalinya. Seminggu pertama terasa bebas dan menyenangkan, tetapi saya segera menyadari hal yang merepotkan: memasak, bersih-bersih, dan mencuci, semuanya harus saya kerjakan sendiri.\nSaat masih di rumah orang tua, ibu memasakkan nasi setiap hari. Dulu saya anggap itu hal biasa, tapi sekarang saya benar-benar paham kerja keras ibu. Minggu lalu, ketika saya bilang \"terima kasih\" lewat telepon, ibu tertawa dan berkata, \"Kenapa tiba-tiba begitu?\"",
 soal:[
  {q:"「{大変|たいへん}なこと」とは{何|なん}ですか。", opt:["{大学|だいがく}の{勉強|べんきょう}が{難|むずか}しいこと","{家事|かじ}を{全部|ぜんぶ}{自分|じぶん}でしなければならないこと","{母|はは}に{会|あ}えないこと","{お金|かね}がなくなったこと"], correct:1, exp:"Dijelaskan setelah tanda hubung: 料理も掃除も洗濯も、全部自分でしなければならない. Itulah 'hal yang merepotkan'."},
  {q:"{母|はは}が{笑|わら}っていたのはなぜだと{考|かんが}えられますか。", opt:["{電話|でんわ}の{声|こえ}が{面白|おもしろ}かったから","「{私|わたし}」が{急|きゅう}にお{礼|れい}を{言|い}ったから","「{私|わたし}」が{家|いえ}に{帰|かえ}ってきたから","{母|はは}が{忙|いそが}しかったから"], correct:1, exp:"Ibu bertanya 急にどうしたの (kenapa tiba-tiba) setelah mendengar ありがとう, jadi ia heran sekaligus geli karena diberi ucapan terima kasih mendadak."}
 ]},

{id:"n3r07", tipe:"chuubun", topik:"Kesehatan",
 judul:"{睡眠|すいみん}と{健康|けんこう}",
 teks:"{睡眠|すいみん}の{時間|じかん}が{短|みじか}いと、{病気|びょうき}になりやすいと{言|い}われている。ある{研究|けんきゅう}によると、{毎日|まいにち}6{時間|じかん}より{少|すく}ない{人|ひと}は、7{時間|じかん}{以上|いじょう}{寝|ね}る{人|ひと}より、{風邪|かぜ}を{引|ひ}く{割合|わりあい}が{高|たか}かったそうだ。\nでは、よく{眠|ねむ}るためにはどうすればいいだろうか。{寝|ね}る{前|まえ}の{一時間|いちじかん}は、スマートフォンを{見|み}ないほうがいい。{画面|がめん}の{光|ひかり}が、{眠|ねむ}くなるのをじゃまするからだ。{代|か}わりに、{軽|かる}い{運動|うんどう}をしたり、{温|あたた}かい{飲|の}み{物|もの}を{飲|の}んだりするのがおすすめだ。",
 terjemahan:"Dikatakan bahwa jika waktu tidur pendek, orang mudah jatuh sakit. Menurut suatu penelitian, orang yang tidur kurang dari 6 jam setiap hari memiliki proporsi terkena flu yang lebih tinggi dibanding orang yang tidur 7 jam atau lebih.\nLalu, bagaimana agar bisa tidur nyenyak? Satu jam sebelum tidur sebaiknya tidak melihat ponsel, karena cahaya layar mengganggu rasa kantuk. Sebagai gantinya, disarankan melakukan olahraga ringan atau minum minuman hangat.",
 soal:[
  {q:"{研究|けんきゅう}でわかったことは{何|なん}ですか。", opt:["{睡眠|すいみん}が{短|みじか}い{人|ひと}は{風邪|かぜ}を{引|ひ}きやすい","{長|なが}く{寝|ね}る{人|ひと}は{病気|びょうき}になりやすい","{運動|うんどう}する{人|ひと}は{風邪|かぜ}を{引|ひ}かない","スマートフォンを{見|み}る{人|ひと}は{寝|ね}る{時間|じかん}が{短|みじか}い"], correct:0, exp:"6時間より少ない人は風邪を引く割合が高かった. Jadi tidur singkat berkaitan dengan lebih mudah sakit."},
  {q:"{寝|ね}る{前|まえ}の{一時間|いちじかん}にしないほうがいいことは{何|なに}ですか。", opt:["{軽|かる}い{運動|うんどう}","{温|あたた}かい{飲|の}み{物|もの}を{飲|の}むこと","スマートフォンを{見|み}ること","{音楽|おんがく}を{聞|き}くこと"], correct:2, exp:"寝る前の一時間はスマートフォンを見ないほうがいい. Olahraga ringan dan minuman hangat justru disarankan."}
 ]},

{id:"n3r08", tipe:"chuubun", topik:"Budaya",
 judul:"{日本|にほん}の{自動販売機|じどうはんばいき}",
 teks:"{日本|にほん}には、{自動販売機|じどうはんばいき}がとても{多|おお}い。{飲|の}み{物|もの}だけでなく、{食|た}べ{物|もの}や{傘|かさ}まで{売|う}っている。{外国|がいこく}から{来|き}た{人|ひと}は、{夜|よる}{遅|おそ}くても{道|みち}に{明|あか}るい{機械|きかい}があって、{安全|あんぜん}にお{金|かね}を{使|つか}えることに{驚|おどろ}くそうだ。\n{一方|いっぽう}、{電気|でんき}をたくさん{使|つか}うことが{問題|もんだい}になっている。そこで{最近|さいきん}は、{使|つか}う{電気|でんき}の{量|りょう}を{減|へ}らした{新|あたら}しい{機械|きかい}が{増|ふ}えてきた。",
 terjemahan:"Di Jepang, mesin penjual otomatis sangat banyak. Tidak hanya minuman, bahkan makanan dan payung pun dijual. Konon orang asing terkejut karena bahkan larut malam di jalan ada mesin yang terang dan mereka bisa memakai uang dengan aman.\nDi sisi lain, pemakaian listrik yang besar menjadi masalah. Karena itu, belakangan ini mesin baru yang jumlah listriknya dikurangi semakin banyak.",
 soal:[
  {q:"{外国|がいこく}の{人|ひと}は、{何|なに}に{驚|おどろ}くと{言|い}われていますか。", opt:["{自動販売機|じどうはんばいき}が{高|たか}いこと","{夜|よる}{遅|おそ}くても{安全|あんぜん}にお{金|かね}を{使|つか}えること","{傘|かさ}が{売|う}っていないこと","{機械|きかい}が{壊|こわ}れやすいこと"], correct:1, exp:"Dikatakan 夜遅くても道に明るい機械があって、安全にお金を使えることに驚く."},
  {q:"「そこで」の{後|あと}に{書|か}かれているのはどんな{内容|ないよう}ですか。", opt:["{問題|もんだい}に{対|たい}する{対策|たいさく}","{問題|もんだい}の{原因|げんいん}","{外国人|がいこくじん}の{感想|かんそう}","{自動販売機|じどうはんばいき}の{歴史|れきし}"], correct:0, exp:"Setelah 'そこで' (karena itu) dijelaskan langkah mengatasi masalah listrik: mesin hemat listrik semakin banyak."}
 ]},

{id:"n3r09", tipe:"chouubun", topik:"Esai pekerjaan",
 judul:"{失敗|しっぱい}から{学|まな}んだこと",
 teks:"{私|わたし}は{去年|きょねん}、{初|はじ}めて{大|おお}きな{仕事|しごと}を{任|まか}された。{新|あたら}しい{商品|しょうひん}の{発表会|はっぴょうかい}を{企画|きかく}する{仕事|しごと}だった。うれしかったが、{同時|どうじ}に{不安|ふあん}でもあった。\n{発表会|はっぴょうかい}の{当日|とうじつ}、{大|おお}きな{問題|もんだい}が{起|お}きた。{準備|じゅんび}していたパソコンが、{動|うご}かなくなったのだ。{私|わたし}は{頭|あたま}が{真|ま}っ{白|しろ}になり、{何|なに}もできなかった。その{時|とき}、{先輩|せんぱい}が{自分|じぶん}のパソコンを{貸|か}してくれて、{発表会|はっぴょうかい}は{無事|ぶじ}に{終|お}わった。\n{後|あと}で、{先輩|せんぱい}は「{失敗|しっぱい}は{誰|だれ}にでもある。{大切|たいせつ}なのは、{次|つぎ}に{同|おな}じことが{起|お}きないように、{何|なに}をすればいいか{考|かんが}えることだ」と{言|い}った。それから{私|わたし}は、{大事|だいじ}な{仕事|しごと}の{前|まえ}には、{必|かなら}ず{予備|よび}の{道具|どうぐ}を{用意|ようい}することにしている。{失敗|しっぱい}したことは、はずかしいが、あの{経験|けいけん}のおかげで、{少|すこ}し{強|つよ}くなれたと{思|おも}う。",
 terjemahan:"Tahun lalu, untuk pertama kalinya saya dipercaya memegang pekerjaan besar: merencanakan acara peluncuran produk baru. Saya senang, tetapi sekaligus cemas.\nPada hari acara, terjadi masalah besar. Komputer yang sudah disiapkan tidak bisa menyala. Kepala saya kosong dan saya tidak bisa berbuat apa-apa. Saat itu, senior meminjamkan komputernya sendiri, dan acara pun selesai dengan lancar.\nKemudian senior berkata, \"Kegagalan bisa dialami siapa saja. Yang penting adalah memikirkan apa yang harus dilakukan agar hal yang sama tidak terulang.\" Sejak itu, sebelum pekerjaan penting saya selalu menyiapkan peralatan cadangan. Gagal itu memalukan, tetapi berkat pengalaman itu saya merasa menjadi sedikit lebih kuat.",
 soal:[
  {q:"{発表会|はっぴょうかい}の{当日|とうじつ}、{何|なに}が{起|お}きましたか。", opt:["{先輩|せんぱい}が{来|こ}なかった","{準備|じゅんび}したパソコンが{動|うご}かなくなった","{資料|しりょう}を{忘|わす}れた","{商品|しょうひん}が{届|とど}かなかった"], correct:1, exp:"Kalimat: 準備していたパソコンが、動かなくなったのだ."},
  {q:"{先輩|せんぱい}の{言葉|ことば}の{意味|いみ}として{合|あ}うものはどれですか。", opt:["{失敗|しっぱい}しないように{気|き}をつけるべきだ","{失敗|しっぱい}したら、{次|つぎ}は{同|おな}じことが{起|お}きないように{考|かんが}えることが{大切|たいせつ}だ","{失敗|しっぱい}は{恥|は}ずかしいから、{人|ひと}に{言|い}わないほうがいい","{失敗|しっぱい}したら、{誰|だれ}かに{助|たす}けてもらうべきだ"], correct:1, exp:"Inti ucapan senior: 次に同じことが起きないように、何をすればいいか考えることが大切."},
  {q:"「{私|わたし}」が{今|いま}、{仕事|しごと}の{前|まえ}にしていることは{何|なん}ですか。", opt:["{先輩|せんぱい}に{相談|そうだん}する","{予備|よび}の{道具|どうぐ}を{用意|ようい}する","パソコンを{新|あたら}しく{買|か}う","{早|はや}く{寝|ね}る"], correct:1, exp:"大事な仕事の前には、必ず予備の道具を用意することにしている."}
 ]},

{id:"n3r10", tipe:"jouhou", topik:"Panduan fasilitas",
 judul:"{市民|しみん}プールのご{利用案内|りようあんない}",
 teks:"【{開館時間|かいかんじかん}】\n{平日|へいじつ}　{午前|ごぜん}9{時|じ}～{午後|ごご}9{時|じ}\n{土曜|どよう}・{日曜|にちよう}・{祝日|しゅくじつ}　{午前|ごぜん}9{時|じ}～{午後|ごご}5{時|じ}\n【{休館日|きゅうかんび}】{毎月|まいつき}{第|だい}2{月曜日|げつようび}（{祝日|しゅくじつ}の{場合|ばあい}は、{次|つぎ}の{日|ひ}）\n【{料金|りょうきん}】{大人|おとな}　500{円|えん}　{中学生|ちゅうがくせい}{以下|いか}　200{円|えん}　{65歳|ろくじゅうごさい}{以上|いじょう}　250{円|えん}\n【{注意|ちゅうい}】{小学生|しょうがくせい}{以下|いか}の{子供|こども}は、{必|かなら}ず{大人|おとな}といっしょに{入|はい}ってください。{泳|およ}ぐときは、{帽子|ぼうし}を{着|つ}けてください。",
 terjemahan:"[Jam buka] Hari kerja pukul 9 pagi–9 malam. Sabtu, Minggu, hari libur nasional pukul 9 pagi–5 sore.\n[Hari tutup] Senin kedua setiap bulan (jika hari libur nasional, maka hari berikutnya).\n[Tarif] Dewasa 500 yen; SMP ke bawah 200 yen; usia 65 tahun ke atas 250 yen.\n[Perhatian] Anak SD ke bawah harus masuk bersama orang dewasa. Saat berenang, harap memakai topi renang.",
 soal:[
  {q:"{日曜日|にちようび}に{泳|およ}ぎに{行|い}きたいです。{何時|なんじ}まで{入|はい}れますか。", opt:["{午後|ごご}5{時|じ}","{午後|ごご}9{時|じ}","{午前|ごぜん}9{時|じ}","{午後|ごご}7{時|じ}"], correct:0, exp:"Hari Minggu termasuk 土曜・日曜・祝日: pukul 9 pagi sampai 午後5時."},
  {q:"70{歳|さい}のおじいさんと8{歳|さい}の{孫|まご}が{一緒|いっしょ}に{行|い}くと、{料金|りょうきん}は{全部|ぜんぶ}でいくらですか。", opt:["450{円|えん}","700{円|えん}","500{円|えん}","750{円|えん}"], correct:0, exp:"Kakek (65歳以上) 250 yen + cucu SD (中学生以下) 200 yen = 450 yen."},
  {q:"{来月|らいげつ}の{第|だい}2{月曜日|げつようび}が{祝日|しゅくじつ}のとき、{休館日|きゅうかんび}はいつですか。", opt:["{火曜日|かようび}","{日曜日|にちようび}","{月曜日|げつようび}","{水曜日|すいようび}"], correct:0, exp:"Jika Senin kedua adalah hari libur, tutupnya 次の日 = hari berikutnya, yaitu Selasa."}
 ]}

];

// Arti per kotoba untuk popup Reading. Kunci: kata|bacaan (sama dengan markup {kata|bacaan}).
window.N3_READING_GLOSS = {
  "会議|かいぎ": "rapat",
  "時間|じかん": "waktu",
  "変更|へんこう": "perubahan, mengubah",
  "知|し": "memberi tahu (知らせ・知らせる)",
  "営業部|えいぎょうぶ": "departemen penjualan",
  "皆|みな": "semuanya",
  "来週|らいしゅう": "minggu depan",
  "火曜日|かようび": "hari Selasa",
  "部長|ぶちょう": "kepala departemen",
  "都合|つごう": "kondisi/keperluan (waktu luang)",
  "午前|ごぜん": "pagi (sebelum tengah hari)",
  "時|じ": "jam (pukul)",
  "午後|ごご": "siang/sore (setelah tengah hari)",
  "場所|ばしょ": "tempat",
  "変|か": "berubah (変わる)",
  "三階|さんがい": "lantai tiga",
  "会議室|かいぎしつ": "ruang rapat",
  "資料|しりょう": "materi, dokumen",
  "前日|ぜんじつ": "hari sebelumnya",
  "送|おく": "mengirim (送る)",
  "予定|よてい": "rencana, jadwal",
  "入|い": "memasukkan (入れる)",
  "人|ひと": "orang",
  "調整|ちょうせい": "penyesuaian, mengatur",
  "願|ねが": "memohon (お願いします)",
  "山田|やまだ": "Yamada (nama keluarga)",
  "中止|ちゅうし": "pembatalan",
  "日|ひ": "hari, tanggal",
  "出|で": "keluar, hadir (出る)",
  "何|なに": "apa",
  "予約|よやく": "reservasi",
  "連絡|れんらく": "menghubungi, kontak",
  "朝|あさ": "pagi",
  "私|わたし": "saya",
  "去年|きょねん": "tahun lalu",
  "毎朝|まいあさ": "setiap pagi",
  "近|ちか": "dekat (近く・近い)",
  "公園|こうえん": "taman",
  "走|はし": "berlari (走る)",
  "始|はじ": "memulai (始める)",
  "五分|ごふん": "lima menit",
  "続|つづ": "berlanjut (続く)",
  "思|おも": "berpikir, merasa (思う)",
  "友達|ともだち": "teman",
  "速|はや": "cepat (速く・速い)",
  "歩|ある": "berjalan (歩く)",
  "言|い": "berkata (言う)",
  "楽|たの": "menyenangkan (楽しい)",
  "今|いま": "sekarang",
  "三十分|さんじゅっぷん": "tiga puluh menit",
  "疲|つか": "lelah (疲れる)",
  "体|からだ": "tubuh",
  "気持|きも": "perasaan (気持ち)",
  "元気|げんき": "sehat, semangat",
  "気|き": "perasaan, semangat (気がする = merasa)",
  "家|いえ": "rumah",
  "一緒|いっしょ": "bersama",
  "毎日|まいにち": "setiap hari",
  "正|ただ": "benar (正しい)",
  "市立図書館|しりつとしょかん": "perpustakaan kota",
  "図書館|としょかん": "perpustakaan",
  "来月|らいげつ": "bulan depan",
  "日|にち": "tanggal (〜日)",
  "三週間|さんしゅうかん": "tiga minggu",
  "工事|こうじ": "pekerjaan konstruksi",
  "休|やす": "libur, istirahat (休む)",
  "間|あいだ": "selama, di antara",
  "本|ほん": "buku",
  "借|か": "meminjam (借りる)",
  "返|かえ": "mengembalikan (返す)",
  "入口|いりぐち": "pintu masuk",
  "横|よこ": "samping",
  "返却|へんきゃく": "pengembalian (barang pinjaman)",
  "自動的|じどうてき": "otomatis",
  "利用者|りようしゃ": "pengguna",
  "中|なか": "dalam",
  "読|よ": "membaca (読む)",
  "前|まえ": "sebelum, depan",
  "料理教室|りょうりきょうしつ": "kelas memasak",
  "案内|あんない": "panduan, informasi",
  "和食|わしょく": "masakan Jepang",
  "毎週|まいしゅう": "setiap minggu",
  "月曜日|げつようび": "hari Senin",
  "夜|よる": "malam",
  "回|かい": "kali, pertemuan",
  "円|えん": "yen",
  "洋食|ようしょく": "masakan Barat",
  "水曜日|すいようび": "hari Rabu",
  "菓子|かし": "kue, manisan (お菓子)",
  "第|だい": "ke- (urutan)",
  "土曜日|どようび": "hari Sabtu",
  "申|もう": "mengajukan (申し込み)",
  "込|こ": "masuk, mendaftar (申し込み)",
  "週|しゅう": "minggu",
  "金曜日|きんようび": "hari Jumat",
  "材料費|ざいりょうひ": "biaya bahan",
  "料金|りょうきん": "tarif, biaya",
  "含|ふく": "termasuk, mencakup (含まれる)",
  "学生|がくせい": "pelajar, mahasiswa",
  "割|わり": "persepuluh (1割 = 10%)",
  "安|やす": "murah (安い)",
  "平日|へいじつ": "hari kerja",
  "習|なら": "belajar (習う)",
  "会社員|かいしゃいん": "karyawan perusahaan",
  "選|えら": "memilih (選ぶ)",
  "電子書籍|でんししょせき": "buku elektronik",
  "紙|かみ": "kertas",
  "最近|さいきん": "belakangan ini",
  "増|ふ": "bertambah (増える)",
  "何冊|なんさつ": "berapa buku",
  "持|も": "membawa, memiliki (持つ)",
  "重|おも": "berat (重い)",
  "旅行|りょこう": "bepergian, wisata",
  "使|つか": "menggunakan (使う)",
  "良|よ": "baik (良い)",
  "感|かん": "kesan, sensasi (感じ)",
  "好|す": "suka (好き)",
  "多|おお": "banyak (多い)",
  "画面|がめん": "layar",
  "長|なが": "panjang, lama (長い)",
  "見|み": "melihat (見る)",
  "目|め": "mata",
  "少|すく": "sedikit (少ない)",
  "場面|ばめん": "situasi, adegan",
  "分|わ": "dibagi (使い分ける)",
  "一番|いちばん": "paling",
  "理由|りゆう": "alasan",
  "何|なん": "apa (何ですか)",
  "値段|ねだん": "harga",
  "文章|ぶんしょう": "teks, tulisan",
  "書|か": "menulis (書く)",
  "筆者|ひっしゃ": "penulis",
  "考|かんが": "berpikir (考える)",
  "合|あ": "cocok (合う)",
  "初|はじ": "pertama (初めて)",
  "一人暮|ひとりぐ": "hidup sendiri (一人暮らし)",
  "大学|だいがく": "universitas",
  "入|はい": "masuk (入る)",
  "最初|さいしょ": "pertama, awal",
  "一週間|いっしゅうかん": "satu minggu",
  "自由|じゆう": "bebas",
  "大変|たいへん": "repot, berat",
  "料理|りょうり": "memasak, masakan",
  "掃除|そうじ": "bersih-bersih",
  "洗濯|せんたく": "mencuci pakaian",
  "全部|ぜんぶ": "semuanya",
  "自分|じぶん": "diri sendiri",
  "実家|じっか": "rumah orang tua",
  "母|はは": "ibu (milik sendiri)",
  "飯|はん": "nasi (ご飯)",
  "作|つく": "membuat (作る)",
  "当|あ": "kena, wajar (当たり前)",
  "苦労|くろう": "jerih payah",
  "先週|せんしゅう": "minggu lalu",
  "電話|でんわ": "telepon",
  "急|きゅう": "mendadak",
  "笑|わら": "tertawa (笑う)",
  "勉強|べんきょう": "belajar",
  "難|むずか": "sulit (難しい)",
  "家事|かじ": "pekerjaan rumah tangga",
  "会|あ": "bertemu (会う)",
  "お金|かね": "uang",
  "声|こえ": "suara",
  "面白|おもしろ": "menarik, lucu (面白い)",
  "礼|れい": "ucapan terima kasih, hormat",
  "帰|かえ": "pulang (帰る)",
  "忙|いそが": "sibuk (忙しい)",
  "睡眠|すいみん": "tidur",
  "健康|けんこう": "kesehatan",
  "短|みじか": "pendek (短い)",
  "病気|びょうき": "penyakit",
  "研究|けんきゅう": "penelitian",
  "以上|いじょう": "lebih dari, ke atas",
  "寝|ね": "tidur (寝る)",
  "風邪|かぜ": "flu, masuk angin",
  "引|ひ": "menarik (風邪を引く = terkena flu)",
  "割合|わりあい": "proporsi, persentase",
  "高|たか": "tinggi, mahal (高い)",
  "眠|ねむ": "mengantuk (眠い・眠る)",
  "一時間|いちじかん": "satu jam",
  "光|ひかり": "cahaya",
  "代|か": "menggantikan (代わり)",
  "軽|かる": "ringan (軽い)",
  "運動|うんどう": "olahraga",
  "温|あたた": "hangat (温かい)",
  "飲|の": "minum (飲む)",
  "物|もの": "benda, barang (飲み物 = minuman)",
  "音楽|おんがく": "musik",
  "聞|き": "mendengar (聞く)",
  "日本|にほん": "Jepang",
  "自動販売機|じどうはんばいき": "mesin penjual otomatis",
  "食|た": "makan (食べる)",
  "傘|かさ": "payung",
  "売|う": "menjual (売る)",
  "外国|がいこく": "luar negeri",
  "来|き": "datang (来た)",
  "遅|おそ": "larut, lambat (遅い)",
  "道|みち": "jalan",
  "明|あか": "terang (明るい)",
  "機械|きかい": "mesin",
  "安全|あんぜん": "aman",
  "金|かね": "uang",
  "驚|おどろ": "terkejut (驚く)",
  "一方|いっぽう": "di sisi lain",
  "電気|でんき": "listrik",
  "問題|もんだい": "masalah",
  "量|りょう": "jumlah, kuantitas",
  "減|へ": "berkurang, mengurangi (減らす)",
  "新|あたら": "baru (新しい)",
  "壊|こわ": "rusak (壊れる)",
  "後|あと": "setelah",
  "内容|ないよう": "isi",
  "対|たい": "terhadap",
  "対策|たいさく": "langkah penanggulangan",
  "原因|げんいん": "penyebab",
  "外国人|がいこくじん": "orang asing",
  "感想|かんそう": "kesan, pendapat",
  "歴史|れきし": "sejarah",
  "失敗|しっぱい": "kegagalan",
  "学|まな": "belajar (学ぶ)",
  "大|おお": "besar (大きい)",
  "仕事|しごと": "pekerjaan",
  "任|まか": "mempercayakan (任される)",
  "商品|しょうひん": "produk",
  "発表会|はっぴょうかい": "acara presentasi/peluncuran",
  "企画|きかく": "perencanaan acara/proyek",
  "同時|どうじ": "pada saat yang sama",
  "不安|ふあん": "cemas",
  "当日|とうじつ": "hari H",
  "起|お": "terjadi (起きる)",
  "準備|じゅんび": "persiapan",
  "動|うご": "bergerak, menyala (動く)",
  "頭|あたま": "kepala",
  "真|ま": "sungguh (真っ白 = putih bersih)",
  "白|しろ": "putih",
  "時|とき": "saat, ketika",
  "先輩|せんぱい": "senior",
  "貸|か": "meminjamkan (貸す)",
  "無事|ぶじ": "selamat, lancar",
  "終|お": "selesai (終わる)",
  "誰|だれ": "siapa",
  "大切|たいせつ": "penting, berharga",
  "次|つぎ": "berikutnya",
  "同|おな": "sama (同じ)",
  "大事|だいじ": "penting",
  "必|かなら": "pasti (必ず)",
  "予備|よび": "cadangan",
  "道具|どうぐ": "peralatan",
  "用意|ようい": "persiapan, menyiapkan",
  "経験|けいけん": "pengalaman",
  "少|すこ": "sedikit (少し)",
  "強|つよ": "kuat (強い)",
  "来|こ": "datang (来る)",
  "忘|わす": "lupa (忘れる)",
  "届|とど": "sampai (届く)",
  "言葉|ことば": "kata, ucapan",
  "意味|いみ": "arti",
  "恥|は": "malu (恥ずかしい)",
  "助|たす": "menolong (助ける)",
  "相談|そうだん": "berkonsultasi",
  "買|か": "membeli (買う)",
  "早|はや": "awal, cepat (早い)",
  "市民|しみん": "warga kota",
  "利用案内|りようあんない": "panduan penggunaan",
  "開館時間|かいかんじかん": "jam buka",
  "土曜|どよう": "Sabtu",
  "日曜|にちよう": "Minggu",
  "祝日|しゅくじつ": "hari libur nasional",
  "休館日|きゅうかんび": "hari tutup",
  "毎月|まいつき": "setiap bulan",
  "場合|ばあい": "kasus, jika",
  "大人|おとな": "orang dewasa",
  "中学生|ちゅうがくせい": "siswa SMP",
  "以下|いか": "di bawah, ke bawah",
  "65歳|ろくじゅうごさい": "65 tahun",
  "注意|ちゅうい": "perhatian, peringatan",
  "小学生|しょうがくせい": "siswa SD",
  "子供|こども": "anak",
  "泳|およ": "berenang (泳ぐ)",
  "帽子|ぼうし": "topi",
  "着|つ": "memakai (着ける)",
  "日曜日|にちようび": "hari Minggu",
  "行|い": "pergi (行く)",
  "何時|なんじ": "jam berapa",
  "歳|さい": "usia (〜歳)",
  "孫|まご": "cucu"
};
