// ===================================================================
// Qategori Nihongo - Kotoba (単語) JLPT N4
// Skema: {kat, kanji, kana, romaji, arti, contohJp, contohRomaji, contohId}
// ===================================================================
window.N4_KOTOBA = [

  // ---------------- KATA KERJA ----------------
  {kat:"Kata Kerja", kanji:"会う", kana:"あう", romaji:"au", arti:"bertemu", contohJp:"明日、友達に会います。", contohRomaji:"Ashita, tomodachi ni aimasu.", contohId:"Besok saya akan bertemu teman."},
  {kat:"Kata Kerja", kanji:"開ける", kana:"あける", romaji:"akeru", arti:"membuka", contohJp:"窓を開けてください。", contohRomaji:"Mado o akete kudasai.", contohId:"Tolong buka jendelanya."},
  {kat:"Kata Kerja", kanji:"遊ぶ", kana:"あそぶ", romaji:"asobu", arti:"bermain", contohJp:"子供が公園で遊んでいます。", contohRomaji:"Kodomo ga kouen de asonde imasu.", contohId:"Anak-anak sedang bermain di taman."},
  {kat:"Kata Kerja", kanji:"洗う", kana:"あらう", romaji:"arau", arti:"mencuci", contohJp:"食べる前に手を洗います。", contohRomaji:"Taberu mae ni te o araimasu.", contohId:"Saya mencuci tangan sebelum makan."},
  {kat:"Kata Kerja", kanji:"歩く", kana:"あるく", romaji:"aruku", arti:"berjalan kaki", contohJp:"駅まで歩いて10分です。", contohRomaji:"Eki made aruite juppun desu.", contohId:"Jalan kaki ke stasiun 10 menit."},
  {kat:"Kata Kerja", kanji:"言う", kana:"いう", romaji:"iu", arti:"mengatakan", contohJp:"彼は何も言いませんでした。", contohRomaji:"Kare wa nani mo iimasen deshita.", contohId:"Dia tidak mengatakan apa-apa."},
  {kat:"Kata Kerja", kanji:"要る", kana:"いる", romaji:"iru", arti:"perlu, butuh", contohJp:"パスポートが要ります。", contohRomaji:"Pasupooto ga irimasu.", contohId:"Perlu paspor."},
  {kat:"Kata Kerja", kanji:"歌う", kana:"うたう", romaji:"utau", arti:"bernyanyi", contohJp:"カラオケで歌を歌いました。", contohRomaji:"Karaoke de uta o utaimashita.", contohId:"Saya bernyanyi di karaoke."},
  {kat:"Kata Kerja", kanji:"生まれる", kana:"うまれる", romaji:"umareru", arti:"lahir", contohJp:"娘は去年生まれました。", contohRomaji:"Musume wa kyonen umaremashita.", contohId:"Anak perempuan saya lahir tahun lalu."},
  {kat:"Kata Kerja", kanji:"売る", kana:"うる", romaji:"uru", arti:"menjual", contohJp:"この店は野菜を売っています。", contohRomaji:"Kono mise wa yasai o utte imasu.", contohId:"Toko ini menjual sayuran."},
  {kat:"Kata Kerja", kanji:"起きる", kana:"おきる", romaji:"okiru", arti:"bangun", contohJp:"毎朝6時に起きます。", contohRomaji:"Maiasa rokuji ni okimasu.", contohId:"Setiap pagi saya bangun jam 6."},
  {kat:"Kata Kerja", kanji:"送る", kana:"おくる", romaji:"okuru", arti:"mengirim, mengantar", contohJp:"友達にメールを送りました。", contohRomaji:"Tomodachi ni meeru o okurimashita.", contohId:"Saya mengirim email ke teman."},
  {kat:"Kata Kerja", kanji:"怒る", kana:"おこる", romaji:"okoru", arti:"marah", contohJp:"先生が怒っています。", contohRomaji:"Sensei ga okotte imasu.", contohId:"Guru sedang marah."},
  {kat:"Kata Kerja", kanji:"教える", kana:"おしえる", romaji:"oshieru", arti:"mengajar, memberi tahu", contohJp:"道を教えてください。", contohRomaji:"Michi o oshiete kudasai.", contohId:"Tolong beri tahu jalannya."},
  {kat:"Kata Kerja", kanji:"落ちる", kana:"おちる", romaji:"ochiru", arti:"jatuh", contohJp:"本が棚から落ちました。", contohRomaji:"Hon ga tana kara ochimashita.", contohId:"Buku jatuh dari rak."},
  {kat:"Kata Kerja", kanji:"覚える", kana:"おぼえる", romaji:"oboeru", arti:"mengingat, menghafal", contohJp:"新しい単語を覚えます。", contohRomaji:"Atarashii tango o oboemasu.", contohId:"Saya menghafal kosakata baru."},
  {kat:"Kata Kerja", kanji:"思う", kana:"おもう", romaji:"omou", arti:"berpikir, merasa", contohJp:"明日は雨だと思います。", contohRomaji:"Ashita wa ame da to omoimasu.", contohId:"Saya pikir besok hujan."},
  {kat:"Kata Kerja", kanji:"泳ぐ", kana:"およぐ", romaji:"oyogu", arti:"berenang", contohJp:"夏はプールで泳ぎます。", contohRomaji:"Natsu wa puuru de oyogimasu.", contohId:"Musim panas saya berenang di kolam."},
  {kat:"Kata Kerja", kanji:"降りる", kana:"おりる", romaji:"oriru", arti:"turun", contohJp:"次の駅で降ります。", contohRomaji:"Tsugi no eki de orimasu.", contohId:"Saya turun di stasiun berikutnya."},
  {kat:"Kata Kerja", kanji:"変える", kana:"かえる", romaji:"kaeru", arti:"mengubah", contohJp:"予定を変えました。", contohRomaji:"Yotei o kaemashita.", contohId:"Saya mengubah jadwal."},
  {kat:"Kata Kerja", kanji:"かかる", kana:"かかる", romaji:"kakaru", arti:"memerlukan (waktu/biaya)", contohJp:"時間が30分かかります。", contohRomaji:"Jikan ga sanjuppun kakarimasu.", contohId:"Memerlukan waktu 30 menit."},
  {kat:"Kata Kerja", kanji:"かける", kana:"かける", romaji:"kakeru", arti:"menelepon, memakai (kacamata)", contohJp:"母に電話をかけます。", contohRomaji:"Haha ni denwa o kakemasu.", contohId:"Saya menelepon ibu."},
  {kat:"Kata Kerja", kanji:"貸す", kana:"かす", romaji:"kasu", arti:"meminjamkan", contohJp:"友達に本を貸しました。", contohRomaji:"Tomodachi ni hon o kashimashita.", contohId:"Saya meminjamkan buku ke teman."},
  {kat:"Kata Kerja", kanji:"借りる", kana:"かりる", romaji:"kariru", arti:"meminjam", contohJp:"図書館で本を借ります。", contohRomaji:"Toshokan de hon o karimasu.", contohId:"Saya meminjam buku di perpustakaan."},
  {kat:"Kata Kerja", kanji:"消える", kana:"きえる", romaji:"kieru", arti:"padam, hilang", contohJp:"電気が消えました。", contohRomaji:"Denki ga kiemashita.", contohId:"Lampu padam."},
  {kat:"Kata Kerja", kanji:"決める", kana:"きめる", romaji:"kimeru", arti:"memutuskan", contohJp:"旅行の日を決めました。", contohRomaji:"Ryokou no hi o kimemashita.", contohId:"Saya sudah memutuskan tanggal perjalanan."},
  {kat:"Kata Kerja", kanji:"答える", kana:"こたえる", romaji:"kotaeru", arti:"menjawab", contohJp:"質問に答えました。", contohRomaji:"Shitsumon ni kotaemashita.", contohId:"Saya menjawab pertanyaan."},
  {kat:"Kata Kerja", kanji:"困る", kana:"こまる", romaji:"komaru", arti:"kesulitan, bingung", contohJp:"お金がなくて困っています。", contohRomaji:"Okane ga nakute komatte imasu.", contohId:"Saya kesulitan karena tidak ada uang."},
  {kat:"Kata Kerja", kanji:"探す", kana:"さがす", romaji:"sagasu", arti:"mencari", contohJp:"鍵を探しています。", contohRomaji:"Kagi o sagashite imasu.", contohId:"Saya sedang mencari kunci."},
  {kat:"Kata Kerja", kanji:"下がる", kana:"さがる", romaji:"sagaru", arti:"turun (harga/suhu)", contohJp:"気温が下がりました。", contohRomaji:"Kion ga sagarimashita.", contohId:"Suhu udara turun."},
  {kat:"Kata Kerja", kanji:"咲く", kana:"さく", romaji:"saku", arti:"mekar", contohJp:"桜が咲きました。", contohRomaji:"Sakura ga sakimashita.", contohId:"Bunga sakura mekar."},
  {kat:"Kata Kerja", kanji:"死ぬ", kana:"しぬ", romaji:"shinu", arti:"mati", contohJp:"祖父が去年死にました。", contohRomaji:"Sofu ga kyonen shinimashita.", contohId:"Kakek saya meninggal tahun lalu."},
  {kat:"Kata Kerja", kanji:"知らせる", kana:"しらせる", romaji:"shiraseru", arti:"memberitahu", contohJp:"結果を知らせます。", contohRomaji:"Kekka o shirasemasu.", contohId:"Saya akan memberitahu hasilnya."},
  {kat:"Kata Kerja", kanji:"調べる", kana:"しらべる", romaji:"shiraberu", arti:"meneliti, memeriksa", contohJp:"インターネットで調べます。", contohRomaji:"Intaanetto de shirabemasu.", contohId:"Saya mencari tahu lewat internet."},
  {kat:"Kata Kerja", kanji:"捨てる", kana:"すてる", romaji:"suteru", arti:"membuang", contohJp:"ゴミを捨ててください。", contohRomaji:"Gomi o sutete kudasai.", contohId:"Tolong buang sampahnya."},
  {kat:"Kata Kerja", kanji:"倒れる", kana:"たおれる", romaji:"taoreru", arti:"jatuh, roboh", contohJp:"木が台風で倒れました。", contohRomaji:"Ki ga taifuu de taoremashita.", contohId:"Pohon roboh karena topan."},
  {kat:"Kata Kerja", kanji:"足りる", kana:"たりる", romaji:"tariru", arti:"cukup", contohJp:"時間が足りません。", contohRomaji:"Jikan ga tarimasen.", contohId:"Waktunya tidak cukup."},
  {kat:"Kata Kerja", kanji:"着く", kana:"つく", romaji:"tsuku", arti:"tiba, sampai", contohJp:"空港に着きました。", contohRomaji:"Kuukou ni tsukimashita.", contohId:"Saya sudah tiba di bandara."},
  {kat:"Kata Kerja", kanji:"連れる", kana:"つれる", romaji:"tsureru", arti:"membawa (orang)", contohJp:"子供を連れて出かけます。", contohRomaji:"Kodomo o tsurete dekakemasu.", contohId:"Saya keluar sambil membawa anak."},
  {kat:"Kata Kerja", kanji:"届ける", kana:"とどける", romaji:"todokeru", arti:"mengantarkan", contohJp:"荷物を届けます。", contohRomaji:"Nimotsu o todokemasu.", contohId:"Saya akan mengantarkan barang."},
  {kat:"Kata Kerja", kanji:"直す", kana:"なおす", romaji:"naosu", arti:"memperbaiki", contohJp:"自転車を直しました。", contohRomaji:"Jitensha o naoshimashita.", contohId:"Saya sudah memperbaiki sepeda."},
  {kat:"Kata Kerja", kanji:"鳴く", kana:"なく", romaji:"naku", arti:"berkicau, bersuara (hewan)", contohJp:"鳥が鳴いています。", contohRomaji:"Tori ga naite imasu.", contohId:"Burung sedang berkicau."},
  {kat:"Kata Kerja", kanji:"間に合う", kana:"まにあう", romaji:"maniau", arti:"tepat waktu, keburu", contohJp:"電車に間に合いました。", contohRomaji:"Densha ni maniaimashita.", contohId:"Saya keburu naik kereta."},

  // ---------------- KATA SIFAT -i ----------------
  {kat:"Kata Sifat -i", kanji:"甘い", kana:"あまい", romaji:"amai", arti:"manis", contohJp:"このケーキは甘いです。", contohRomaji:"Kono keeki wa amai desu.", contohId:"Kue ini manis."},
  {kat:"Kata Sifat -i", kanji:"危ない", kana:"あぶない", romaji:"abunai", arti:"berbahaya", contohJp:"ここは危ないですよ。", contohRomaji:"Koko wa abunai desu yo.", contohId:"Di sini berbahaya lho."},
  {kat:"Kata Sifat -i", kanji:"忙しい", kana:"いそがしい", romaji:"isogashii", arti:"sibuk", contohJp:"今週はとても忙しいです。", contohRomaji:"Konshuu wa totemo isogashii desu.", contohId:"Minggu ini sangat sibuk."},
  {kat:"Kata Sifat -i", kanji:"美味しい", kana:"おいしい", romaji:"oishii", arti:"enak", contohJp:"このラーメンは美味しいです。", contohRomaji:"Kono raamen wa oishii desu.", contohId:"Ramen ini enak."},
  {kat:"Kata Sifat -i", kanji:"かゆい", kana:"かゆい", romaji:"kayui", arti:"gatal", contohJp:"背中がかゆいです。", contohRomaji:"Senaka ga kayui desu.", contohId:"Punggung saya gatal."},
  {kat:"Kata Sifat -i", kanji:"厳しい", kana:"きびしい", romaji:"kibishii", arti:"ketat, keras", contohJp:"あの先生は厳しいです。", contohRomaji:"Ano sensei wa kibishii desu.", contohId:"Guru itu ketat."},
  {kat:"Kata Sifat -i", kanji:"危険", kana:"きけん", romaji:"kiken", arti:"berbahaya (nomina/sifat)", contohJp:"この道は危険です。", contohRomaji:"Kono michi wa kiken desu.", contohId:"Jalan ini berbahaya."},
  {kat:"Kata Sifat -i", kanji:"気持ちいい", kana:"きもちいい", romaji:"kimochi ii", arti:"terasa nyaman/enak", contohJp:"風が気持ちいいです。", contohRomaji:"Kaze ga kimochi ii desu.", contohId:"Anginnya terasa nyaman."},
  {kat:"Kata Sifat -i", kanji:"暗い", kana:"くらい", romaji:"kurai", arti:"gelap", contohJp:"部屋が暗いです。", contohRomaji:"Heya ga kurai desu.", contohId:"Kamarnya gelap."},
  {kat:"Kata Sifat -i", kanji:"苦しい", kana:"くるしい", romaji:"kurushii", arti:"sesak, menderita", contohJp:"胸が苦しいです。", contohRomaji:"Mune ga kurushii desu.", contohId:"Dada saya terasa sesak."},
  {kat:"Kata Sifat -i", kanji:"濃い", kana:"こい", romaji:"koi", arti:"pekat, kental", contohJp:"このコーヒーは濃いです。", contohRomaji:"Kono koohii wa koi desu.", contohId:"Kopi ini pekat."},
  {kat:"Kata Sifat -i", kanji:"寂しい", kana:"さびしい", romaji:"sabishii", arti:"kesepian", contohJp:"一人で寂しいです。", contohRomaji:"Hitori de sabishii desu.", contohId:"Kesepian sendirian."},
  {kat:"Kata Sifat -i", kanji:"すごい", kana:"すごい", romaji:"sugoi", arti:"hebat, luar biasa", contohJp:"彼の日本語はすごいです。", contohRomaji:"Kare no nihongo wa sugoi desu.", contohId:"Bahasa Jepangnya hebat."},
  {kat:"Kata Sifat -i", kanji:"涼しい", kana:"すずしい", romaji:"suzushii", arti:"sejuk", contohJp:"朝は涼しいです。", contohRomaji:"Asa wa suzushii desu.", contohId:"Pagi hari terasa sejuk."},
  {kat:"Kata Sifat -i", kanji:"狭い", kana:"せまい", romaji:"semai", arti:"sempit", contohJp:"この部屋は狭いです。", contohRomaji:"Kono heya wa semai desu.", contohId:"Kamar ini sempit."},
  {kat:"Kata Sifat -i", kanji:"痛い", kana:"いたい", romaji:"itai", arti:"sakit", contohJp:"頭が痛いです。", contohRomaji:"Atama ga itai desu.", contohId:"Kepala saya sakit."},
  {kat:"Kata Sifat -i", kanji:"眠い", kana:"ねむい", romaji:"nemui", arti:"mengantuk", contohJp:"授業中眠かったです。", contohRomaji:"Jugyouchuu nemukatta desu.", contohId:"Saya mengantuk saat pelajaran."},
  {kat:"Kata Sifat -i", kanji:"深い", kana:"ふかい", romaji:"fukai", arti:"dalam", contohJp:"この川は深いです。", contohRomaji:"Kono kawa wa fukai desu.", contohId:"Sungai ini dalam."},
  {kat:"Kata Sifat -i", kanji:"太い", kana:"ふとい", romaji:"futoi", arti:"gemuk, tebal (batang)", contohJp:"この木は太いです。", contohRomaji:"Kono ki wa futoi desu.", contohId:"Pohon ini besar/tebal."},
  {kat:"Kata Sifat -i", kanji:"珍しい", kana:"めずらしい", romaji:"mezurashii", arti:"langka, jarang", contohJp:"これは珍しい花です。", contohRomaji:"Kore wa mezurashii hana desu.", contohId:"Ini bunga yang langka."},

  // ---------------- KATA SIFAT -na ----------------
  {kat:"Kata Sifat -na", kanji:"上手", kana:"じょうず", romaji:"jouzu", arti:"pandai, mahir", contohJp:"彼はピアノが上手です。", contohRomaji:"Kare wa piano ga jouzu desu.", contohId:"Dia mahir bermain piano."},
  {kat:"Kata Sifat -na", kanji:"下手", kana:"へた", romaji:"heta", arti:"tidak mahir", contohJp:"私は料理が下手です。", contohRomaji:"Watashi wa ryouri ga heta desu.", contohId:"Saya tidak mahir memasak."},
  {kat:"Kata Sifat -na", kanji:"元気", kana:"げんき", romaji:"genki", arti:"sehat, bersemangat", contohJp:"祖母はとても元気です。", contohRomaji:"Sobo wa totemo genki desu.", contohId:"Nenek saya sangat sehat."},
  {kat:"Kata Sifat -na", kanji:"親切", kana:"しんせつ", romaji:"shinsetsu", arti:"baik hati, ramah", contohJp:"彼女はとても親切です。", contohRomaji:"Kanojo wa totemo shinsetsu desu.", contohId:"Dia sangat baik hati."},
  {kat:"Kata Sifat -na", kanji:"大切", kana:"たいせつ", romaji:"taisetsu", arti:"penting, berharga", contohJp:"家族が一番大切です。", contohRomaji:"Kazoku ga ichiban taisetsu desu.", contohId:"Keluarga adalah yang paling penting."},
  {kat:"Kata Sifat -na", kanji:"便利", kana:"べんり", romaji:"benri", arti:"praktis, berguna", contohJp:"このアプリは便利です。", contohRomaji:"Kono apuri wa benri desu.", contohId:"Aplikasi ini praktis."},
  {kat:"Kata Sifat -na", kanji:"不便", kana:"ふべん", romaji:"fuben", arti:"tidak praktis, merepotkan", contohJp:"ここは交通が不便です。", contohRomaji:"Koko wa koutsuu ga fuben desu.", contohId:"Di sini transportasinya merepotkan."},
  {kat:"Kata Sifat -na", kanji:"複雑", kana:"ふくざつ", romaji:"fukuzatsu", arti:"rumit", contohJp:"この問題は複雑です。", contohRomaji:"Kono mondai wa fukuzatsu desu.", contohId:"Masalah ini rumit."},
  {kat:"Kata Sifat -na", kanji:"簡単", kana:"かんたん", romaji:"kantan", arti:"mudah, sederhana", contohJp:"この料理は簡単です。", contohRomaji:"Kono ryouri wa kantan desu.", contohId:"Masakan ini mudah."},
  {kat:"Kata Sifat -na", kanji:"心配", kana:"しんぱい", romaji:"shinpai", arti:"khawatir", contohJp:"母の健康が心配です。", contohRomaji:"Haha no kenkou ga shinpai desu.", contohId:"Saya khawatir dengan kesehatan ibu."},
  {kat:"Kata Sifat -na", kanji:"熱心", kana:"ねっしん", romaji:"nesshin", arti:"tekun, bersemangat", contohJp:"彼は勉強に熱心です。", contohRomaji:"Kare wa benkyou ni nesshin desu.", contohId:"Dia tekun belajar."},
  {kat:"Kata Sifat -na", kanji:"自由", kana:"じゆう", romaji:"jiyuu", arti:"bebas", contohJp:"週末は自由な時間です。", contohRomaji:"Shuumatsu wa jiyuu na jikan desu.", contohId:"Akhir pekan adalah waktu bebas."},
  {kat:"Kata Sifat -na", kanji:"必要", kana:"ひつよう", romaji:"hitsuyou", arti:"perlu", contohJp:"パスポートが必要です。", contohRomaji:"Pasupooto ga hitsuyou desu.", contohId:"Paspor itu perlu."},
  {kat:"Kata Sifat -na", kanji:"色々", kana:"いろいろ", romaji:"iroiro", arti:"bermacam-macam", contohJp:"色々な国から来ました。", contohRomaji:"Iroiro na kuni kara kimashita.", contohId:"Berasal dari berbagai negara."},
  {kat:"Kata Sifat -na", kanji:"大変", kana:"たいへん", romaji:"taihen", arti:"berat, susah", contohJp:"引っ越しは大変でした。", contohRomaji:"Hikkoshi wa taihen deshita.", contohId:"Pindahan rumah itu berat."},

  // ---------------- KEHIDUPAN SEHARI-HARI ----------------
  {kat:"Kehidupan Sehari-hari", kanji:"財布", kana:"さいふ", romaji:"saifu", arti:"dompet", contohJp:"財布を忘れました。", contohRomaji:"Saifu o wasuremashita.", contohId:"Saya lupa membawa dompet."},
  {kat:"Kehidupan Sehari-hari", kanji:"傘", kana:"かさ", romaji:"kasa", arti:"payung", contohJp:"傘を持っていますか。", contohRomaji:"Kasa o motte imasu ka.", contohId:"Apa kamu membawa payung?"},
  {kat:"Kehidupan Sehari-hari", kanji:"鏡", kana:"かがみ", romaji:"kagami", arti:"cermin", contohJp:"鏡を見ながら化粧します。", contohRomaji:"Kagami o minagara keshou shimasu.", contohId:"Saya bersolek sambil melihat cermin."},
  {kat:"Kehidupan Sehari-hari", kanji:"石鹸", kana:"せっけん", romaji:"sekken", arti:"sabun", contohJp:"石鹸で手を洗います。", contohRomaji:"Sekken de te o araimasu.", contohId:"Saya cuci tangan dengan sabun."},
  {kat:"Kehidupan Sehari-hari", kanji:"布団", kana:"ふとん", romaji:"futon", arti:"kasur lipat/futon", contohJp:"布団をたたみます。", contohRomaji:"Futon o tatamimasu.", contohId:"Saya melipat futon."},
  {kat:"Kehidupan Sehari-hari", kanji:"毛布", kana:"もうふ", romaji:"moufu", arti:"selimut", contohJp:"寒いので毛布を使います。", contohRomaji:"Samui node moufu o tsukaimasu.", contohId:"Karena dingin, saya pakai selimut."},
  {kat:"Kehidupan Sehari-hari", kanji:"洗濯機", kana:"せんたくき", romaji:"sentakuki", arti:"mesin cuci", contohJp:"洗濯機で服を洗います。", contohRomaji:"Sentakuki de fuku o araimasu.", contohId:"Saya mencuci baju dengan mesin cuci."},
  {kat:"Kehidupan Sehari-hari", kanji:"冷蔵庫", kana:"れいぞうこ", romaji:"reizouko", arti:"kulkas", contohJp:"牛乳は冷蔵庫にあります。", contohRomaji:"Gyuunyuu wa reizouko ni arimasu.", contohId:"Susu ada di kulkas."},
  {kat:"Kehidupan Sehari-hari", kanji:"電気", kana:"でんき", romaji:"denki", arti:"listrik, lampu", contohJp:"電気を消してください。", contohRomaji:"Denki o keshite kudasai.", contohId:"Tolong matikan lampunya."},
  {kat:"Kehidupan Sehari-hari", kanji:"掃除", kana:"そうじ", romaji:"souji", arti:"bersih-bersih", contohJp:"毎週日曜日に掃除します。", contohRomaji:"Maishuu nichiyoubi ni souji shimasu.", contohId:"Setiap Minggu saya bersih-bersih."},
  {kat:"Kehidupan Sehari-hari", kanji:"洗濯", kana:"せんたく", romaji:"sentaku", arti:"cuci baju", contohJp:"今日は洗濯をしました。", contohRomaji:"Kyou wa sentaku o shimashita.", contohId:"Hari ini saya mencuci baju."},
  {kat:"Kehidupan Sehari-hari", kanji:"予定", kana:"よてい", romaji:"yotei", arti:"jadwal, rencana", contohJp:"来週の予定を確認します。", contohRomaji:"Raishuu no yotei o kakunin shimasu.", contohId:"Saya cek jadwal minggu depan."},
  {kat:"Kehidupan Sehari-hari", kanji:"約束", kana:"やくそく", romaji:"yakusoku", arti:"janji", contohJp:"友達と約束があります。", contohRomaji:"Tomodachi to yakusoku ga arimasu.", contohId:"Saya ada janji dengan teman."},
  {kat:"Kehidupan Sehari-hari", kanji:"用事", kana:"ようじ", romaji:"youji", arti:"urusan, keperluan", contohJp:"今日は用事があります。", contohRomaji:"Kyou wa youji ga arimasu.", contohId:"Hari ini saya ada urusan."},
  {kat:"Kehidupan Sehari-hari", kanji:"趣味", kana:"しゅみ", romaji:"shumi", arti:"hobi", contohJp:"私の趣味は読書です。", contohRomaji:"Watashi no shumi wa dokusho desu.", contohId:"Hobi saya membaca buku."},
  {kat:"Kehidupan Sehari-hari", kanji:"習慣", kana:"しゅうかん", romaji:"shuukan", arti:"kebiasaan", contohJp:"早起きは私の習慣です。", contohRomaji:"Hayaoki wa watashi no shuukan desu.", contohId:"Bangun pagi adalah kebiasaan saya."},
  {kat:"Kehidupan Sehari-hari", kanji:"経験", kana:"けいけん", romaji:"keiken", arti:"pengalaman", contohJp:"日本で働いた経験があります。", contohRomaji:"Nihon de hataraita keiken ga arimasu.", contohId:"Saya punya pengalaman bekerja di Jepang."},
  {kat:"Kehidupan Sehari-hari", kanji:"性格", kana:"せいかく", romaji:"seikaku", arti:"sifat, karakter", contohJp:"彼女は明るい性格です。", contohRomaji:"Kanojo wa akarui seikaku desu.", contohId:"Dia berkarakter ceria."},

  // ---------------- KELUARGA & ORANG ----------------
  {kat:"Keluarga & Orang", kanji:"両親", kana:"りょうしん", romaji:"ryoushin", arti:"orang tua", contohJp:"両親は田舎に住んでいます。", contohRomaji:"Ryoushin wa inaka ni sunde imasu.", contohId:"Orang tua saya tinggal di kampung."},
  {kat:"Keluarga & Orang", kanji:"兄弟", kana:"きょうだい", romaji:"kyoudai", arti:"saudara kandung", contohJp:"兄弟は3人います。", contohRomaji:"Kyoudai wa sannin imasu.", contohId:"Saudara saya ada 3 orang."},
  {kat:"Keluarga & Orang", kanji:"祖父", kana:"そふ", romaji:"sofu", arti:"kakek", contohJp:"祖父は80歳です。", contohRomaji:"Sofu wa hachijussai desu.", contohId:"Kakek saya berusia 80 tahun."},
  {kat:"Keluarga & Orang", kanji:"祖母", kana:"そぼ", romaji:"sobo", arti:"nenek", contohJp:"祖母の料理が好きです。", contohRomaji:"Sobo no ryouri ga suki desu.", contohId:"Saya suka masakan nenek."},
  {kat:"Keluarga & Orang", kanji:"夫", kana:"おっと", romaji:"otto", arti:"suami", contohJp:"夫は会社員です。", contohRomaji:"Otto wa kaishain desu.", contohId:"Suami saya karyawan kantoran."},
  {kat:"Keluarga & Orang", kanji:"妻", kana:"つま", romaji:"tsuma", arti:"istri", contohJp:"妻は看護師です。", contohRomaji:"Tsuma wa kangoshi desu.", contohId:"Istri saya perawat."},
  {kat:"Keluarga & Orang", kanji:"娘", kana:"むすめ", romaji:"musume", arti:"anak perempuan", contohJp:"娘は5歳です。", contohRomaji:"Musume wa gosai desu.", contohId:"Anak perempuan saya berusia 5 tahun."},
  {kat:"Keluarga & Orang", kanji:"息子", kana:"むすこ", romaji:"musuko", arti:"anak laki-laki", contohJp:"息子は大学生です。", contohRomaji:"Musuko wa daigakusei desu.", contohId:"Anak laki-laki saya mahasiswa."},
  {kat:"Keluarga & Orang", kanji:"お互い", kana:"おたがい", romaji:"otagai", arti:"satu sama lain", contohJp:"お互いに助け合います。", contohRomaji:"Otagai ni tasukeaimasu.", contohId:"Kami saling membantu satu sama lain."},
  {kat:"Keluarga & Orang", kanji:"社会人", kana:"しゃかいじん", romaji:"shakaijin", arti:"orang yang sudah bekerja", contohJp:"兄はもう社会人です。", contohRomaji:"Ani wa mou shakaijin desu.", contohId:"Kakak laki-laki saya sudah bekerja."},

  // ---------------- WAKTU & TANGGAL ----------------
  {kat:"Waktu & Tanggal", kanji:"最近", kana:"さいきん", romaji:"saikin", arti:"akhir-akhir ini", contohJp:"最近忙しいです。", contohRomaji:"Saikin isogashii desu.", contohId:"Akhir-akhir ini sibuk."},
  {kat:"Waktu & Tanggal", kanji:"将来", kana:"しょうらい", romaji:"shourai", arti:"masa depan", contohJp:"将来医者になりたいです。", contohRomaji:"Shourai isha ni naritai desu.", contohId:"Ingin menjadi dokter di masa depan."},
  {kat:"Waktu & Tanggal", kanji:"以前", kana:"いぜん", romaji:"izen", arti:"sebelumnya, dulu", contohJp:"以前ここに住んでいました。", contohRomaji:"Izen koko ni sunde imashita.", contohId:"Dulu saya tinggal di sini."},
  {kat:"Waktu & Tanggal", kanji:"今度", kana:"こんど", romaji:"kondo", arti:"lain kali, kali ini", contohJp:"今度一緒に行きましょう。", contohRomaji:"Kondo issho ni ikimashou.", contohId:"Lain kali ayo pergi bersama."},
  {kat:"Waktu & Tanggal", kanji:"毎回", kana:"まいかい", romaji:"maikai", arti:"setiap kali", contohJp:"毎回遅刻します。", contohRomaji:"Maikai chikoku shimasu.", contohId:"Setiap kali terlambat."},
  {kat:"Waktu & Tanggal", kanji:"久しぶり", kana:"ひさしぶり", romaji:"hisashiburi", arti:"lama tidak bertemu/tidak lakukan", contohJp:"久しぶりですね。", contohRomaji:"Hisashiburi desu ne.", contohId:"Sudah lama tidak bertemu ya."},
  {kat:"Waktu & Tanggal", kanji:"来月", kana:"らいげつ", romaji:"raigetsu", arti:"bulan depan", contohJp:"来月日本へ行きます。", contohRomaji:"Raigetsu Nihon e ikimasu.", contohId:"Bulan depan saya pergi ke Jepang."},
  {kat:"Waktu & Tanggal", kanji:"先月", kana:"せんげつ", romaji:"sengetsu", arti:"bulan lalu", contohJp:"先月結婚しました。", contohRomaji:"Sengetsu kekkon shimashita.", contohId:"Bulan lalu saya menikah."},
  {kat:"Waktu & Tanggal", kanji:"今後", kana:"こんご", romaji:"kongo", arti:"mulai sekarang, ke depannya", contohJp:"今後気をつけます。", contohRomaji:"Kongo ki o tsukemasu.", contohId:"Mulai sekarang saya akan hati-hati."},

  // ---------------- KATA KETERANGAN ----------------
  {kat:"Kata Keterangan", kanji:"だんだん", kana:"だんだん", romaji:"dandan", arti:"lambat laun, semakin", contohJp:"だんだん寒くなります。", contohRomaji:"Dandan samuku narimasu.", contohId:"Semakin lama semakin dingin."},
  {kat:"Kata Keterangan", kanji:"ずっと", kana:"ずっと", romaji:"zutto", arti:"terus-menerus, jauh (lebih)", contohJp:"ずっと待っていました。", contohRomaji:"Zutto matte imashita.", contohId:"Saya terus menunggu."},
  {kat:"Kata Keterangan", kanji:"できるだけ", kana:"できるだけ", romaji:"dekirudake", arti:"sebisa mungkin", contohJp:"できるだけ早く来てください。", contohRomaji:"Dekirudake hayaku kite kudasai.", contohId:"Tolong datang secepat mungkin."},
  {kat:"Kata Keterangan", kanji:"やっと", kana:"やっと", romaji:"yatto", arti:"akhirnya", contohJp:"やっと終わりました。", contohRomaji:"Yatto owarimashita.", contohId:"Akhirnya selesai."},
  {kat:"Kata Keterangan", kanji:"急に", kana:"きゅうに", romaji:"kyuu ni", arti:"tiba-tiba", contohJp:"急に雨が降りました。", contohRomaji:"Kyuu ni ame ga furimashita.", contohId:"Tiba-tiba turun hujan."},
  {kat:"Kata Keterangan", kanji:"確か", kana:"たしか", romaji:"tashika", arti:"kalau tidak salah, pasti", contohJp:"確か明日休みです。", contohRomaji:"Tashika ashita yasumi desu.", contohId:"Kalau tidak salah besok libur."},
  {kat:"Kata Keterangan", kanji:"そろそろ", kana:"そろそろ", romaji:"sorosoro", arti:"sebentar lagi, sudah saatnya", contohJp:"そろそろ帰りましょう。", contohRomaji:"Sorosoro kaerimashou.", contohId:"Sebentar lagi ayo pulang."},
  {kat:"Kata Keterangan", kanji:"やはり", kana:"やはり", romaji:"yahari", arti:"memang benar, seperti dugaan", contohJp:"やはり雨でした。", contohRomaji:"Yahari ame deshita.", contohId:"Ternyata memang hujan."},
  {kat:"Kata Keterangan", kanji:"なかなか", kana:"なかなか", romaji:"nakanaka", arti:"cukup, susah (dengan negatif)", contohJp:"バスがなかなか来ません。", contohRomaji:"Basu ga nakanaka kimasen.", contohId:"Bus tidak kunjung datang."},

  // ---------------- TEMPAT & ARAH ----------------
  {kat:"Tempat & Arah", kanji:"近く", kana:"ちかく", romaji:"chikaku", arti:"dekat, sekitar", contohJp:"駅の近くに住んでいます。", contohRomaji:"Eki no chikaku ni sunde imasu.", contohId:"Saya tinggal dekat stasiun."},
  {kat:"Tempat & Arah", kanji:"向こう", kana:"むこう", romaji:"mukou", arti:"seberang, sana", contohJp:"郵便局は道の向こうです。", contohRomaji:"Yuubinkyoku wa michi no mukou desu.", contohId:"Kantor pos ada di seberang jalan."},
  {kat:"Tempat & Arah", kanji:"周り", kana:"まわり", romaji:"mawari", arti:"sekitar, sekeliling", contohJp:"家の周りは静かです。", contohRomaji:"Ie no mawari wa shizuka desu.", contohId:"Sekitar rumah tenang."},
  {kat:"Tempat & Arah", kanji:"田舎", kana:"いなか", romaji:"inaka", arti:"desa, kampung halaman", contohJp:"田舎でゆっくり過ごしました。", contohRomaji:"Inaka de yukkuri sugoshimashita.", contohId:"Saya bersantai di kampung."},
  {kat:"Tempat & Arah", kanji:"都会", kana:"とかい", romaji:"tokai", arti:"kota besar", contohJp:"都会の生活は忙しいです。", contohRomaji:"Tokai no seikatsu wa isogashii desu.", contohId:"Kehidupan di kota besar sibuk."},
  {kat:"Tempat & Arah", kanji:"交差点", kana:"こうさてん", romaji:"kousaten", arti:"persimpangan", contohJp:"次の交差点を右に曲がってください。", contohRomaji:"Tsugi no kousaten o migi ni magatte kudasai.", contohId:"Tolong belok kanan di persimpangan berikutnya."},
  {kat:"Tempat & Arah", kanji:"信号", kana:"しんごう", romaji:"shingou", arti:"lampu lalu lintas", contohJp:"信号が赤です。", contohRomaji:"Shingou ga aka desu.", contohId:"Lampu lalu lintas merah."},

  // ---------------- MAKANAN & BELANJA ----------------
  {kat:"Makanan & Belanja", kanji:"味", kana:"あじ", romaji:"aji", arti:"rasa", contohJp:"この料理は味が濃いです。", contohRomaji:"Kono ryouri wa aji ga koi desu.", contohId:"Masakan ini rasanya kuat."},
  {kat:"Makanan & Belanja", kanji:"値段", kana:"ねだん", romaji:"nedan", arti:"harga", contohJp:"この靴の値段は高いです。", contohRomaji:"Kono kutsu no nedan wa takai desu.", contohId:"Harga sepatu ini mahal."},
  {kat:"Makanan & Belanja", kanji:"レジ", kana:"レジ", romaji:"reji", arti:"kasir", contohJp:"レジで払ってください。", contohRomaji:"Reji de haratte kudasai.", contohId:"Tolong bayar di kasir."},
  {kat:"Makanan & Belanja", kanji:"お釣り", kana:"おつり", romaji:"otsuri", arti:"uang kembalian", contohJp:"お釣りをもらいました。", contohRomaji:"Otsuri o moraimashita.", contohId:"Saya menerima uang kembalian."},
  {kat:"Makanan & Belanja", kanji:"割引", kana:"わりびき", romaji:"waribiki", arti:"diskon", contohJp:"今日は10%割引です。", contohRomaji:"Kyou wa juppaasento waribiki desu.", contohId:"Hari ini diskon 10%."},
  {kat:"Makanan & Belanja", kanji:"味噌", kana:"みそ", romaji:"miso", arti:"pasta kedelai (miso)", contohJp:"味噌汁を作りました。", contohRomaji:"Misoshiru o tsukurimashita.", contohId:"Saya membuat sup miso."},
  {kat:"Makanan & Belanja", kanji:"新鮮", kana:"しんせん", romaji:"shinsen", arti:"segar", contohJp:"この魚は新鮮です。", contohRomaji:"Kono sakana wa shinsen desu.", contohId:"Ikan ini segar."},

  // ---------------- KATA SERAPAN & LAINNYA ----------------
  {kat:"Kata Serapan & Lainnya", kanji:"アルバイト", kana:"アルバイト", romaji:"arubaito", arti:"kerja paruh waktu", contohJp:"コンビニでアルバイトをしています。", contohRomaji:"Konbini de arubaito o shite imasu.", contohId:"Saya kerja paruh waktu di minimarket."},
  {kat:"Kata Serapan & Lainnya", kanji:"アパート", kana:"アパート", romaji:"apaato", arti:"apartemen", contohJp:"駅の近くのアパートに住んでいます。", contohRomaji:"Eki no chikaku no apaato ni sunde imasu.", contohId:"Saya tinggal di apartemen dekat stasiun."},
  {kat:"Kata Serapan & Lainnya", kanji:"エレベーター", kana:"エレベーター", romaji:"erebeetaa", arti:"lift", contohJp:"エレベーターで5階に行きます。", contohRomaji:"Erebeetaa de gokai ni ikimasu.", contohId:"Saya naik lift ke lantai 5."},
  {kat:"Kata Serapan & Lainnya", kanji:"カーテン", kana:"カーテン", romaji:"kaaten", arti:"tirai", contohJp:"カーテンを閉めてください。", contohRomaji:"Kaaten o shimete kudasai.", contohId:"Tolong tutup tirainya."},
  {kat:"Kata Serapan & Lainnya", kanji:"スーツケース", kana:"スーツケース", romaji:"suutsukeesu", arti:"koper", contohJp:"スーツケースに荷物を入れます。", contohRomaji:"Suutsukeesu ni nimotsu o iremasu.", contohId:"Saya memasukkan barang ke koper."},
  {kat:"Kata Serapan & Lainnya", kanji:"パスポート", kana:"パスポート", romaji:"pasupooto", arti:"paspor", contohJp:"パスポートを見せてください。", contohRomaji:"Pasupooto o misete kudasai.", contohId:"Tolong tunjukkan paspornya."},
  {kat:"Kata Serapan & Lainnya", kanji:"サービス", kana:"サービス", romaji:"saabisu", arti:"layanan", contohJp:"このホテルはサービスがいいです。", contohRomaji:"Kono hoteru wa saabisu ga ii desu.", contohId:"Layanan hotel ini bagus."},
  {kat:"Kata Serapan & Lainnya", kanji:"インタビュー", kana:"インタビュー", romaji:"intabyuu", arti:"wawancara", contohJp:"有名人にインタビューしました。", contohRomaji:"Yuumeijin ni intabyuu shimashita.", contohId:"Saya mewawancarai orang terkenal."}
];
