// ===================================================================
// Qategori Nihongo - Reading (読解) JLPT N4
// Furigana: {漢字|かんじ} (kata dalam kurung kurawal, bacaan setelah |)
// tipe: tanbun (bacaan pendek), chuubun (menengah), jouhou (pencarian informasi)
// ===================================================================
window.N4_READING = [

{id:"n4r01", tipe:"tanbun", topik:"Surel undangan",
 judul:"{誕生日|たんじょうび}パーティーのお{知|し}らせ",
 teks:"{田中|たなか}さんへ\nお{元気|げんき}ですか。{来週|らいしゅう}の{土曜日|どようび}に、{私|わたし}の{家|いえ}で{誕生日|たんじょうび}パーティーをします。{時間|じかん}は{午後|ごご}6{時|じ}からです。{駅|えき}から{歩|ある}いて10{分|ぷん}ぐらいです。{食|た}べ{物|もの}は{私|わたし}が{用意|ようい}しますから、{飲|の}み{物|もの}を{持|も}ってきてください。{来|こ}られるかどうか、{木曜日|もくようび}までに{教|おし}えてください。\n{鈴木|すずき}",
 terjemahan:"Kepada Tanaka.\nApa kabar? Sabtu depan saya akan mengadakan pesta ulang tahun di rumah saya. Waktunya mulai jam 6 sore. Dari stasiun jalan kaki sekitar 10 menit. Makanan saya yang siapkan, jadi tolong bawa minuman. Beri tahu saya sampai hari Kamis apakah kamu bisa datang atau tidak.\nSuzuki",
 soal:[
  {q:"{鈴木|すずき}さんは{何|なに}をしますか。", opt:["{旅行|りょこう}に{行|い}く","{家|いえ}でパーティーをする","{駅|えき}で{友|とも}だちに{会|あ}う","{食|た}べ{物|もの}を{買|か}いに{行|い}く"], correct:1, exp:"Teks menyebut 私の家で誕生日パーティーをします (Suzuki mengadakan pesta di rumahnya)."},
  {q:"{田中|たなか}さんは{何|なに}を{持|も}っていきますか。", opt:["{食|た}べ{物|もの}","{飲|の}み{物|もの}","プレゼントと{花|はな}","{何|なに}も{持|も}っていかない"], correct:1, exp:"食べ物は私が用意しますから、飲み物を持ってきてください → bawa minuman."},
  {q:"{田中|たなか}さんは、いつまでに{返事|へんじ}をしますか。", opt:["{来週|らいしゅう}の{土曜日|どようび}","{今日|きょう}","{木曜日|もくようび}","{午後|ごご}6{時|じ}"], correct:2, exp:"来られるかどうか、木曜日までに教えてください → balas sampai hari Kamis."}
 ]},

{id:"n4r02", tipe:"tanbun", topik:"Pengumuman",
 judul:"{図書館|としょかん}のご{案内|あんない}",
 teks:"{図書館|としょかん}は{月曜日|げつようび}から{金曜日|きんようび}まで{午前|ごぜん}9{時|じ}から{午後|ごご}7{時|じ}まで{開|あ}いています。{土曜日|どようび}は{午後|ごご}5{時|じ}に{閉|し}まります。{日曜日|にちようび}と{祝日|しゅくじつ}は{休|やす}みです。{本|ほん}は一{人|にん}5{冊|さつ}まで、2{週間|しゅうかん}{借|か}りることができます。{返|かえ}す{日|ひ}を{過|す}ぎた{場合|ばあい}は、{次|つぎ}の{本|ほん}を{借|か}りられません。",
 terjemahan:"Perpustakaan buka dari Senin sampai Jumat, jam 9 pagi sampai jam 7 malam. Pada hari Sabtu tutup jam 5 sore. Hari Minggu dan hari libur nasional libur. Buku bisa dipinjam sampai 5 buku per orang selama 2 minggu. Jika melewati tanggal pengembalian, Anda tidak dapat meminjam buku berikutnya.",
 soal:[
  {q:"{土曜日|どようび}、{図書館|としょかん}は{何時|なんじ}に{閉|し}まりますか。", opt:["{午後|ごご}5{時|じ}","{午後|ごご}7{時|じ}","{午前|ごぜん}9{時|じ}","{閉|し}まらない"], correct:0, exp:"土曜日は午後5時に閉まります."},
  {q:"{本|ほん}についてどれが{正|ただ}しいですか。", opt:["{一度|いちど}に10{冊|さつ}{借|か}りられる","{一週間|いっしゅうかん}しか{借|か}りられない","{借|か}りられるのは2{週間|しゅうかん}、5{冊|さつ}まで","{日曜日|にちようび}にだけ{返|かえ}せる"], correct:2, exp:"一人5冊まで、2週間借りることができます."},
  {q:"{返|かえ}す{日|ひ}を{過|す}ぎたら、どうなりますか。", opt:["お{金|かね}を{払|はら}う","{次|つぎ}の{本|ほん}を{借|か}りられない","{図書館|としょかん}に{入|はい}れない","{本|ほん}をもらえる"], correct:1, exp:"返す日を過ぎた場合は、次の本を借りられません."}
 ]},

{id:"n4r03", tipe:"tanbun", topik:"Buku harian",
 judul:"{雨|あめ}の{日|ひ}",
 teks:"{今日|きょう}は{朝|あさ}から{雨|あめ}でした。{私|わたし}は{傘|かさ}を{家|いえ}に{忘|わす}れて、{駅|えき}に{着|つ}いてから{気|き}がつきました。{困|こま}っていると、{同|おな}じ{会社|かいしゃ}の{山田|やまだ}さんが{傘|かさ}に{入|い}れてくれました。{会社|かいしゃ}まで{二人|ふたり}で{歩|ある}きました。{帰|かえ}りは{雨|あめ}がやんでいたので、{山田|やまだ}さんに「ありがとう」と{言|い}って、{一人|ひとり}で{帰|かえ}りました。",
 terjemahan:"Hari ini hujan sejak pagi. Saya lupa payung di rumah dan baru sadar setelah sampai di stasiun. Saat sedang bingung, Yamada dari perusahaan yang sama mengajak saya berteduh di bawah payungnya. Kami berjalan berdua sampai kantor. Saat pulang hujan sudah berhenti, jadi saya mengucapkan \"terima kasih\" kepada Yamada dan pulang sendiri.",
 soal:[
  {q:"「{私|わたし}」はいつ{傘|かさ}を{忘|わす}れたことに{気|き}がつきましたか。", opt:["{家|いえ}を{出|で}る{前|まえ}","{駅|えき}に{着|つ}いてから","{会社|かいしゃ}に{着|つ}いてから","{帰|かえ}るとき"], correct:1, exp:"駅に着いてから気がつきました."},
  {q:"{会社|かいしゃ}まで、「{私|わたし}」はどうやって{行|い}きましたか。", opt:["タクシーで{行|い}った","{山田|やまだ}さんの{傘|かさ}に{入|はい}って{歩|ある}いた","{自分|じぶん}の{傘|かさ}で{歩|ある}いた","バスに{乗|の}った"], correct:1, exp:"山田さんが傘に入れてくれて、二人で歩きました."}
 ]},

{id:"n4r04", tipe:"tanbun", topik:"Memo",
 judul:"お{母|かあ}さんのメモ",
 teks:"{太郎|たろう}へ\nお{母|かあ}さんは{友|とも}だちと{買|か}い{物|もの}に{行|い}ってきます。{帰|かえ}りは{夕方|ゆうがた}6{時|じ}ごろです。{晩|ばん}ご{飯|はん}はカレーを{作|つく}って、{冷蔵庫|れいぞうこ}に{入|い}れてあります。{食|た}べる{前|まえ}に{温|あたた}めてください。{宿題|しゅくだい}は{先|さき}に{終|お}わらせてね。\n{母|はは}",
 terjemahan:"Untuk Taro.\nIbu pergi berbelanja dengan teman. Ibu pulang sekitar jam 6 sore. Untuk makan malam, ibu sudah membuat kari dan memasukkannya ke kulkas. Hangatkan dulu sebelum dimakan. PR selesaikan lebih dulu, ya.\nIbu",
 soal:[
  {q:"{太郎|たろう}は{晩|ばん}ご{飯|はん}の{前|まえ}に{何|なに}をしますか。", opt:["カレーを{作|つく}る","{買|か}い{物|もの}に{行|い}く","{宿題|しゅくだい}をして、カレーを{温|あたた}める","{友|とも}だちに{会|あ}う"], correct:2, exp:"Taro diminta menyelesaikan PR lebih dulu dan menghangatkan kari sebelum makan."},
  {q:"{晩|ばん}ご{飯|はん}のカレーはどこにありますか。", opt:["{台所|だいどころ}のテーブルの{上|うえ}","{冷蔵庫|れいぞうこ}の{中|なか}","{友|とも}だちの{家|いえ}","{店|みせ}"], correct:1, exp:"カレーを作って、冷蔵庫に入れてあります."}
 ]},

{id:"n4r05", tipe:"chuubun", topik:"Esai pribadi",
 judul:"{日本語|にほんご}の{勉強|べんきょう}",
 teks:"{私|わたし}は{二年|にねん}ぐらい{前|まえ}から{日本語|にほんご}を{勉強|べんきょう}しています。{始|はじ}めたきっかけは、{日本|にほん}のアニメが{好|す}きだったことです。{最初|さいしょ}は、ひらがなとカタカナを{覚|おぼ}えるのが{大変|たいへん}でした。{漢字|かんじ}はもっと{難|むずか}しくて、{何度|なんど}も{書|か}いても{忘|わす}れてしまいました。でも、{毎日|まいにち}{少|すこ}しずつ{続|つづ}けたので、{今|いま}は{簡単|かんたん}な{本|ほん}なら{読|よ}めるようになりました。{来年|らいねん}は{日本|にほん}に{留学|りゅうがく}して、もっと{上手|じょうず}になりたいです。",
 terjemahan:"Saya belajar bahasa Jepang sejak sekitar dua tahun lalu. Pemicunya adalah karena saya suka anime Jepang. Awalnya, menghafal hiragana dan katakana itu berat. Kanji lebih sulit lagi, ditulis berkali-kali pun tetap lupa. Tetapi karena saya melanjutkannya sedikit demi sedikit setiap hari, sekarang saya sudah bisa membaca buku yang mudah. Tahun depan saya ingin belajar ke Jepang agar bisa lebih mahir.",
 soal:[
  {q:"「{私|わたし}」が{日本語|にほんご}を{勉強|べんきょう}し{始|はじ}めたのはなぜですか。", opt:["{日本|にほん}に{住|す}んでいたから","{日本|にほん}のアニメが{好|す}きだったから","{会社|かいしゃ}の{仕事|しごと}で{必要|ひつよう}だったから","{友|とも}だちに{頼|たの}まれたから"], correct:1, exp:"始めたきっかけは、日本のアニメが好きだったこと."},
  {q:"{一番|いちばん}{難|むずか}しかったのは{何|なん}ですか。", opt:["ひらがな","カタカナ","{漢字|かんじ}","{会話|かいわ}"], correct:2, exp:"漢字はもっと難しくて... → kanji adalah yang tersulit."},
  {q:"{今|いま}の「{私|わたし}」について、{正|ただ}しいものはどれですか。", opt:["{簡単|かんたん}な{本|ほん}が{読|よ}める","{日本|にほん}に{住|す}んでいる","{漢字|かんじ}をすべて{覚|おぼ}えた","{勉強|べんきょう}をやめた"], correct:0, exp:"今は簡単な本なら読めるようになりました."}
 ]},

{id:"n4r06", tipe:"chuubun", topik:"Esai pribadi",
 judul:"{自転車|じてんしゃ}で{駅|えき}まで",
 teks:"{私|わたし}は{先月|せんげつ}、{駅|えき}から{少|すこ}し{遠|とお}いところに{引|ひ}っ{越|こ}しました。{家|いえ}から{駅|えき}までバスで15{分|ふん}かかります。でも、バスは{一時間|いちじかん}に{二本|にほん}しかないので、{不便|ふべん}です。そこで、{中古|ちゅうこ}の{自転車|じてんしゃ}を{買|か}いました。{自転車|じてんしゃ}なら{十分|じゅっぷん}で{駅|えき}に{着|つ}きます。{雨|あめ}の{日|ひ}は{大変|たいへん}ですが、{天気|てんき}がいい{日|ひ}は{気持|きも}ちがいいです。それに、{体|からだ}にもいいので、{続|つづ}けたいと{思|おも}っています。",
 terjemahan:"Bulan lalu saya pindah ke tempat yang agak jauh dari stasiun. Dari rumah ke stasiun naik bus 15 menit. Tetapi bus hanya ada dua kali per jam, jadi tidak praktis. Maka saya membeli sepeda bekas. Dengan sepeda, sampai ke stasiun dalam 10 menit. Saat hujan memang repot, tetapi saat cuaca bagus rasanya menyenangkan. Lagi pula baik untuk badan, jadi saya ingin melanjutkannya.",
 soal:[
  {q:"「{私|わたし}」はどうして{自転車|じてんしゃ}を{買|か}いましたか。", opt:["バスが{高|たか}かったから","バスが{少|すく}なくて{不便|ふべん}だったから","{自転車|じてんしゃ}が{好|す}きだったから","{駅|えき}が{家|いえ}の{隣|となり}だったから"], correct:1, exp:"バスは一時間に二本しかないので、不便です → itulah alasan membeli sepeda."},
  {q:"{自転車|じてんしゃ}で{駅|えき}まで{何分|なんぷん}かかりますか。", opt:["5{分|ふん}","10{分|ぷん}","15{分|ふん}","30{分|ぷん}"], correct:1, exp:"自転車なら十分で駅に着きます. (15 menit adalah waktu naik bus.)"},
  {q:"「{私|わたし}」は{自転車|じてんしゃ}についてどう{思|おも}っていますか。", opt:["{雨|あめ}の{日|ひ}も{楽|たの}しい","{体|からだ}にいいので{続|つづ}けたい","{高|たか}いのでもう{買|か}いたくない","バスのほうがいい"], correct:1, exp:"体にもいいので、続けたいと思っています."}
 ]},

{id:"n4r07", tipe:"chuubun", topik:"Pengalaman",
 judul:"{北海道|ほっかいどう}{旅行|りょこう}",
 teks:"{去年|きょねん}の{夏|なつ}、{家族|かぞく}と{北海道|ほっかいどう}へ{旅行|りょこう}に{行|い}きました。{飛行機|ひこうき}で{二時間|にじかん}ぐらいかかりました。{東京|とうきょう}はとても{暑|あつ}かったのに、{北海道|ほっかいどう}は{涼|すず}しくて、{快適|かいてき}でした。{私|わたし}たちは{広|ひろ}い{牧場|ぼくじょう}で{馬|うま}に{乗|の}ったり、{新鮮|しんせん}な{牛乳|ぎゅうにゅう}を{飲|の}んだりしました。{一番|いちばん}{美味|おい}しかったのは、{海|うみ}の{近|ちか}くで{食|た}べた{魚|さかな}です。また{行|い}きたいです。",
 terjemahan:"Musim panas tahun lalu, saya bepergian ke Hokkaido bersama keluarga. Naik pesawat sekitar dua jam. Padahal Tokyo sangat panas, tetapi Hokkaido sejuk dan nyaman. Kami menunggang kuda di peternakan yang luas dan minum susu segar. Yang paling enak adalah ikan yang kami makan di dekat laut. Saya ingin pergi lagi.",
 soal:[
  {q:"{北海道|ほっかいどう}はどうでしたか。", opt:["{東京|とうきょう}より{暑|あつ}かった","{東京|とうきょう}より{涼|すず}しかった","{雪|ゆき}が{降|ふ}っていた","{雨|あめ}だった"], correct:1, exp:"東京は暑かったのに、北海道は涼しくて、快適でした."},
  {q:"{牧場|ぼくじょう}で{何|なに}をしましたか。", opt:["{魚|さかな}を{釣|つ}った","{馬|うま}に{乗|の}って、{牛乳|ぎゅうにゅう}を{飲|の}んだ","{買|か}い{物|もの}をした","{泳|およ}いだ"], correct:1, exp:"広い牧場で馬に乗ったり、新鮮な牛乳を飲んだりしました."},
  {q:"{一番|いちばん}{美味|おい}しかったのは{何|なん}ですか。", opt:["{牛乳|ぎゅうにゅう}","{肉|にく}","{魚|さかな}","{野菜|やさい}"], correct:2, exp:"一番美味しかったのは、海の近くで食べた魚です."}
 ]},

{id:"n4r08", tipe:"chuubun", topik:"Pengalaman",
 judul:"カフェのアルバイト",
 teks:"{私|わたし}は{先月|せんげつ}から、{駅|えき}の{近|ちか}くのカフェでアルバイトをしています。{最初|さいしょ}の{一週間|いっしゅうかん}は、お{客様|きゃくさま}に{何|なん}と{言|い}えばいいかわからなくて、{緊張|きんちょう}しました。でも、{店|みせ}の{先輩|せんぱい}が{優|やさ}しく{教|おし}えてくれたので、{少|すこ}しずつ{慣|な}れてきました。{先週|せんしゅう}、お{客様|きゃくさま}から「ありがとう、{美味|おい}しかったよ」と{言|い}われて、とても{嬉|うれ}しかったです。これからも{頑張|がんば}りたいと{思|おも}います。",
 terjemahan:"Sejak bulan lalu saya bekerja paruh waktu di kafe dekat stasiun. Pada minggu pertama saya tegang karena tidak tahu harus berkata apa kepada pelanggan. Namun karena senior di toko mengajari dengan ramah, saya perlahan terbiasa. Minggu lalu, seorang pelanggan berkata \"Terima kasih, enak sekali,\" dan saya sangat senang. Saya ingin terus berusaha.",
 soal:[
  {q:"{最初|さいしょ}の{一週間|いっしゅうかん}、「{私|わたし}」はどうでしたか。", opt:["{仕事|しごと}が{楽|たの}しかった","{何|なん}と{言|い}えばいいかわからなくて{緊張|きんちょう}した","{忙|いそが}しくて{休|やす}んだ","{先輩|せんぱい}と{喧嘩|けんか}した"], correct:1, exp:"お客様に何と言えばいいかわからなくて、緊張しました."},
  {q:"「{私|わたし}」はなぜ{少|すこ}しずつ{慣|な}れましたか。", opt:["{毎日|まいにち}{働|はたら}いたから","{先輩|せんぱい}が{優|やさ}しく{教|おし}えてくれたから","{店|みせ}が{静|しず}かだったから","お{客様|きゃくさま}が{少|すく}なかったから"], correct:1, exp:"店の先輩が優しく教えてくれたので、少しずつ慣れてきました."}
 ]},

{id:"n4r09", tipe:"jouhou", topik:"Brosur",
 judul:"{料理教室|りょうりきょうしつ}のご{案内|あんない}",
 teks:"【{料理教室|りょうりきょうしつ}の{生徒|せいと}さんをぼしゅうしています】\n・{日本料理|にほんりょうり}コース：{毎週|まいしゅう}{水曜日|すいようび}　{午後|ごご}6{時|じ}〜8{時|じ}　{月|つき}4{回|かい}　{八千円|はっせんえん}\n・パンコース：{毎週|まいしゅう}{土曜日|どようび}　{午前|ごぜん}10{時|じ}〜12{時|じ}　{月|つき}3{回|かい}　{六千円|ろくせんえん}\n・{申|もう}し{込|こ}み：{電話|でんわ}かホームページで。{今月|こんげつ}25{日|にち}までに{申|もう}し{込|こ}んだ{人|ひと}は、{最初|さいしょ}の{月|つき}は10パーセント{安|やす}くなります。\n・{持|も}ち{物|もの}：エプロン、タオル",
 terjemahan:"[Menerima murid kelas memasak]\n・Kursus masakan Jepang: tiap Rabu, jam 6–8 malam, 4 kali per bulan, 8.000 yen\n・Kursus roti: tiap Sabtu, jam 10–12 pagi, 3 kali per bulan, 6.000 yen\n・Pendaftaran: lewat telepon atau situs web. Yang mendaftar sampai tanggal 25 bulan ini mendapat diskon 10 persen untuk bulan pertama.\n・Yang dibawa: celemek, handuk",
 soal:[
  {q:"{平日|へいじつ}の{夜|よる}に{習|なら}いたい{人|ひと}は、どのコースですか。", opt:["{日本料理|にほんりょうり}コース","パンコース","どちらでもいい","どちらもできない"], correct:0, exp:"Kursus masakan Jepang adalah hari Rabu malam (hari kerja). Kursus roti hari Sabtu pagi."},
  {q:"パンコースの{月|つき}の{料金|りょうきん}はいくらですか。", opt:["{八千円|はっせんえん}","{六千円|ろくせんえん}","{一万四千円|いちまんよんせんえん}","{五千四百円|ごせんよんひゃくえん}"], correct:1, exp:"パンコースは月3回で六千円 (diskon hanya berlaku bagi yang mendaftar sebelum tanggal 25 untuk bulan pertama)."},
  {q:"{今月|こんげつ}の25{日|にち}までに{申|もう}し{込|こ}むと、どうなりますか。", opt:["{最初|さいしょ}の{月|つき}が10パーセント{安|やす}くなる","{料理|りょうり}をもらえる","エプロンがもらえる","{毎月|まいつき}{安|やす}くなる"], correct:0, exp:"今月25日までに申し込んだ人は、最初の月は10パーセント安くなります."}
 ]},

{id:"n4r10", tipe:"jouhou", topik:"Pengumuman fasilitas",
 judul:"{市民|しみん}プールのご{利用|りよう}について",
 teks:"・{開|あ}いている{時間|じかん}：{午前|ごぜん}10{時|じ}〜{午後|ごご}8{時|じ}（{毎週|まいしゅう}{月曜日|げつようび}は{休|やす}み）\n・{料金|りょうきん}：{大人|おとな}　300{円|えん}　{子|こ}ども（{小学生|しょうがくせい}・{中学生|ちゅうがくせい}）　100{円|えん}\n・{小学生|しょうがくせい}より{小|ちい}さい{子|こ}どもは、{大人|おとな}といっしょに{入|はい}ってください。\n・{泳|およ}ぐときは、{帽子|ぼうし}をかぶってください。\n・{食事|しょくじ}は{外|そと}のレストランでお{願|ねが}いします。",
 terjemahan:"・Jam buka: jam 10 pagi–8 malam (tiap Senin libur)\n・Tarif: dewasa 300 yen, anak (SD dan SMP) 100 yen\n・Anak yang lebih kecil dari murid SD harap masuk bersama orang dewasa.\n・Saat berenang, mohon memakai topi renang.\n・Makan mohon dilakukan di restoran di luar.",
 soal:[
  {q:"プールが{休|やす}みなのはいつですか。", opt:["{毎週|まいしゅう}{月曜日|げつようび}","{毎週|まいしゅう}{日曜日|にちようび}","{毎日|まいにち}","{夜|よる}8{時|じ}から"], correct:0, exp:"毎週月曜日は休みです."},
  {q:"{中学生|ちゅうがくせい}一{人|ひとり}と{大人|おとな}一{人|ひとり}が{入|はい}ると、{全部|ぜんぶ}でいくらですか。", opt:["300{円|えん}","400{円|えん}","600{円|えん}","100{円|えん}"], correct:1, exp:"大人300円 + 子ども(中学生)100円 = 400円."},
  {q:"このプールで{守|まも}らなければならないことは{何|なん}ですか。", opt:["{泳|およ}ぐときに{帽子|ぼうし}をかぶる","プールの{中|なか}で{食事|しょくじ}をする","{一人|ひとり}で{小|ちい}さい{子|こ}どもを{入|い}れる","{月曜日|げつようび}に{来|く}る"], correct:0, exp:"泳ぐときは、帽子をかぶってください."}
 ]}

];

// Arti per kotoba untuk popup Reading. Kunci: kata|bacaan (sama dengan markup {kata|bacaan}).
window.N4_READING_GLOSS = {
  "一万四千円|いちまんよんせんえん": "14.000 yen",
  "一人|ひとり": "satu orang",
  "一度|いちど": "satu kali",
  "一時間|いちじかん": "satu jam",
  "一番|いちばん": "paling",
  "一週間|いっしゅうかん": "satu minggu",
  "上|うえ": "atas",
  "上手|じょうず": "pandai, mahir",
  "不便|ふべん": "tidak praktis, merepotkan",
  "中|なか": "dalam",
  "中古|ちゅうこ": "bekas (barang)",
  "中学生|ちゅうがくせい": "siswa SMP",
  "乗|の": "naik (乗る)",
  "二人|ふたり": "dua orang",
  "二年|にねん": "dua tahun",
  "二時間|にじかん": "dua jam",
  "二本|にほん": "dua batang/kali (penghitung)",
  "五千四百円|ごせんよんひゃくえん": "5.400 yen",
  "人|にん": "orang (penghitung: 一人)",
  "人|ひと": "orang",
  "人|ひとり": "satu orang (一人)",
  "今|いま": "sekarang",
  "今日|きょう": "hari ini",
  "今月|こんげつ": "bulan ini",
  "仕事|しごと": "pekerjaan",
  "休|やす": "libur, istirahat (休む)",
  "会|あ": "bertemu (会う)",
  "会社|かいしゃ": "perusahaan",
  "会話|かいわ": "percakapan",
  "住|す": "tinggal (住む)",
  "体|からだ": "tubuh",
  "何|なに": "apa",
  "何|なん": "apa (何ですか)",
  "何分|なんぷん": "berapa menit",
  "何度|なんど": "berapa kali",
  "何時|なんじ": "jam berapa",
  "作|つく": "membuat (作る)",
  "借|か": "meminjam (借りる)",
  "傘|かさ": "payung",
  "働|はたら": "bekerja (働く)",
  "優|やさ": "baik hati (優しい)",
  "元気|げんき": "sehat, semangat",
  "先|さき": "lebih dulu, di depan",
  "先月|せんげつ": "bulan lalu",
  "先輩|せんぱい": "senior",
  "先週|せんしゅう": "minggu lalu",
  "入|い": "memasukkan (入れる)",
  "入|はい": "masuk (入る)",
  "全部|ぜんぶ": "semuanya",
  "八千円|はっせんえん": "8.000 yen",
  "六千円|ろくせんえん": "6.000 yen",
  "円|えん": "yen",
  "冊|さつ": "penghitung buku",
  "冷蔵庫|れいぞうこ": "kulkas",
  "出|で": "keluar, hadir (出る)",
  "分|ふん": "menit (penghitung)",
  "分|ぷん": "menit (penghitung)",
  "利用|りよう": "penggunaan",
  "前|まえ": "sebelum, depan",
  "勉強|べんきょう": "belajar",
  "北海道|ほっかいどう": "Hokkaido",
  "十分|じゅっぷん": "sepuluh menit",
  "午前|ごぜん": "pagi (sebelum tengah hari)",
  "午後|ごご": "siang/sore (setelah tengah hari)",
  "去年|きょねん": "tahun lalu",
  "友|とも": "teman (友だち)",
  "台所|だいどころ": "dapur",
  "同|おな": "sama (同じ)",
  "喧嘩|けんか": "bertengkar",
  "回|かい": "kali, pertemuan",
  "困|こま": "kesulitan, bingung (困る)",
  "図書館|としょかん": "perpustakaan",
  "土曜日|どようび": "hari Sabtu",
  "場合|ばあい": "kasus, jika",
  "夏|なつ": "musim panas",
  "夕方|ゆうがた": "sore",
  "外|そと": "luar",
  "夜|よる": "malam",
  "大人|おとな": "orang dewasa",
  "大変|たいへん": "repot, berat",
  "天気|てんき": "cuaca",
  "太郎|たろう": "Taro (nama laki-laki)",
  "好|す": "suka (好き)",
  "始|はじ": "memulai (始める)",
  "嬉|うれ": "senang (嬉しい)",
  "子|こ": "anak (子ども)",
  "守|まも": "menaati, menjaga (守る)",
  "安|やす": "murah (安い)",
  "客様|きゃくさま": "tamu, pelanggan (お客様)",
  "家|いえ": "rumah",
  "家族|かぞく": "keluarga",
  "宿題|しゅくだい": "PR",
  "小|ちい": "kecil (小さい)",
  "小学生|しょうがくせい": "siswa SD",
  "少|すく": "sedikit (少ない)",
  "少|すこ": "sedikit (少し)",
  "山田|やまだ": "Yamada (nama keluarga)",
  "市民|しみん": "warga kota",
  "帰|かえ": "pulang (帰る)",
  "帽子|ぼうし": "topi",
  "平日|へいじつ": "hari kerja",
  "広|ひろ": "luas (広い)",
  "店|みせ": "toko",
  "引|ひ": "menarik; 引っ越す = pindah rumah",
  "必要|ひつよう": "perlu",
  "忘|わす": "lupa (忘れる)",
  "忙|いそが": "sibuk (忙しい)",
  "快適|かいてき": "nyaman",
  "思|おも": "berpikir, merasa (思う)",
  "慣|な": "terbiasa (慣れる)",
  "払|はら": "membayar (払う)",
  "持|も": "membawa, memiliki (持つ)",
  "教|おし": "mengajari, memberi tahu (教える)",
  "料理|りょうり": "memasak, masakan",
  "料理教室|りょうりきょうしつ": "kelas memasak",
  "料金|りょうきん": "tarif, biaya",
  "新鮮|しんせん": "segar",
  "旅行|りょこう": "bepergian, wisata",
  "日|にち": "tanggal (〜日)",
  "日|ひ": "hari, tanggal",
  "日曜日|にちようび": "hari Minggu",
  "日本|にほん": "Jepang",
  "日本料理|にほんりょうり": "masakan Jepang",
  "日本語|にほんご": "bahasa Jepang",
  "時|じ": "jam (pukul)",
  "時間|じかん": "waktu",
  "晩|ばん": "malam (晩ご飯: makan malam)",
  "暑|あつ": "panas (暑い)",
  "書|か": "menulis (書く)",
  "最初|さいしょ": "pertama, awal",
  "月|つき": "bulan",
  "月曜日|げつようび": "hari Senin",
  "朝|あさ": "pagi",
  "木曜日|もくようび": "hari Kamis",
  "本|ほん": "buku",
  "来|く": "datang (来る)",
  "来|こ": "datang (来る)",
  "来年|らいねん": "tahun depan",
  "来週|らいしゅう": "minggu depan",
  "東京|とうきょう": "Tokyo",
  "案内|あんない": "panduan, informasi",
  "楽|たの": "menyenangkan (楽しい)",
  "次|つぎ": "berikutnya",
  "正|ただ": "benar (正しい)",
  "歩|ある": "berjalan (歩く)",
  "母|かあ": "ibu (お母さん)",
  "母|はは": "ibu (milik sendiri)",
  "毎日|まいにち": "setiap hari",
  "毎月|まいつき": "setiap bulan",
  "毎週|まいしゅう": "setiap minggu",
  "気|き": "perasaan, semangat (気がする = merasa)",
  "気持|きも": "perasaan (気持ち)",
  "水曜日|すいようび": "hari Rabu",
  "泳|およ": "berenang (泳ぐ)",
  "海|うみ": "laut",
  "涼|すず": "sejuk (涼しい)",
  "温|あたた": "hangat (温かい)",
  "漢字|かんじ": "kanji",
  "牛乳|ぎゅうにゅう": "susu",
  "牧場|ぼくじょう": "peternakan",
  "物|もの": "benda, barang (飲み物 = minuman)",
  "生徒|せいと": "murid",
  "用意|ようい": "persiapan, menyiapkan",
  "田中|たなか": "Tanaka (nama keluarga)",
  "申|もう": "mengajukan (申し込み)",
  "留学|りゅうがく": "belajar ke luar negeri",
  "着|つ": "tiba (着く)",
  "知|し": "memberi tahu (知らせ・知らせる)",
  "祝日|しゅくじつ": "hari libur nasional",
  "私|わたし": "saya",
  "簡単|かんたん": "mudah, sederhana",
  "終|お": "selesai (終わる)",
  "続|つづ": "berlanjut (続く)",
  "緊張|きんちょう": "tegang, gugup",
  "美味|おい": "enak (美味しい)",
  "習|なら": "belajar (習う)",
  "肉|にく": "daging",
  "自分|じぶん": "diri sendiri",
  "自転車|じてんしゃ": "sepeda",
  "花|はな": "bunga",
  "行|い": "pergi (行く)",
  "覚|おぼ": "menghafal, mengingat (覚える)",
  "言|い": "berkata (言う)",
  "誕生日|たんじょうび": "ulang tahun",
  "読|よ": "membaca (読む)",
  "買|か": "membeli (買う)",
  "越|こ": "melewati; 引っ越す = pindah rumah",
  "込|こ": "masuk, mendaftar (申し込み)",
  "近|ちか": "dekat (近く・近い)",
  "返|かえ": "mengembalikan (返す)",
  "返事|へんじ": "balasan, jawaban",
  "週間|しゅうかん": "minggu (lamanya)",
  "過|す": "melewati (過ぎる)",
  "遠|とお": "jauh (遠い)",
  "野菜|やさい": "sayur",
  "金|かね": "uang",
  "金曜日|きんようび": "hari Jumat",
  "釣|つ": "memancing (釣る)",
  "鈴木|すずき": "Suzuki (nama keluarga)",
  "閉|し": "tertutup, tutup (閉まる)",
  "開|あ": "terbuka, buka (開く)",
  "降|ふ": "turun (hujan/salju) (降る)",
  "隣|となり": "sebelah, tetangga",
  "難|むずか": "sulit (難しい)",
  "雨|あめ": "hujan",
  "雪|ゆき": "salju",
  "電話|でんわ": "telepon",
  "静|しず": "tenang (静か)",
  "頑張|がんば": "berusaha sekuat tenaga (頑張る)",
  "頼|たの": "meminta, memesan (頼む/頼まれる)",
  "願|ねが": "memohon (お願いします)",
  "飛行機|ひこうき": "pesawat",
  "食|た": "makan (食べる)",
  "食事|しょくじ": "makan",
  "飯|はん": "nasi (ご飯)",
  "飲|の": "minum (飲む)",
  "馬|うま": "kuda",
  "駅|えき": "stasiun",
  "高|たか": "tinggi, mahal (高い)",
  "魚|さかな": "ikan"
};
