// ===================================================================
// Qategori Nihongo - Kotoba (単語) JLPT N5
// Skema: {kat, kanji, kana, romaji, arti, contohJp, contohRomaji, contohId}
// ===================================================================
window.N5_KOTOBA = [

  // ---------------- KATA KERJA ----------------
  {kat:"Kata Kerja", kanji:"行く", kana:"いく", romaji:"iku", arti:"pergi", contohJp:"学校に行きます。", contohRomaji:"Gakkou ni ikimasu.", contohId:"Saya pergi ke sekolah."},
  {kat:"Kata Kerja", kanji:"来る", kana:"くる", romaji:"kuru", arti:"datang", contohJp:"友達が来ます。", contohRomaji:"Tomodachi ga kimasu.", contohId:"Teman saya datang."},
  {kat:"Kata Kerja", kanji:"食べる", kana:"たべる", romaji:"taberu", arti:"makan", contohJp:"朝ご飯を食べます。", contohRomaji:"Asagohan o tabemasu.", contohId:"Saya makan sarapan."},
  {kat:"Kata Kerja", kanji:"飲む", kana:"のむ", romaji:"nomu", arti:"minum", contohJp:"水を飲みます。", contohRomaji:"Mizu o nomimasu.", contohId:"Saya minum air."},
  {kat:"Kata Kerja", kanji:"見る", kana:"みる", romaji:"miru", arti:"melihat", contohJp:"テレビを見ます。", contohRomaji:"Terebi o mimasu.", contohId:"Saya menonton TV."},
  {kat:"Kata Kerja", kanji:"聞く", kana:"きく", romaji:"kiku", arti:"mendengar, bertanya", contohJp:"音楽を聞きます。", contohRomaji:"Ongaku o kikimasu.", contohId:"Saya mendengarkan musik."},
  {kat:"Kata Kerja", kanji:"話す", kana:"はなす", romaji:"hanasu", arti:"berbicara", contohJp:"日本語を話します。", contohRomaji:"Nihongo o hanashimasu.", contohId:"Saya berbicara bahasa Jepang."},
  {kat:"Kata Kerja", kanji:"読む", kana:"よむ", romaji:"yomu", arti:"membaca", contohJp:"本を読みます。", contohRomaji:"Hon o yomimasu.", contohId:"Saya membaca buku."},
  {kat:"Kata Kerja", kanji:"書く", kana:"かく", romaji:"kaku", arti:"menulis", contohJp:"手紙を書きます。", contohRomaji:"Tegami o kakimasu.", contohId:"Saya menulis surat."},
  {kat:"Kata Kerja", kanji:"買う", kana:"かう", romaji:"kau", arti:"membeli", contohJp:"パンを買います。", contohRomaji:"Pan o kaimasu.", contohId:"Saya membeli roti."},
  {kat:"Kata Kerja", kanji:"する", kana:"する", romaji:"suru", arti:"melakukan", contohJp:"宿題をします。", contohRomaji:"Shukudai o shimasu.", contohId:"Saya mengerjakan PR."},
  {kat:"Kata Kerja", kanji:"ある", kana:"ある", romaji:"aru", arti:"ada (benda)", contohJp:"机の上に本があります。", contohRomaji:"Tsukue no ue ni hon ga arimasu.", contohId:"Ada buku di atas meja."},
  {kat:"Kata Kerja", kanji:"いる", kana:"いる", romaji:"iru", arti:"ada (makhluk hidup)", contohJp:"公園に猫がいます。", contohRomaji:"Kouen ni neko ga imasu.", contohId:"Ada kucing di taman."},
  {kat:"Kata Kerja", kanji:"寝る", kana:"ねる", romaji:"neru", arti:"tidur", contohJp:"11時に寝ます。", contohRomaji:"Juuichiji ni nemasu.", contohId:"Saya tidur jam 11."},
  {kat:"Kata Kerja", kanji:"起きる", kana:"おきる", romaji:"okiru", arti:"bangun", contohJp:"7時に起きます。", contohRomaji:"Shichiji ni okimasu.", contohId:"Saya bangun jam 7."},
  {kat:"Kata Kerja", kanji:"休む", kana:"やすむ", romaji:"yasumu", arti:"istirahat", contohJp:"ここで休みましょう。", contohRomaji:"Koko de yasumimashou.", contohId:"Ayo istirahat di sini."},
  {kat:"Kata Kerja", kanji:"働く", kana:"はたらく", romaji:"hataraku", arti:"bekerja", contohJp:"会社で働いています。", contohRomaji:"Kaisha de hataraite imasu.", contohId:"Saya bekerja di perusahaan."},
  {kat:"Kata Kerja", kanji:"勉強する", kana:"べんきょうする", romaji:"benkyou suru", arti:"belajar", contohJp:"毎日勉強します。", contohRomaji:"Mainichi benkyou shimasu.", contohId:"Saya belajar setiap hari."},
  {kat:"Kata Kerja", kanji:"習う", kana:"ならう", romaji:"narau", arti:"belajar (dari orang lain)", contohJp:"先生に日本語を習います。", contohRomaji:"Sensei ni nihongo o naraimasu.", contohId:"Saya belajar bahasa Jepang dari guru."},
  {kat:"Kata Kerja", kanji:"使う", kana:"つかう", romaji:"tsukau", arti:"memakai, menggunakan", contohJp:"ペンを使います。", contohRomaji:"Pen o tsukaimasu.", contohId:"Saya memakai pulpen."},
  {kat:"Kata Kerja", kanji:"待つ", kana:"まつ", romaji:"matsu", arti:"menunggu", contohJp:"バスを待ちます。", contohRomaji:"Basu o machimasu.", contohId:"Saya menunggu bus."},
  {kat:"Kata Kerja", kanji:"立つ", kana:"たつ", romaji:"tatsu", arti:"berdiri", contohJp:"ここに立ってください。", contohRomaji:"Koko ni tatte kudasai.", contohId:"Tolong berdiri di sini."},
  {kat:"Kata Kerja", kanji:"座る", kana:"すわる", romaji:"suwaru", arti:"duduk", contohJp:"椅子に座ります。", contohRomaji:"Isu ni suwarimasu.", contohId:"Saya duduk di kursi."},
  {kat:"Kata Kerja", kanji:"入る", kana:"はいる", romaji:"hairu", arti:"masuk", contohJp:"部屋に入ります。", contohRomaji:"Heya ni hairimasu.", contohId:"Saya masuk ke kamar."},
  {kat:"Kata Kerja", kanji:"出る", kana:"でる", romaji:"deru", arti:"keluar", contohJp:"家を出ます。", contohRomaji:"Ie o demasu.", contohId:"Saya keluar rumah."},
  {kat:"Kata Kerja", kanji:"作る", kana:"つくる", romaji:"tsukuru", arti:"membuat", contohJp:"料理を作ります。", contohRomaji:"Ryouri o tsukurimasu.", contohId:"Saya memasak."},
  {kat:"Kata Kerja", kanji:"分かる", kana:"わかる", romaji:"wakaru", arti:"mengerti", contohJp:"質問が分かりません。", contohRomaji:"Shitsumon ga wakarimasen.", contohId:"Saya tidak mengerti pertanyaannya."},
  {kat:"Kata Kerja", kanji:"知る", kana:"しる", romaji:"shiru", arti:"tahu, kenal", contohJp:"彼を知っています。", contohRomaji:"Kare o shitte imasu.", contohId:"Saya kenal dia."},

  // ---------------- KATA SIFAT -i ----------------
  {kat:"Kata Sifat -i", kanji:"大きい", kana:"おおきい", romaji:"ookii", arti:"besar", contohJp:"この家は大きいです。", contohRomaji:"Kono ie wa ookii desu.", contohId:"Rumah ini besar."},
  {kat:"Kata Sifat -i", kanji:"小さい", kana:"ちいさい", romaji:"chiisai", arti:"kecil", contohJp:"犬は小さいです。", contohRomaji:"Inu wa chiisai desu.", contohId:"Anjingnya kecil."},
  {kat:"Kata Sifat -i", kanji:"新しい", kana:"あたらしい", romaji:"atarashii", arti:"baru", contohJp:"新しい車を買いました。", contohRomaji:"Atarashii kuruma o kaimashita.", contohId:"Saya membeli mobil baru."},
  {kat:"Kata Sifat -i", kanji:"古い", kana:"ふるい", romaji:"furui", arti:"lama, tua (benda)", contohJp:"このカメラは古いです。", contohRomaji:"Kono kamera wa furui desu.", contohId:"Kamera ini sudah lama."},
  {kat:"Kata Sifat -i", kanji:"高い", kana:"たかい", romaji:"takai", arti:"mahal, tinggi", contohJp:"このバッグは高いです。", contohRomaji:"Kono baggu wa takai desu.", contohId:"Tas ini mahal."},
  {kat:"Kata Sifat -i", kanji:"安い", kana:"やすい", romaji:"yasui", arti:"murah", contohJp:"この店は安いです。", contohRomaji:"Kono mise wa yasui desu.", contohId:"Toko ini murah."},
  {kat:"Kata Sifat -i", kanji:"低い", kana:"ひくい", romaji:"hikui", arti:"rendah, pendek", contohJp:"この机は低いです。", contohRomaji:"Kono tsukue wa hikui desu.", contohId:"Meja ini rendah."},
  {kat:"Kata Sifat -i", kanji:"長い", kana:"ながい", romaji:"nagai", arti:"panjang", contohJp:"髪が長いです。", contohRomaji:"Kami ga nagai desu.", contohId:"Rambutnya panjang."},
  {kat:"Kata Sifat -i", kanji:"短い", kana:"みじかい", romaji:"mijikai", arti:"pendek", contohJp:"今日の授業は短いです。", contohRomaji:"Kyou no jugyou wa mijikai desu.", contohId:"Pelajaran hari ini singkat."},
  {kat:"Kata Sifat -i", kanji:"暑い", kana:"あつい", romaji:"atsui", arti:"panas (cuaca)", contohJp:"今日は暑いです。", contohRomaji:"Kyou wa atsui desu.", contohId:"Hari ini panas."},
  {kat:"Kata Sifat -i", kanji:"寒い", kana:"さむい", romaji:"samui", arti:"dingin (cuaca)", contohJp:"冬は寒いです。", contohRomaji:"Fuyu wa samui desu.", contohId:"Musim dingin itu dingin."},
  {kat:"Kata Sifat -i", kanji:"熱い", kana:"あつい", romaji:"atsui", arti:"panas (benda)", contohJp:"お茶が熱いです。", contohRomaji:"Ocha ga atsui desu.", contohId:"Tehnya panas."},
  {kat:"Kata Sifat -i", kanji:"冷たい", kana:"つめたい", romaji:"tsumetai", arti:"dingin (benda)", contohJp:"水が冷たいです。", contohRomaji:"Mizu ga tsumetai desu.", contohId:"Airnya dingin."},
  {kat:"Kata Sifat -i", kanji:"良い", kana:"いい", romaji:"ii", arti:"bagus", contohJp:"これはいい本です。", contohRomaji:"Kore wa ii hon desu.", contohId:"Ini buku yang bagus."},
  {kat:"Kata Sifat -i", kanji:"悪い", kana:"わるい", romaji:"warui", arti:"buruk", contohJp:"天気が悪いです。", contohRomaji:"Tenki ga warui desu.", contohId:"Cuacanya buruk."},
  {kat:"Kata Sifat -i", kanji:"楽しい", kana:"たのしい", romaji:"tanoshii", arti:"menyenangkan", contohJp:"旅行は楽しいです。", contohRomaji:"Ryokou wa tanoshii desu.", contohId:"Bepergian itu menyenangkan."},
  {kat:"Kata Sifat -i", kanji:"面白い", kana:"おもしろい", romaji:"omoshiroi", arti:"menarik, lucu", contohJp:"この映画は面白いです。", contohRomaji:"Kono eiga wa omoshiroi desu.", contohId:"Film ini menarik."},
  {kat:"Kata Sifat -i", kanji:"難しい", kana:"むずかしい", romaji:"muzukashii", arti:"sulit", contohJp:"この問題は難しいです。", contohRomaji:"Kono mondai wa muzukashii desu.", contohId:"Soal ini sulit."},
  {kat:"Kata Sifat -i", kanji:"易しい", kana:"やさしい", romaji:"yasashii", arti:"mudah", contohJp:"この本は易しいです。", contohRomaji:"Kono hon wa yasashii desu.", contohId:"Buku ini mudah."},
  {kat:"Kata Sifat -i", kanji:"多い", kana:"おおい", romaji:"ooi", arti:"banyak", contohJp:"学生が多いです。", contohRomaji:"Gakusei ga ooi desu.", contohId:"Muridnya banyak."},
  {kat:"Kata Sifat -i", kanji:"少ない", kana:"すくない", romaji:"sukunai", arti:"sedikit", contohJp:"時間が少ないです。", contohRomaji:"Jikan ga sukunai desu.", contohId:"Waktunya sedikit."},

  // ---------------- KATA SIFAT -na ----------------
  {kat:"Kata Sifat -na", kanji:"きれい", kana:"きれい", romaji:"kirei", arti:"cantik, bersih", contohJp:"この公園はきれいです。", contohRomaji:"Kono kouen wa kirei desu.", contohId:"Taman ini bersih/indah."},
  {kat:"Kata Sifat -na", kanji:"静か", kana:"しずか", romaji:"shizuka", arti:"tenang", contohJp:"図書館は静かです。", contohRomaji:"Toshokan wa shizuka desu.", contohId:"Perpustakaan itu tenang."},
  {kat:"Kata Sifat -na", kanji:"にぎやか", kana:"にぎやか", romaji:"nigiyaka", arti:"ramai", contohJp:"この町はにぎやかです。", contohRomaji:"Kono machi wa nigiyaka desu.", contohId:"Kota ini ramai."},
  {kat:"Kata Sifat -na", kanji:"有名", kana:"ゆうめい", romaji:"yuumei", arti:"terkenal", contohJp:"この店は有名です。", contohRomaji:"Kono mise wa yuumei desu.", contohId:"Toko ini terkenal."},
  {kat:"Kata Sifat -na", kanji:"好き", kana:"すき", romaji:"suki", arti:"suka", contohJp:"音楽が好きです。", contohRomaji:"Ongaku ga suki desu.", contohId:"Saya suka musik."},
  {kat:"Kata Sifat -na", kanji:"嫌い", kana:"きらい", romaji:"kirai", arti:"tidak suka", contohJp:"虫が嫌いです。", contohRomaji:"Mushi ga kirai desu.", contohId:"Saya tidak suka serangga."},
  {kat:"Kata Sifat -na", kanji:"暇", kana:"ひま", romaji:"hima", arti:"luang, senggang", contohJp:"今日は暇です。", contohRomaji:"Kyou wa hima desu.", contohId:"Hari ini saya senggang."},
  {kat:"Kata Sifat -na", kanji:"大丈夫", kana:"だいじょうぶ", romaji:"daijoubu", arti:"tidak apa-apa, baik-baik saja", contohJp:"大丈夫ですか。", contohRomaji:"Daijoubu desu ka.", contohId:"Apakah kamu baik-baik saja?"},
  {kat:"Kata Sifat -na", kanji:"同じ", kana:"おなじ", romaji:"onaji", arti:"sama", contohJp:"私たちは同じクラスです。", contohRomaji:"Watashitachi wa onaji kurasu desu.", contohId:"Kami kelas yang sama."},
  {kat:"Kata Sifat -na", kanji:"便利", kana:"べんり", romaji:"benri", arti:"praktis", contohJp:"駅が近くて便利です。", contohRomaji:"Eki ga chikakute benri desu.", contohId:"Praktis karena dekat stasiun."},

  // ---------------- KEHIDUPAN SEHARI-HARI ----------------
  {kat:"Kehidupan Sehari-hari", kanji:"家", kana:"いえ", romaji:"ie", arti:"rumah", contohJp:"家に帰ります。", contohRomaji:"Ie ni kaerimasu.", contohId:"Saya pulang ke rumah."},
  {kat:"Kehidupan Sehari-hari", kanji:"学校", kana:"がっこう", romaji:"gakkou", arti:"sekolah", contohJp:"学校は8時からです。", contohRomaji:"Gakkou wa hachiji kara desu.", contohId:"Sekolah mulai jam 8."},
  {kat:"Kehidupan Sehari-hari", kanji:"会社", kana:"かいしゃ", romaji:"kaisha", arti:"perusahaan", contohJp:"父の会社は大きいです。", contohRomaji:"Chichi no kaisha wa ookii desu.", contohId:"Perusahaan ayah saya besar."},
  {kat:"Kehidupan Sehari-hari", kanji:"病院", kana:"びょういん", romaji:"byouin", arti:"rumah sakit", contohJp:"病院へ行きます。", contohRomaji:"Byouin e ikimasu.", contohId:"Saya pergi ke rumah sakit."},
  {kat:"Kehidupan Sehari-hari", kanji:"銀行", kana:"ぎんこう", romaji:"ginkou", arti:"bank", contohJp:"銀行でお金を出します。", contohRomaji:"Ginkou de okane o dashimasu.", contohId:"Saya ambil uang di bank."},
  {kat:"Kehidupan Sehari-hari", kanji:"駅", kana:"えき", romaji:"eki", arti:"stasiun", contohJp:"駅はあそこです。", contohRomaji:"Eki wa asoko desu.", contohId:"Stasiunnya di sana."},
  {kat:"Kehidupan Sehari-hari", kanji:"店", kana:"みせ", romaji:"mise", arti:"toko", contohJp:"この店は便利です。", contohRomaji:"Kono mise wa benri desu.", contohId:"Toko ini praktis."},
  {kat:"Kehidupan Sehari-hari", kanji:"本", kana:"ほん", romaji:"hon", arti:"buku", contohJp:"本を読みます。", contohRomaji:"Hon o yomimasu.", contohId:"Saya membaca buku."},
  {kat:"Kehidupan Sehari-hari", kanji:"新聞", kana:"しんぶん", romaji:"shinbun", arti:"koran", contohJp:"毎朝新聞を読みます。", contohRomaji:"Maiasa shinbun o yomimasu.", contohId:"Setiap pagi saya baca koran."},
  {kat:"Kehidupan Sehari-hari", kanji:"机", kana:"つくえ", romaji:"tsukue", arti:"meja", contohJp:"机の上にペンがあります。", contohRomaji:"Tsukue no ue ni pen ga arimasu.", contohId:"Ada pulpen di atas meja."},
  {kat:"Kehidupan Sehari-hari", kanji:"椅子", kana:"いす", romaji:"isu", arti:"kursi", contohJp:"椅子に座ってください。", contohRomaji:"Isu ni suwatte kudasai.", contohId:"Tolong duduk di kursi."},
  {kat:"Kehidupan Sehari-hari", kanji:"電話", kana:"でんわ", romaji:"denwa", arti:"telepon", contohJp:"電話をかけます。", contohRomaji:"Denwa o kakemasu.", contohId:"Saya menelepon."},
  {kat:"Kehidupan Sehari-hari", kanji:"テレビ", kana:"テレビ", romaji:"terebi", arti:"televisi", contohJp:"テレビを見ます。", contohRomaji:"Terebi o mimasu.", contohId:"Saya menonton TV."},
  {kat:"Kehidupan Sehari-hari", kanji:"水", kana:"みず", romaji:"mizu", arti:"air", contohJp:"水を飲みます。", contohRomaji:"Mizu o nomimasu.", contohId:"Saya minum air."},
  {kat:"Kehidupan Sehari-hari", kanji:"お金", kana:"おかね", romaji:"okane", arti:"uang", contohJp:"お金がありません。", contohRomaji:"Okane ga arimasen.", contohId:"Saya tidak punya uang."},
  {kat:"Kehidupan Sehari-hari", kanji:"傘", kana:"かさ", romaji:"kasa", arti:"payung", contohJp:"傘を持ちます。", contohRomaji:"Kasa o mochimasu.", contohId:"Saya membawa payung."},

  // ---------------- KELUARGA & ORANG ----------------
  {kat:"Keluarga & Orang", kanji:"父", kana:"ちち", romaji:"chichi", arti:"ayah (sendiri)", contohJp:"父は先生です。", contohRomaji:"Chichi wa sensei desu.", contohId:"Ayah saya seorang guru."},
  {kat:"Keluarga & Orang", kanji:"母", kana:"はは", romaji:"haha", arti:"ibu (sendiri)", contohJp:"母は料理が上手です。", contohRomaji:"Haha wa ryouri ga jouzu desu.", contohId:"Ibu saya pandai memasak."},
  {kat:"Keluarga & Orang", kanji:"兄", kana:"あに", romaji:"ani", arti:"kakak laki-laki (sendiri)", contohJp:"兄は会社員です。", contohRomaji:"Ani wa kaishain desu.", contohId:"Kakak laki-laki saya karyawan."},
  {kat:"Keluarga & Orang", kanji:"姉", kana:"あね", romaji:"ane", arti:"kakak perempuan (sendiri)", contohJp:"姉は大学生です。", contohRomaji:"Ane wa daigakusei desu.", contohId:"Kakak perempuan saya mahasiswa."},
  {kat:"Keluarga & Orang", kanji:"弟", kana:"おとうと", romaji:"otouto", arti:"adik laki-laki", contohJp:"弟は中学生です。", contohRomaji:"Otouto wa chuugakusei desu.", contohId:"Adik laki-laki saya siswa SMP."},
  {kat:"Keluarga & Orang", kanji:"妹", kana:"いもうと", romaji:"imouto", arti:"adik perempuan", contohJp:"妹は小学生です。", contohRomaji:"Imouto wa shougakusei desu.", contohId:"Adik perempuan saya siswa SD."},
  {kat:"Keluarga & Orang", kanji:"友達", kana:"ともだち", romaji:"tomodachi", arti:"teman", contohJp:"友達と遊びます。", contohRomaji:"Tomodachi to asobimasu.", contohId:"Saya bermain dengan teman."},
  {kat:"Keluarga & Orang", kanji:"先生", kana:"せんせい", romaji:"sensei", arti:"guru", contohJp:"先生に質問します。", contohRomaji:"Sensei ni shitsumon shimasu.", contohId:"Saya bertanya kepada guru."},
  {kat:"Keluarga & Orang", kanji:"学生", kana:"がくせい", romaji:"gakusei", arti:"murid, mahasiswa", contohJp:"私は学生です。", contohRomaji:"Watashi wa gakusei desu.", contohId:"Saya seorang pelajar."},
  {kat:"Keluarga & Orang", kanji:"子供", kana:"こども", romaji:"kodomo", arti:"anak-anak", contohJp:"子供が公園で遊びます。", contohRomaji:"Kodomo ga kouen de asobimasu.", contohId:"Anak-anak bermain di taman."},

  // ---------------- WAKTU & TANGGAL ----------------
  {kat:"Waktu & Tanggal", kanji:"今日", kana:"きょう", romaji:"kyou", arti:"hari ini", contohJp:"今日は暑いです。", contohRomaji:"Kyou wa atsui desu.", contohId:"Hari ini panas."},
  {kat:"Waktu & Tanggal", kanji:"明日", kana:"あした", romaji:"ashita", arti:"besok", contohJp:"明日休みです。", contohRomaji:"Ashita yasumi desu.", contohId:"Besok libur."},
  {kat:"Waktu & Tanggal", kanji:"昨日", kana:"きのう", romaji:"kinou", arti:"kemarin", contohJp:"昨日映画を見ました。", contohRomaji:"Kinou eiga o mimashita.", contohId:"Kemarin saya menonton film."},
  {kat:"Waktu & Tanggal", kanji:"今", kana:"いま", romaji:"ima", arti:"sekarang", contohJp:"今何時ですか。", contohRomaji:"Ima nanji desu ka.", contohId:"Sekarang jam berapa?"},
  {kat:"Waktu & Tanggal", kanji:"毎日", kana:"まいにち", romaji:"mainichi", arti:"setiap hari", contohJp:"毎日勉強します。", contohRomaji:"Mainichi benkyou shimasu.", contohId:"Saya belajar setiap hari."},
  {kat:"Waktu & Tanggal", kanji:"今週", kana:"こんしゅう", romaji:"konshuu", arti:"minggu ini", contohJp:"今週は忙しいです。", contohRomaji:"Konshuu wa isogashii desu.", contohId:"Minggu ini sibuk."},
  {kat:"Waktu & Tanggal", kanji:"来週", kana:"らいしゅう", romaji:"raishuu", arti:"minggu depan", contohJp:"来週テストがあります。", contohRomaji:"Raishuu tesuto ga arimasu.", contohId:"Minggu depan ada tes."},
  {kat:"Waktu & Tanggal", kanji:"先週", kana:"せんしゅう", romaji:"senshuu", arti:"minggu lalu", contohJp:"先週旅行しました。", contohRomaji:"Senshuu ryokou shimashita.", contohId:"Minggu lalu saya bepergian."},
  {kat:"Waktu & Tanggal", kanji:"朝", kana:"あさ", romaji:"asa", arti:"pagi", contohJp:"朝ご飯を食べます。", contohRomaji:"Asagohan o tabemasu.", contohId:"Saya makan sarapan."},
  {kat:"Waktu & Tanggal", kanji:"昼", kana:"ひる", romaji:"hiru", arti:"siang", contohJp:"昼にご飯を食べます。", contohRomaji:"Hiru ni gohan o tabemasu.", contohId:"Saya makan siang."},
  {kat:"Waktu & Tanggal", kanji:"夜", kana:"よる", romaji:"yoru", arti:"malam", contohJp:"夜勉強します。", contohRomaji:"Yoru benkyou shimasu.", contohId:"Saya belajar di malam hari."},
  {kat:"Waktu & Tanggal", kanji:"時間", kana:"じかん", romaji:"jikan", arti:"waktu", contohJp:"時間がありません。", contohRomaji:"Jikan ga arimasen.", contohId:"Tidak ada waktu."},

  // ---------------- TEMPAT & ARAH ----------------
  {kat:"Tempat & Arah", kanji:"上", kana:"うえ", romaji:"ue", arti:"atas", contohJp:"机の上にあります。", contohRomaji:"Tsukue no ue ni arimasu.", contohId:"Ada di atas meja."},
  {kat:"Tempat & Arah", kanji:"下", kana:"した", romaji:"shita", arti:"bawah", contohJp:"机の下にあります。", contohRomaji:"Tsukue no shita ni arimasu.", contohId:"Ada di bawah meja."},
  {kat:"Tempat & Arah", kanji:"中", kana:"なか", romaji:"naka", arti:"dalam", contohJp:"箱の中にあります。", contohRomaji:"Hako no naka ni arimasu.", contohId:"Ada di dalam kotak."},
  {kat:"Tempat & Arah", kanji:"外", kana:"そと", romaji:"soto", arti:"luar", contohJp:"外は寒いです。", contohRomaji:"Soto wa samui desu.", contohId:"Di luar dingin."},
  {kat:"Tempat & Arah", kanji:"右", kana:"みぎ", romaji:"migi", arti:"kanan", contohJp:"右に曲がってください。", contohRomaji:"Migi ni magatte kudasai.", contohId:"Tolong belok kanan."},
  {kat:"Tempat & Arah", kanji:"左", kana:"ひだり", romaji:"hidari", arti:"kiri", contohJp:"左に銀行があります。", contohRomaji:"Hidari ni ginkou ga arimasu.", contohId:"Ada bank di sebelah kiri."},
  {kat:"Tempat & Arah", kanji:"前", kana:"まえ", romaji:"mae", arti:"depan", contohJp:"駅の前で待ちます。", contohRomaji:"Eki no mae de machimasu.", contohId:"Saya menunggu di depan stasiun."},
  {kat:"Tempat & Arah", kanji:"後ろ", kana:"うしろ", romaji:"ushiro", arti:"belakang", contohJp:"学校の後ろに公園があります。", contohRomaji:"Gakkou no ushiro ni kouen ga arimasu.", contohId:"Ada taman di belakang sekolah."},

  // ---------------- MAKANAN & BELANJA ----------------
  {kat:"Makanan & Belanja", kanji:"ご飯", kana:"ごはん", romaji:"gohan", arti:"nasi, makanan", contohJp:"ご飯を食べます。", contohRomaji:"Gohan o tabemasu.", contohId:"Saya makan nasi."},
  {kat:"Makanan & Belanja", kanji:"パン", kana:"パン", romaji:"pan", arti:"roti", contohJp:"パンを買います。", contohRomaji:"Pan o kaimasu.", contohId:"Saya membeli roti."},
  {kat:"Makanan & Belanja", kanji:"肉", kana:"にく", romaji:"niku", arti:"daging", contohJp:"肉が好きです。", contohRomaji:"Niku ga suki desu.", contohId:"Saya suka daging."},
  {kat:"Makanan & Belanja", kanji:"魚", kana:"さかな", romaji:"sakana", arti:"ikan", contohJp:"魚を食べます。", contohRomaji:"Sakana o tabemasu.", contohId:"Saya makan ikan."},
  {kat:"Makanan & Belanja", kanji:"野菜", kana:"やさい", romaji:"yasai", arti:"sayuran", contohJp:"野菜を買います。", contohRomaji:"Yasai o kaimasu.", contohId:"Saya membeli sayuran."},
  {kat:"Makanan & Belanja", kanji:"果物", kana:"くだもの", romaji:"kudamono", arti:"buah", contohJp:"果物が好きです。", contohRomaji:"Kudamono ga suki desu.", contohId:"Saya suka buah."},

  // ---------------- KATA KETERANGAN & LAINNYA ----------------
  {kat:"Kata Keterangan & Lainnya", kanji:"とても", kana:"とても", romaji:"totemo", arti:"sangat", contohJp:"とても楽しいです。", contohRomaji:"Totemo tanoshii desu.", contohId:"Sangat menyenangkan."},
  {kat:"Kata Keterangan & Lainnya", kanji:"少し", kana:"すこし", romaji:"sukoshi", arti:"sedikit", contohJp:"少し休みます。", contohRomaji:"Sukoshi yasumimasu.", contohId:"Saya istirahat sebentar."},
  {kat:"Kata Keterangan & Lainnya", kanji:"たくさん", kana:"たくさん", romaji:"takusan", arti:"banyak", contohJp:"たくさん食べました。", contohRomaji:"Takusan tabemashita.", contohId:"Saya makan banyak."},
  {kat:"Kata Keterangan & Lainnya", kanji:"いつも", kana:"いつも", romaji:"itsumo", arti:"selalu", contohJp:"いつも元気です。", contohRomaji:"Itsumo genki desu.", contohId:"Saya selalu sehat."},
  {kat:"Kata Keterangan & Lainnya", kanji:"よく", kana:"よく", romaji:"yoku", arti:"sering, dengan baik", contohJp:"よく映画を見ます。", contohRomaji:"Yoku eiga o mimasu.", contohId:"Saya sering menonton film."},
  {kat:"Kata Keterangan & Lainnya", kanji:"あまり", kana:"あまり", romaji:"amari", arti:"tidak terlalu (dgn negatif)", contohJp:"あまり食べません。", contohRomaji:"Amari tabemasen.", contohId:"Saya tidak terlalu banyak makan."},
  {kat:"Kata Keterangan & Lainnya", kanji:"全然", kana:"ぜんぜん", romaji:"zenzen", arti:"sama sekali tidak", contohJp:"全然分かりません。", contohRomaji:"Zenzen wakarimasen.", contohId:"Saya sama sekali tidak mengerti."},
  {kat:"Kata Keterangan & Lainnya", kanji:"もう", kana:"もう", romaji:"mou", arti:"sudah", contohJp:"もう食べました。", contohRomaji:"Mou tabemashita.", contohId:"Saya sudah makan."},
  {kat:"Kata Keterangan & Lainnya", kanji:"まだ", kana:"まだ", romaji:"mada", arti:"masih, belum", contohJp:"まだ食べていません。", contohRomaji:"Mada tabete imasen.", contohId:"Saya belum makan."}
];
