// ===================================================================
// Qategori Nihongo - Reading (読解) JLPT N5
// Furigana: {漢字|かんじ} (kata dalam kurung kurawal, bacaan setelah |)
// tipe: tanbun (bacaan pendek), chuubun (menengah), jouhou (pencarian informasi)
// ===================================================================
window.N5_READING = [

{id:"n5r01", tipe:"tanbun", topik:"Perkenalan diri",
 judul:"{私|わたし}の{家族|かぞく}",
 teks:"{私|わたし}の{家族|かぞく}は{四人|よにん}です。{父|ちち}と{母|はは}と{弟|おとうと}と{私|わたし}です。{父|ちち}は{会社員|かいしゃいん}です。{母|はは}は{先生|せんせい}です。{弟|おとうと}は{十歳|じっさい}で、{小学生|しょうがくせい}です。{私|わたし}は{大学生|だいがくせい}です。{日曜日|にちようび}は{家族|かぞく}みんなで{晩|ばん}ご{飯|はん}を{食|た}べます。",
 terjemahan:"Keluarga saya empat orang. Ayah, ibu, adik laki-laki, dan saya. Ayah karyawan. Ibu guru. Adik berusia sepuluh tahun dan murid SD. Saya mahasiswa. Hari Minggu kami sekeluarga makan malam bersama.",
 soal:[
  {q:"{私|わたし}の{家族|かぞく}は{何人|なんにん}ですか。", opt:["{三人|さんにん}","{四人|よにん}","{五人|ごにん}","{六人|ろくにん}"], correct:1, exp:"Teks menyebut 家族は四人です."},
  {q:"{母|はは}は{何|なに}をしていますか。", opt:["{会社員|かいしゃいん}","{学生|がくせい}","{先生|せんせい}","{医者|いしゃ}"], correct:2, exp:"母は先生です → ibu adalah guru."},
  {q:"{日曜日|にちようび}に{何|なに}をしますか。", opt:["{家族|かぞく}で{晩|ばん}ご{飯|はん}を{食|た}べる","{学校|がっこう}へ{行|い}く","{会社|かいしゃ}で{働|はたら}く","{一人|ひとり}で{旅行|りょこう}する"], correct:0, exp:"日曜日は家族みんなで晩ご飯を食べます."}
 ]},

{id:"n5r02", tipe:"tanbun", topik:"Rutinitas",
 judul:"{私|わたし}の{朝|あさ}",
 teks:"{私|わたし}は{毎朝|まいあさ}6{時|じ}に{起|お}きます。{顔|かお}を{洗|あら}って、{朝|あさ}ご{飯|はん}を{食|た}べます。パンと{卵|たまご}と{牛乳|ぎゅうにゅう}です。7{時|じ}に{家|いえ}を{出|で}て、{電車|でんしゃ}で{学校|がっこう}へ{行|い}きます。{学校|がっこう}まで30{分|ぷん}かかります。",
 terjemahan:"Setiap pagi saya bangun jam 6. Saya mencuci muka lalu sarapan. Sarapannya roti, telur, dan susu. Jam 7 saya keluar rumah dan pergi ke sekolah naik kereta. Ke sekolah memakan waktu 30 menit.",
 soal:[
  {q:"{私|わたし}は{何時|なんじ}に{起|お}きますか。", opt:["5{時|じ}","6{時|じ}","7{時|じ}","8{時|じ}"], correct:1, exp:"毎朝6時に起きます."},
  {q:"{朝|あさ}ご{飯|はん}に{何|なに}を{食|た}べますか。", opt:["ご{飯|はん}とお{茶|ちゃ}","パンと{卵|たまご}と{牛乳|ぎゅうにゅう}","{魚|さかな}と{野菜|やさい}","ラーメン"], correct:1, exp:"パンと卵と牛乳です."},
  {q:"どうやって{学校|がっこう}へ{行|い}きますか。", opt:["バスで","{自転車|じてんしゃ}で","{電車|でんしゃ}で","{歩|ある}いて"], correct:2, exp:"電車で学校へ行きます."}
 ]},

{id:"n5r03", tipe:"tanbun", topik:"Surel",
 judul:"{友|とも}だちへのメール",
 teks:"{山田|やまだ}さんへ\n{来週|らいしゅう}の{日曜日|にちようび}、いっしょに{映画|えいが}を{見|み}に{行|い}きませんか。{映画|えいが}は{午後|ごご}2{時|じ}からです。{駅|えき}の{前|まえ}で1{時|じ}に{会|あ}いましょう。{返事|へんじ}を{待|ま}っています。\n{田中|たなか}",
 terjemahan:"Untuk Yamada.\nMinggu depan hari Minggu, maukah kita menonton film bersama? Filmnya mulai jam 2 siang. Mari bertemu di depan stasiun jam 1. Saya menunggu balasanmu.\nTanaka",
 soal:[
  {q:"{二人|ふたり}は{何|なに}を{見|み}に{行|い}きますか。", opt:["{絵|え}","{映画|えいが}","{花|はな}","{山|やま}"], correct:1, exp:"いっしょに映画を見に行きませんか."},
  {q:"{二人|ふたり}は{何時|なんじ}にどこで{会|あ}いますか。", opt:["1{時|じ}に{駅|えき}の{前|まえ}","2{時|じ}に{映画館|えいがかん}","1{時|じ}に{学校|がっこう}","2{時|じ}に{駅|えき}の{前|まえ}"], correct:0, exp:"駅の前で1時に会いましょう (film mulai jam 2)."}
 ]},

{id:"n5r04", tipe:"tanbun", topik:"Catatan harian",
 judul:"{日記|にっき}",
 teks:"10{月|がつ}5{日|か}　{日曜日|にちようび}　{晴|は}れ\n{今日|きょう}は{友|とも}だちと{公園|こうえん}へ{行|い}きました。{公園|こうえん}は{広|ひろ}くて、{花|はな}がたくさんありました。{友|とも}だちと{写真|しゃしん}を{撮|と}りました。それから、{喫茶店|きっさてん}でコーヒーを{飲|の}みました。とても{楽|たの}しかったです。",
 terjemahan:"5 Oktober, Minggu, cerah.\nHari ini saya pergi ke taman bersama teman. Tamannya luas dan banyak bunga. Kami mengambil foto bersama. Setelah itu kami minum kopi di kafe. Sangat menyenangkan.",
 soal:[
  {q:"{今日|きょう}の{天気|てんき}は？", opt:["{雨|あめ}","{晴|は}れ","{曇|くも}り","{雪|ゆき}"], correct:1, exp:"Tanggal dan cuaca tertulis: 晴れ (cerah)."},
  {q:"{公園|こうえん}で{何|なに}をしましたか。", opt:["{泳|およ}いだ","{写真|しゃしん}を{撮|と}った","{勉強|べんきょう}した","{買|か}い{物|もの}をした"], correct:1, exp:"友だちと写真を撮りました."},
  {q:"{喫茶店|きっさてん}で{何|なに}を{飲|の}みましたか。", opt:["お{茶|ちゃ}","{水|みず}","コーヒー","ジュース"], correct:2, exp:"喫茶店でコーヒーを飲みました."}
 ]},

{id:"n5r05", tipe:"tanbun", topik:"Memo",
 judul:"お{母|かあ}さんのメモ",
 teks:"{花子|はなこ}へ\nお{母|かあ}さんは{買|か}い{物|もの}に{行|い}きます。ご{飯|はん}は{冷蔵庫|れいぞうこ}の{中|なか}にあります。{食|た}べてください。{宿題|しゅくだい}をしてから、{遊|あそ}んでください。\n{母|はは}",
 terjemahan:"Untuk Hanako.\nIbu pergi berbelanja. Makanan ada di dalam kulkas. Silakan dimakan. Kerjakan PR dulu, baru bermain.\nIbu",
 soal:[
  {q:"お{母|かあ}さんは{今|いま}どこへ{行|い}きましたか。", opt:["{学校|がっこう}","{買|か}い{物|もの}","{会社|かいしゃ}","{病院|びょういん}"], correct:1, exp:"お母さんは買い物に行きます."},
  {q:"ご{飯|はん}はどこにありますか。", opt:["{机|つくえ}の{上|うえ}","{冷蔵庫|れいぞうこ}の{中|なか}","かばんの{中|なか}","{庭|にわ}"], correct:1, exp:"ご飯は冷蔵庫の中にあります."},
  {q:"{花子|はなこ}は{遊|あそ}ぶ{前|まえ}に{何|なに}をしますか。", opt:["{宿題|しゅくだい}","{掃除|そうじ}","{買|か}い{物|もの}","{料理|りょうり}"], correct:0, exp:"宿題をしてから、遊んでください."}
 ]},

{id:"n5r06", tipe:"tanbun", topik:"Pengumuman",
 judul:"{図書館|としょかん}のお{知|し}らせ",
 teks:"{図書館|としょかん}は{朝|あさ}9{時|じ}から{夜|よる}8{時|じ}まで{開|あ}いています。{月曜日|げつようび}は{休|やす}みです。{本|ほん}は{一人|ひとり}3{冊|さつ}まで{借|か}りられます。{静|しず}かに{本|ほん}を{読|よ}んでください。",
 terjemahan:"Perpustakaan buka dari jam 9 pagi sampai jam 8 malam. Hari Senin libur. Buku bisa dipinjam sampai 3 buku per orang. Silakan membaca buku dengan tenang.",
 soal:[
  {q:"{図書館|としょかん}は{何時|なんじ}まで{開|あ}いていますか。", opt:["{夕方|ゆうがた}5{時|じ}","{夜|よる}8{時|じ}","{夜|よる}10{時|じ}","{朝|あさ}9{時|じ}"], correct:1, exp:"朝9時から夜8時まで開いています."},
  {q:"{休|やす}みは{何曜日|なんようび}ですか。", opt:["{月曜日|げつようび}","{火曜日|かようび}","{土曜日|どようび}","{日曜日|にちようび}"], correct:0, exp:"月曜日は休みです."},
  {q:"{本|ほん}は{何冊|なんさつ}{借|か}りられますか。", opt:["1{冊|さつ}","2{冊|さつ}","3{冊|さつ}","5{冊|さつ}"], correct:2, exp:"一人3冊まで借りられます."}
 ]},

{id:"n5r07", tipe:"chuubun", topik:"Esai pribadi",
 judul:"{日本|にほん}の{生活|せいかつ}",
 teks:"{私|わたし}は{先月|せんげつ}、{日本|にほん}に{来|き}ました。{日本|にほん}の{食|た}べ{物|もの}は{美味|おい}しいですが、{少|すこ}し{高|たか}いです。{電車|でんしゃ}はとても{便利|べんり}です。でも、{朝|あさ}は{人|ひと}が{多|おお}くて、{大変|たいへん}です。{日本語|にほんご}はまだ{上手|じょうず}ではありませんが、{毎日|まいにち}{勉強|べんきょう}しています。",
 terjemahan:"Saya datang ke Jepang bulan lalu. Makanan Jepang enak, tetapi agak mahal. Kereta sangat praktis. Tetapi di pagi hari orangnya banyak dan repot. Bahasa Jepang saya belum mahir, tetapi saya belajar setiap hari.",
 soal:[
  {q:"{日本|にほん}の{食|た}べ{物|もの}はどうですか。", opt:["{美味|おい}しくて、{安|やす}い","{美味|おい}しいが、{少|すこ}し{高|たか}い","まずくて、{高|たか}い","{安|やす}いが、まずい"], correct:1, exp:"食べ物は美味しいですが、少し高いです."},
  {q:"{朝|あさ}の{電車|でんしゃ}はどうですか。", opt:["{人|ひと}が{少|すく}ない","{人|ひと}が{多|おお}くて{大変|たいへん}","{遅|おそ}い","{高|たか}い"], correct:1, exp:"朝は人が多くて、大変です."},
  {q:"{私|わたし}は{毎日|まいにち}{何|なに}をしていますか。", opt:["{日本語|にほんご}を{勉強|べんきょう}する","{旅行|りょこう}する","{友|とも}だちと{遊|あそ}ぶ","{料理|りょうり}を{習|なら}う"], correct:0, exp:"毎日勉強しています (belajar bahasa Jepang)."}
 ]},

{id:"n5r08", tipe:"chuubun", topik:"Pengalaman",
 judul:"{先週|せんしゅう}の{日曜日|にちようび}",
 teks:"{先週|せんしゅう}の{日曜日|にちようび}、{私|わたし}は{家族|かぞく}と{海|うみ}へ{行|い}きました。{車|くるま}で2{時間|じかん}かかりました。{海|うみ}はとてもきれいでした。{私|わたし}は{弟|おとうと}と{泳|およ}ぎました。{昼|ひる}ご{飯|はん}に{魚|さかな}を{食|た}べました。{夕方|ゆうがた}に{家|いえ}へ{帰|かえ}りました。{疲|つか}れましたが、{楽|たの}しい{一日|いちにち}でした。",
 terjemahan:"Minggu lalu, saya pergi ke laut bersama keluarga. Naik mobil memakan waktu 2 jam. Lautnya sangat indah. Saya berenang dengan adik. Untuk makan siang kami makan ikan. Sore hari kami pulang ke rumah. Lelah, tetapi hari yang menyenangkan.",
 soal:[
  {q:"{海|うみ}まで、どのくらいかかりましたか。", opt:["30{分|ぷん}","1{時間|じかん}","2{時間|じかん}","3{時間|じかん}"], correct:2, exp:"車で2時間かかりました."},
  {q:"{昼|ひる}ご{飯|はん}に{何|なに}を{食|た}べましたか。", opt:["{肉|にく}","{魚|さかな}","パン","ラーメン"], correct:1, exp:"昼ご飯に魚を食べました."},
  {q:"{何時|なんじ}ごろ{家|いえ}へ{帰|かえ}りましたか。", opt:["{朝|あさ}","{昼|ひる}","{夕方|ゆうがた}","{夜中|よなか}"], correct:2, exp:"夕方に家へ帰りました."}
 ]},

{id:"n5r09", tipe:"jouhou", topik:"Menu",
 judul:"レストランのメニュー",
 teks:"【ランチ】\nA　カレーライス　　　　700{円|えん}\nB　ラーメン　　　　　　600{円|えん}\nC　{魚|さかな}のセット　　　　900{円|えん}\n（{飲|の}み{物|もの}は100{円|えん}です）\n{昼|ひる}12{時|じ}から2{時|じ}までです。",
 terjemahan:"[Makan siang]\nA Nasi kari 700 yen\nB Ramen 600 yen\nC Set ikan 900 yen\n(Minuman 100 yen)\nJam 12 siang sampai jam 2.",
 soal:[
  {q:"{一番|いちばん}{安|やす}いのはどれですか。", opt:["カレーライス","ラーメン","{魚|さかな}のセット","{飲|の}み{物|もの}"], correct:1, exp:"Ramen 600 yen adalah yang termurah."},
  {q:"ラーメンと{飲|の}み{物|もの}で、いくらですか。", opt:["600{円|えん}","700{円|えん}","800{円|えん}","1000{円|えん}"], correct:1, exp:"600 + 100 = 700 yen."},
  {q:"ランチは{何時|なんじ}までですか。", opt:["12{時|じ}","1{時|じ}","2{時|じ}","3{時|じ}"], correct:2, exp:"昼12時から2時までです."}
 ]},

{id:"n5r10", tipe:"jouhou", topik:"Jadwal",
 judul:"バスの{時間|じかん}",
 teks:"【{駅|えき}から{大学|だいがく}まで】\n{朝|あさ}　8{時|じ}00{分|ふん}　8{時|じ}20{分|ぷん}　8{時|じ}40{分|ぷん}\n{昼|ひる}　12{時|じ}00{分|ふん}　12{時|じ}30{分|ぷん}\n{料金|りょうきん}：200{円|えん}\n{土曜日|どようび}と{日曜日|にちようび}は、バスがありません。",
 terjemahan:"[Dari stasiun ke universitas]\nPagi: 8.00, 8.20, 8.40\nSiang: 12.00, 12.30\nTarif: 200 yen\nHari Sabtu dan Minggu tidak ada bus.",
 soal:[
  {q:"{朝|あさ}のバスは{何回|なんかい}ありますか。", opt:["1{回|かい}","2{回|かい}","3{回|かい}","5{回|かい}"], correct:2, exp:"Pagi: 8.00, 8.20, 8.40 = 3 kali."},
  {q:"バスの{料金|りょうきん}はいくらですか。", opt:["100{円|えん}","200{円|えん}","300{円|えん}","400{円|えん}"], correct:1, exp:"料金：200円."},
  {q:"{日曜日|にちようび}はどうですか。", opt:["バスがない","バスが{多|おお}い","バスは{安|やす}い","バスは{朝|あさ}だけ"], correct:0, exp:"土曜日と日曜日は、バスがありません."}
 ]}

];

// Arti per kotoba untuk popup Reading. Kunci: kata|bacaan (sama dengan markup {kata|bacaan}).
window.N5_READING_GLOSS = {
  "一人|ひとり": "satu orang",
  "一日|いちにち": "satu hari",
  "一番|いちばん": "paling",
  "三人|さんにん": "tiga orang",
  "上|うえ": "atas",
  "上手|じょうず": "pandai, mahir",
  "中|なか": "dalam",
  "二人|ふたり": "dua orang",
  "五人|ごにん": "lima orang",
  "人|ひと": "orang",
  "今|いま": "sekarang",
  "今日|きょう": "hari ini",
  "休|やす": "libur, istirahat (休む)",
  "会|あ": "bertemu (会う)",
  "会社|かいしゃ": "perusahaan",
  "会社員|かいしゃいん": "karyawan perusahaan",
  "何|なに": "apa",
  "何人|なんにん": "berapa orang",
  "何冊|なんさつ": "berapa buku",
  "何回|なんかい": "berapa kali",
  "何時|なんじ": "jam berapa",
  "何曜日|なんようび": "hari apa",
  "便利|べんり": "praktis",
  "借|か": "meminjam (借りる)",
  "働|はたら": "bekerja (働く)",
  "先月|せんげつ": "bulan lalu",
  "先生|せんせい": "guru",
  "先週|せんしゅう": "minggu lalu",
  "公園|こうえん": "taman",
  "六人|ろくにん": "enam orang",
  "円|えん": "yen",
  "冊|さつ": "penghitung buku",
  "写真|しゃしん": "foto",
  "冷蔵庫|れいぞうこ": "kulkas",
  "出|で": "keluar, hadir (出る)",
  "分|ふん": "menit (penghitung)",
  "分|ぷん": "menit (penghitung)",
  "前|まえ": "sebelum, depan",
  "勉強|べんきょう": "belajar",
  "医者|いしゃ": "dokter",
  "十歳|じっさい": "sepuluh tahun (usia)",
  "午後|ごご": "siang/sore (setelah tengah hari)",
  "卵|たまご": "telur",
  "友|とも": "teman (友だち)",
  "喫茶店|きっさてん": "kafe",
  "四人|よにん": "empat orang",
  "回|かい": "kali, pertemuan",
  "図書館|としょかん": "perpustakaan",
  "土曜日|どようび": "hari Sabtu",
  "夕方|ゆうがた": "sore",
  "多|おお": "banyak (多い)",
  "夜|よる": "malam",
  "夜中|よなか": "tengah malam",
  "大変|たいへん": "repot, berat",
  "大学|だいがく": "universitas",
  "大学生|だいがくせい": "mahasiswa",
  "天気|てんき": "cuaca",
  "学校|がっこう": "sekolah",
  "学生|がくせい": "pelajar, mahasiswa",
  "安|やす": "murah (安い)",
  "家|いえ": "rumah",
  "家族|かぞく": "keluarga",
  "宿題|しゅくだい": "PR",
  "小学生|しょうがくせい": "siswa SD",
  "少|すく": "sedikit (少ない)",
  "少|すこ": "sedikit (少し)",
  "山|やま": "gunung",
  "山田|やまだ": "Yamada (nama keluarga)",
  "帰|かえ": "pulang (帰る)",
  "広|ひろ": "luas (広い)",
  "庭|にわ": "halaman",
  "弟|おとうと": "adik laki-laki",
  "待|ま": "menunggu (待つ)",
  "掃除|そうじ": "bersih-bersih",
  "撮|と": "memotret (撮る)",
  "料理|りょうり": "memasak, masakan",
  "料金|りょうきん": "tarif, biaya",
  "旅行|りょこう": "bepergian, wisata",
  "日|か": "tanggal (5日 = tanggal 5)",
  "日曜日|にちようび": "hari Minggu",
  "日本|にほん": "Jepang",
  "日本語|にほんご": "bahasa Jepang",
  "日記|にっき": "buku harian",
  "映画|えいが": "film",
  "映画館|えいがかん": "bioskop",
  "昼|ひる": "siang",
  "時|じ": "jam (pukul)",
  "時間|じかん": "waktu",
  "晩|ばん": "malam (晩ご飯: makan malam)",
  "晴|は": "cerah (晴れ)",
  "曇|くも": "berawan (曇り)",
  "月|がつ": "bulan (10月 = Oktober)",
  "月曜日|げつようび": "hari Senin",
  "朝|あさ": "pagi",
  "本|ほん": "buku",
  "机|つくえ": "meja",
  "来|き": "datang (来た)",
  "来週|らいしゅう": "minggu depan",
  "楽|たの": "menyenangkan (楽しい)",
  "歩|ある": "berjalan (歩く)",
  "母|かあ": "ibu (お母さん)",
  "母|はは": "ibu (milik sendiri)",
  "毎日|まいにち": "setiap hari",
  "毎朝|まいあさ": "setiap pagi",
  "水|みず": "air",
  "泳|およ": "berenang (泳ぐ)",
  "洗|あら": "mencuci (洗う)",
  "海|うみ": "laut",
  "火曜日|かようび": "hari Selasa",
  "父|ちち": "ayah (sendiri)",
  "牛乳|ぎゅうにゅう": "susu",
  "物|もの": "benda, barang (飲み物 = minuman)",
  "生活|せいかつ": "kehidupan",
  "田中|たなか": "Tanaka (nama keluarga)",
  "疲|つか": "lelah (疲れる)",
  "病院|びょういん": "rumah sakit",
  "知|し": "memberi tahu (知らせ・知らせる)",
  "私|わたし": "saya",
  "絵|え": "lukisan",
  "美味|おい": "enak (美味しい)",
  "習|なら": "belajar (習う)",
  "肉|にく": "daging",
  "自転車|じてんしゃ": "sepeda",
  "花|はな": "bunga",
  "花子|はなこ": "Hanako (nama perempuan)",
  "茶|ちゃ": "teh (お茶)",
  "行|い": "pergi (行く)",
  "見|み": "melihat (見る)",
  "読|よ": "membaca (読む)",
  "買|か": "membeli (買う)",
  "起|お": "terjadi (起きる)",
  "車|くるま": "mobil",
  "返事|へんじ": "balasan, jawaban",
  "遅|おそ": "larut, lambat (遅い)",
  "遊|あそ": "bermain (遊ぶ)",
  "野菜|やさい": "sayur",
  "開|あ": "terbuka, buka (開く)",
  "雨|あめ": "hujan",
  "雪|ゆき": "salju",
  "電車|でんしゃ": "kereta",
  "静|しず": "tenang (静か)",
  "顔|かお": "wajah",
  "食|た": "makan (食べる)",
  "飯|はん": "nasi (ご飯)",
  "飲|の": "minum (飲む)",
  "駅|えき": "stasiun",
  "高|たか": "tinggi, mahal (高い)",
  "魚|さかな": "ikan"
};
