// ===================================================================
// Qategori Nihongo - Kotoba (Kosakata) JLPT N2
// 10 kategori. Tiap kotoba: kat, kanji, kana, romaji, arti, contohJp, contohRomaji, contohId
// ===================================================================
window.N2_KOTOBA = [

// ================= 1. KATA KERJA (DOUSHI) =================
{kat:"Kata Kerja", kanji:"心がける", kana:"こころがける", romaji:"kokorogakeru", arti:"berusaha memperhatikan", contohJp:"健康に気をつけるよう心がけている。", contohRomaji:"Kenkou ni ki o tsukeru you kokorogakete iru.", contohId:"Saya berusaha memperhatikan kesehatan."},
{kat:"Kata Kerja", kanji:"見なす", kana:"みなす", romaji:"minasu", arti:"menganggap", contohJp:"返事がなければ、欠席と見なします。", contohRomaji:"Henji ga nakereba, kesseki to minashimasu.", contohId:"Kalau tidak ada balasan, akan dianggap tidak hadir."},
{kat:"Kata Kerja", kanji:"見込む", kana:"みこむ", romaji:"mikomu", arti:"memperkirakan", contohJp:"来年は売上が増加すると見込んでいる。", contohRomaji:"Rainen wa uriage ga zouka suru to mikonde iru.", contohId:"Diperkirakan penjualan tahun depan akan meningkat."},
{kat:"Kata Kerja", kanji:"見送る", kana:"みおくる", romaji:"miokuru", arti:"melepas kepergian, menunda", contohJp:"今回の計画は見送ることにした。", contohRomaji:"Konkai no keikaku wa miokuru koto ni shita.", contohId:"Rencana kali ini diputuskan untuk ditunda."},
{kat:"Kata Kerja", kanji:"見直す", kana:"みなおす", romaji:"minaosu", arti:"meninjau ulang", contohJp:"予算を見直す必要がある。", contohRomaji:"Yosan o minaosu hitsuyou ga aru.", contohId:"Perlu meninjau ulang anggaran."},
{kat:"Kata Kerja", kanji:"取り組む", kana:"とりくむ", romaji:"torikumu", arti:"bergelut, menangani", contohJp:"環境問題に真剣に取り組んでいる。", contohRomaji:"Kankyou mondai ni shinken ni torikunde iru.", contohId:"Serius menangani masalah lingkungan."},
{kat:"Kata Kerja", kanji:"取り上げる", kana:"とりあげる", romaji:"toriageru", arti:"mengangkat (topik)", contohJp:"番組でその事件が取り上げられた。", contohRomaji:"Bangumi de sono jiken ga toriagerareta.", contohId:"Kasus itu diangkat dalam acara TV."},
{kat:"Kata Kerja", kanji:"取り消す", kana:"とりけす", romaji:"torikesu", arti:"membatalkan", contohJp:"予約を取り消した。", contohRomaji:"Yoyaku o torikeshita.", contohId:"Saya membatalkan reservasi."},
{kat:"Kata Kerja", kanji:"取り扱う", kana:"とりあつかう", romaji:"toriatsukau", arti:"menangani", contohJp:"この店は輸入品を取り扱っている。", contohRomaji:"Kono mise wa yunyuuhin o toriatsukatte iru.", contohId:"Toko ini menangani barang impor."},
{kat:"Kata Kerja", kanji:"見落とす", kana:"みおとす", romaji:"miotosu", arti:"terlewat melihat", contohJp:"大事な点を見落としていた。", contohRomaji:"Daiji na ten o miotoshite ita.", contohId:"Saya melewatkan poin penting."},
{kat:"Kata Kerja", kanji:"心得る", kana:"こころえる", romaji:"kokoroeru", arti:"memahami, menguasai", contohJp:"仕事の基本を心得ている。", contohRomaji:"Shigoto no kihon o kokoroete iru.", contohId:"Dia menguasai dasar-dasar pekerjaan."},
{kat:"Kata Kerja", kanji:"兼ねる", kana:"かねる", romaji:"kaneru", arti:"merangkap", contohJp:"彼は監督と選手を兼ねている。", contohRomaji:"Kare wa kantoku to senshu o kanete iru.", contohId:"Dia merangkap sebagai pelatih dan pemain."},
{kat:"Kata Kerja", kanji:"携わる", kana:"たずさわる", romaji:"tazusawaru", arti:"terlibat dalam", contohJp:"長年この研究に携わってきた。", contohRomaji:"Naganen kono kenkyuu ni tazusawatte kita.", contohId:"Saya sudah lama terlibat dalam penelitian ini."},
{kat:"Kata Kerja", kanji:"伴う", kana:"ともなう", romaji:"tomonau", arti:"disertai", contohJp:"この工事には危険が伴う。", contohRomaji:"Kono kouji ni wa kiken ga tomonau.", contohId:"Proyek konstruksi ini disertai bahaya."},
{kat:"Kata Kerja", kanji:"相次ぐ", kana:"あいつぐ", romaji:"aitsugu", arti:"beruntun, berturut-turut", contohJp:"最近、事故が相次いでいる。", contohRomaji:"Saikin, jiko ga aitsuide iru.", contohId:"Belakangan ini, kecelakaan terjadi beruntun."},
{kat:"Kata Kerja", kanji:"極める", kana:"きわめる", romaji:"kiwameru", arti:"mencapai puncak", contohJp:"彼はその道を極めた職人だ。", contohRomaji:"Kare wa sono michi o kiwameta shokunin da.", contohId:"Dia pengrajin yang sudah mencapai puncak keahliannya."},
{kat:"Kata Kerja", kanji:"巡る", kana:"めぐる", romaji:"meguru", arti:"berkeliling, terkait dengan", contohJp:"その計画を巡って議論が続いている。", contohRomaji:"Sono keikaku o megutte giron ga tsuzuite iru.", contohId:"Diskusi terkait rencana itu terus berlanjut."},
{kat:"Kata Kerja", kanji:"遂げる", kana:"とげる", romaji:"togeru", arti:"mencapai (tujuan)", contohJp:"目標を遂げるまで諦めない。", contohRomaji:"Mokuhyou o togeru made akiramenai.", contohId:"Tidak akan menyerah sampai mencapai tujuan."},
{kat:"Kata Kerja", kanji:"果たす", kana:"はたす", romaji:"hatasu", arti:"memenuhi (peran)", contohJp:"リーダーとしての役割を果たす。", contohRomaji:"Riidaa to shite no yakuwari o hatasu.", contohId:"Memenuhi peran sebagai pemimpin."},
{kat:"Kata Kerja", kanji:"補う", kana:"おぎなう", romaji:"oginau", arti:"melengkapi kekurangan", contohJp:"不足分を補うために働いている。", contohRomaji:"Fusokubun o oginau tame ni hataraite iru.", contohId:"Bekerja untuk menutupi kekurangan."},
{kat:"Kata Kerja", kanji:"妨げる", kana:"さまたげる", romaji:"samatageru", arti:"menghalangi", contohJp:"騒音が集中を妨げる。", contohRomaji:"Souon ga shuuchuu o samatageru.", contohId:"Kebisingan menghalangi konsentrasi."},
{kat:"Kata Kerja", kanji:"損なう", kana:"そこなう", romaji:"sokonau", arti:"merusak, mencederai", contohJp:"健康を損なわないよう注意する。", contohRomaji:"Kenkou o sokonawanai you chuui suru.", contohId:"Berhati-hati agar tidak merusak kesehatan."},
{kat:"Kata Kerja", kanji:"響く", kana:"ひびく", romaji:"hibiku", arti:"bergema, berdampak", contohJp:"彼の言葉が心に響いた。", contohRomaji:"Kare no kotoba ga kokoro ni hibiita.", contohId:"Kata-katanya berdampak di hati saya."},
{kat:"Kata Kerja", kanji:"及ぼす", kana:"およぼす", romaji:"oyobosu", arti:"memberi dampak", contohJp:"経済に影響を及ぼす。", contohRomaji:"Keizai ni eikyou o oyobosu.", contohId:"Memberi dampak pada ekonomi."},
{kat:"Kata Kerja", kanji:"及ぶ", kana:"およぶ", romaji:"oyobu", arti:"mencapai, meluas sampai", contohJp:"被害は広範囲に及んだ。", contohRomaji:"Higai wa kouhan'i ni oyonda.", contohId:"Kerugiannya meluas hingga area yang sangat luas."},
{kat:"Kata Kerja", kanji:"費やす", kana:"ついやす", romaji:"tsuiyasu", arti:"menghabiskan (waktu/biaya)", contohJp:"研究に多くの時間を費やした。", contohRomaji:"Kenkyuu ni ooku no jikan o tsuiyashita.", contohId:"Menghabiskan banyak waktu untuk penelitian."},
{kat:"Kata Kerja", kanji:"目指す", kana:"めざす", romaji:"mezasu", arti:"menargetkan, bercita-cita", contohJp:"世界一を目指している。", contohRomaji:"Sekai-ichi o mezashite iru.", contohId:"Menargetkan menjadi nomor satu di dunia."},
{kat:"Kata Kerja", kanji:"志す", kana:"こころざす", romaji:"kokorozasu", arti:"bercita-cita", contohJp:"医者になることを志した。", contohRomaji:"Isha ni naru koto o kokorozashita.", contohId:"Bercita-cita menjadi dokter."},
{kat:"Kata Kerja", kanji:"促す", kana:"うながす", romaji:"unagasu", arti:"mendorong, mengimbau", contohJp:"早めの対策を促す。", contohRomaji:"Hayame no taisaku o unagasu.", contohId:"Mengimbau langkah antisipasi lebih awal."},
{kat:"Kata Kerja", kanji:"導く", kana:"みちびく", romaji:"michibiku", arti:"membimbing, mengarahkan", contohJp:"生徒を正しい方向へ導く。", contohRomaji:"Seito o tadashii houkou e michibiku.", contohId:"Membimbing murid ke arah yang benar."},
{kat:"Kata Kerja", kanji:"妥協する", kana:"だきょうする", romaji:"dakyousuru", arti:"berkompromi", contohJp:"お互いに妥協することが大切だ。", contohRomaji:"Otagai ni dakyou suru koto ga taisetsu da.", contohId:"Penting untuk saling berkompromi."},
{kat:"Kata Kerja", kanji:"折り合う", kana:"おりあう", romaji:"oriau", arti:"mencapai kesepakatan", contohJp:"価格について折り合った。", contohRomaji:"Kakaku ni tsuite oriatta.", contohId:"Mencapai kesepakatan soal harga."},
{kat:"Kata Kerja", kanji:"見極める", kana:"みきわめる", romaji:"mikiwameru", arti:"menilai dengan cermat", contohJp:"状況を見極めてから決める。", contohRomaji:"Joukyou o mikiwamete kara kimeru.", contohId:"Memutuskan setelah menilai situasi dengan cermat."},
{kat:"Kata Kerja", kanji:"見合わせる", kana:"みあわせる", romaji:"miawaseru", arti:"menunda, menangguhkan", contohJp:"出発を見合わせることにした。", contohRomaji:"Shuppatsu o miawaseru koto ni shita.", contohId:"Memutuskan untuk menunda keberangkatan."},
{kat:"Kata Kerja", kanji:"差し支える", kana:"さしつかえる", romaji:"sashitsukaeru", arti:"mengganggu, menghalangi", contohJp:"仕事に差し支えない範囲で手伝う。", contohRomaji:"Shigoto ni sashitsukaenai han'i de tetsudau.", contohId:"Membantu sejauh tidak mengganggu pekerjaan."},
{kat:"Kata Kerja", kanji:"配慮する", kana:"はいりょする", romaji:"hairyosuru", arti:"mempertimbangkan", contohJp:"周りの人に配慮して行動する。", contohRomaji:"Mawari no hito ni hairyo shite koudou suru.", contohId:"Bertindak dengan mempertimbangkan orang sekitar."},
{kat:"Kata Kerja", kanji:"踏まえる", kana:"ふまえる", romaji:"fumaeru", arti:"berdasarkan pada", contohJp:"前回の結果を踏まえて計画を立てる。", contohRomaji:"Zenkai no kekka o fumaete keikaku o tateru.", contohId:"Membuat rencana berdasarkan hasil sebelumnya."},
{kat:"Kata Kerja", kanji:"発揮する", kana:"はっきする", romaji:"hakkisuru", arti:"menunjukkan (kemampuan)", contohJp:"本番で実力を発揮した。", contohRomaji:"Honban de jitsuryoku o hakki shita.", contohId:"Menunjukkan kemampuan sesungguhnya saat momen penting."},
{kat:"Kata Kerja", kanji:"呼びかける", kana:"よびかける", romaji:"yobikakeru", arti:"menyerukan", contohJp:"節電を呼びかけた。", contohRomaji:"Setsuden o yobikaketa.", contohId:"Menyerukan penghematan listrik."},
{kat:"Kata Kerja", kanji:"講じる", kana:"こうじる", romaji:"koujiru", arti:"mengambil (langkah/tindakan)", contohJp:"対策を講じる必要がある。", contohRomaji:"Taisaku o koujiru hitsuyou ga aru.", contohId:"Perlu mengambil langkah antisipasi."},

// ================= 2. KATA SIFAT -I =================
{kat:"Kata Sifat -i", kanji:"著しい", kana:"いちじるしい", romaji:"ichijirushii", arti:"mencolok, nyata", contohJp:"技術は著しく進歩した。", contohRomaji:"Gijutsu wa ichijirushiku shinpo shita.", contohId:"Teknologi berkembang secara mencolok."},
{kat:"Kata Sifat -i", kanji:"甚だしい", kana:"はなはだしい", romaji:"hanahadashii", arti:"sangat, luar biasa (negatif)", contohJp:"それは甚だしい誤解だ。", contohRomaji:"Sore wa hanahadashii gokai da.", contohId:"Itu kesalahpahaman yang luar biasa."},
{kat:"Kata Sifat -i", kanji:"くどい", kana:"くどい", romaji:"kudoi", arti:"bertele-tele, berlebihan", contohJp:"この味付けはくどい。", contohRomaji:"Kono ajitsuke wa kudoi.", contohId:"Bumbu masakan ini terlalu kuat/berlebihan."},
{kat:"Kata Sifat -i", kanji:"しつこい", kana:"しつこい", romaji:"shitsukoi", arti:"gigih, rewel, terus-menerus", contohJp:"しつこく誘われて断れなかった。", contohRomaji:"Shitsukoku sasowarete kotowarenakatta.", contohId:"Diajak terus-menerus sampai tidak bisa menolak."},
{kat:"Kata Sifat -i", kanji:"ややこしい", kana:"ややこしい", romaji:"yayakoshii", arti:"rumit, membingungkan", contohJp:"手続きがややこしい。", contohRomaji:"Tetsuzuki ga yayakoshii.", contohId:"Prosedurnya rumit."},
{kat:"Kata Sifat -i", kanji:"紛らわしい", kana:"まぎらわしい", romaji:"magirawashii", arti:"membingungkan (mirip)", contohJp:"似た名前で紛らわしい。", contohRomaji:"Nita namae de magirawashii.", contohId:"Namanya mirip jadi membingungkan."},
{kat:"Kata Sifat -i", kanji:"望ましい", kana:"のぞましい", romaji:"nozomashii", arti:"diinginkan, ideal", contohJp:"早めの対応が望ましい。", contohRomaji:"Hayame no taiou ga nozomashii.", contohId:"Respon lebih awal itu ideal."},
{kat:"Kata Sifat -i", kanji:"相応しい", kana:"ふさわしい", romaji:"fusawashii", arti:"cocok, pantas", contohJp:"彼はリーダーに相応しい。", contohRomaji:"Kare wa riidaa ni fusawashii.", contohId:"Dia pantas menjadi pemimpin."},
{kat:"Kata Sifat -i", kanji:"甘い", kana:"あまい", romaji:"amai", arti:"manis, lunak (penilaian)", contohJp:"彼は自分に甘い。", contohRomaji:"Kare wa jibun ni amai.", contohId:"Dia lunak terhadap dirinya sendiri."},
{kat:"Kata Sifat -i", kanji:"険しい", kana:"けわしい", romaji:"kewashii", arti:"curam, tegang (wajah)", contohJp:"険しい表情をしていた。", contohRomaji:"Kewashii hyoujou o shite ita.", contohId:"Dia memasang ekspresi tegang."},
{kat:"Kata Sifat -i", kanji:"卑しい", kana:"いやしい", romaji:"iyashii", arti:"hina, rendah", contohJp:"卑しい考えを持つべきではない。", contohRomaji:"Iyashii kangae o motsu beki dewa nai.", contohId:"Tidak seharusnya memiliki pikiran yang hina."},
{kat:"Kata Sifat -i", kanji:"賢い", kana:"かしこい", romaji:"kashikoi", arti:"cerdas", contohJp:"賢い選択をした。", contohRomaji:"Kashikoi sentaku o shita.", contohId:"Membuat pilihan yang cerdas."},
{kat:"Kata Sifat -i", kanji:"悔しい", kana:"くやしい", romaji:"kuyashii", arti:"menyesal, kesal", contohJp:"負けて悔しい思いをした。", contohRomaji:"Makete kuyashii omoi o shita.", contohId:"Merasa kesal karena kalah."},
{kat:"Kata Sifat -i", kanji:"切ない", kana:"せつない", romaji:"setsunai", arti:"pilu, sedih menyayat", contohJp:"切ない気持ちになった。", contohRomaji:"Setsunai kimochi ni natta.", contohId:"Perasaan menjadi pilu."},

// ================= 3. KATA SIFAT -NA =================
{kat:"Kata Sifat -na", kanji:"曖昧", kana:"あいまい", romaji:"aimai", arti:"ambigu", contohJp:"曖昧な返事をされた。", contohRomaji:"Aimai na henji o sareta.", contohId:"Saya diberi jawaban yang ambigu."},
{kat:"Kata Sifat -na", kanji:"明確", kana:"めいかく", romaji:"meikaku", arti:"jelas, tegas", contohJp:"明確な基準が必要だ。", contohRomaji:"Meikaku na kijun ga hitsuyou da.", contohId:"Perlu standar yang jelas."},
{kat:"Kata Sifat -na", kanji:"円滑", kana:"えんかつ", romaji:"enkatsu", arti:"lancar, mulus", contohJp:"会議は円滑に進んだ。", contohRomaji:"Kaigi wa enkatsu ni susunda.", contohId:"Rapatnya berjalan lancar."},
{kat:"Kata Sifat -na", kanji:"慎重", kana:"しんちょう", romaji:"shinchou", arti:"hati-hati", contohJp:"慎重に判断すべきだ。", contohRomaji:"Shinchou ni handan subeki da.", contohId:"Harus mengambil keputusan dengan hati-hati."},
{kat:"Kata Sifat -na", kanji:"大胆", kana:"だいたん", romaji:"daitan", arti:"berani, nekat", contohJp:"大胆な改革を行った。", contohRomaji:"Daitan na kaikaku o okonatta.", contohId:"Melakukan reformasi yang berani."},
{kat:"Kata Sifat -na", kanji:"柔軟", kana:"じゅうなん", romaji:"juunan", arti:"fleksibel, luwes", contohJp:"柔軟に対応することが大切だ。", contohRomaji:"Juunan ni taiou suru koto ga taisetsu da.", contohId:"Penting untuk menanggapi secara fleksibel."},
{kat:"Kata Sifat -na", kanji:"頑固", kana:"がんこ", romaji:"ganko", arti:"keras kepala", contohJp:"祖父は頑固な性格だ。", contohRomaji:"Sofu wa ganko na seikaku da.", contohId:"Kakek berkepribadian keras kepala."},
{kat:"Kata Sifat -na", kanji:"率直", kana:"そっちょく", romaji:"socchoku", arti:"terus terang", contohJp:"率直な意見を聞きたい。", contohRomaji:"Socchoku na iken o kikitai.", contohId:"Saya ingin mendengar pendapat yang terus terang."},
{kat:"Kata Sifat -na", kanji:"深刻", kana:"しんこく", romaji:"shinkoku", arti:"serius (masalah)", contohJp:"深刻な問題になっている。", contohRomaji:"Shinkoku na mondai ni natte iru.", contohId:"Sudah menjadi masalah yang serius."},
{kat:"Kata Sifat -na", kanji:"悲惨", kana:"ひさん", romaji:"hisan", arti:"tragis, menyedihkan", contohJp:"悲惨な事故だった。", contohRomaji:"Hisan na jiko datta.", contohId:"Itu kecelakaan yang tragis."},
{kat:"Kata Sifat -na", kanji:"贅沢", kana:"ぜいたく", romaji:"zeitaku", arti:"mewah, boros", contohJp:"贅沢な暮らしをしている。", contohRomaji:"Zeitaku na kurashi o shite iru.", contohId:"Menjalani kehidupan yang mewah."},
{kat:"Kata Sifat -na", kanji:"地味", kana:"じみ", romaji:"jimi", arti:"sederhana, kalem", contohJp:"地味な服装を好む。", contohRomaji:"Jimi na fukusou o konomu.", contohId:"Menyukai pakaian yang sederhana."},
{kat:"Kata Sifat -na", kanji:"派手", kana:"はで", romaji:"hade", arti:"mencolok, flamboyan", contohJp:"派手な色のドレスを着た。", contohRomaji:"Hade na iro no doresu o kita.", contohId:"Memakai gaun berwarna mencolok."},
{kat:"Kata Sifat -na", kanji:"気軽", kana:"きがる", romaji:"kigaru", arti:"santai, tanpa beban", contohJp:"気軽に相談してください。", contohRomaji:"Kigaru ni soudan shite kudasai.", contohId:"Silakan berkonsultasi dengan santai."},
{kat:"Kata Sifat -na", kanji:"面倒", kana:"めんどう", romaji:"mendou", arti:"merepotkan", contohJp:"手続きが面倒だ。", contohRomaji:"Tetsuzuki ga mendou da.", contohId:"Prosedurnya merepotkan."},
{kat:"Kata Sifat -na", kanji:"微妙", kana:"びみょう", romaji:"bimyou", arti:"halus, agak sulit dijelaskan", contohJp:"微妙な違いがある。", contohRomaji:"Bimyou na chigai ga aru.", contohId:"Ada perbedaan yang halus."},
{kat:"Kata Sifat -na", kanji:"濃厚", kana:"のうこう", romaji:"noukou", arti:"pekat, kental", contohJp:"敗色が濃厚になった。", contohRomaji:"Haishoku ga noukou ni natta.", contohId:"Tanda-tanda kekalahan semakin kental."},
{kat:"Kata Sifat -na", kanji:"強烈", kana:"きょうれつ", romaji:"kyouretsu", arti:"kuat, intens", contohJp:"強烈な印象を受けた。", contohRomaji:"Kyouretsu na inshou o uketa.", contohId:"Mendapat kesan yang kuat."},
{kat:"Kata Sifat -na", kanji:"大幅", kana:"おおはば", romaji:"oohaba", arti:"besar-besaran (perubahan)", contohJp:"価格が大幅に上がった。", contohRomaji:"Kakaku ga oohaba ni agatta.", contohId:"Harga naik secara besar-besaran."},
{kat:"Kata Sifat -na", kanji:"一律", kana:"いちりつ", romaji:"ichiritsu", arti:"seragam, sama rata", contohJp:"一律に料金を設定する。", contohRomaji:"Ichiritsu ni ryoukin o settei suru.", contohId:"Menetapkan biaya secara seragam."},

// ================= 4. KATA BENDA: BISNIS & EKONOMI =================
{kat:"Bisnis & Ekonomi", kanji:"業績", kana:"ぎょうせき", romaji:"gyouseki", arti:"kinerja usaha", contohJp:"今年の業績は好調だ。", contohRomaji:"Kotoshi no gyouseki wa kouchou da.", contohId:"Kinerja usaha tahun ini bagus."},
{kat:"Bisnis & Ekonomi", kanji:"収益", kana:"しゅうえき", romaji:"shuueki", arti:"laba, pendapatan", contohJp:"収益が前年より増えた。", contohRomaji:"Shuueki ga zennen yori fueta.", contohId:"Laba meningkat dibanding tahun lalu."},
{kat:"Bisnis & Ekonomi", kanji:"赤字", kana:"あかじ", romaji:"akaji", arti:"defisit", contohJp:"会社は赤字が続いている。", contohRomaji:"Kaisha wa akaji ga tsuzuite iru.", contohId:"Perusahaan terus mengalami defisit."},
{kat:"Bisnis & Ekonomi", kanji:"黒字", kana:"くろじ", romaji:"kuroji", arti:"surplus, untung", contohJp:"ようやく黒字になった。", contohRomaji:"Youyaku kuroji ni natta.", contohId:"Akhirnya menjadi surplus."},
{kat:"Bisnis & Ekonomi", kanji:"融資", kana:"ゆうし", romaji:"yuushi", arti:"pembiayaan, pinjaman", contohJp:"銀行から融資を受けた。", contohRomaji:"Ginkou kara yuushi o uketa.", contohId:"Menerima pembiayaan dari bank."},
{kat:"Bisnis & Ekonomi", kanji:"出資", kana:"しゅっし", romaji:"shusshi", arti:"investasi modal", contohJp:"新会社に出資した。", contohRomaji:"Shin kaisha ni shusshi shita.", contohId:"Berinvestasi modal di perusahaan baru."},
{kat:"Bisnis & Ekonomi", kanji:"需要", kana:"じゅよう", romaji:"juyou", arti:"permintaan", contohJp:"需要が急激に伸びた。", contohRomaji:"Juyou ga kyuugeki ni nobita.", contohId:"Permintaan meningkat drastis."},
{kat:"Bisnis & Ekonomi", kanji:"供給", kana:"きょうきゅう", romaji:"kyoukyuu", arti:"penawaran, pasokan", contohJp:"供給が需要に追いつかない。", contohRomaji:"Kyoukyuu ga juyou ni oitsukanai.", contohId:"Pasokan tidak bisa mengejar permintaan."},
{kat:"Bisnis & Ekonomi", kanji:"競争力", kana:"きょうそうりょく", romaji:"kyousouryoku", arti:"daya saing", contohJp:"競争力を高める必要がある。", contohRomaji:"Kyousouryoku o takameru hitsuyou ga aru.", contohId:"Perlu meningkatkan daya saing."},
{kat:"Bisnis & Ekonomi", kanji:"取引", kana:"とりひき", romaji:"torihiki", arti:"transaksi", contohJp:"新しい会社と取引を始めた。", contohRomaji:"Atarashii kaisha to torihiki o hajimeta.", contohId:"Memulai transaksi dengan perusahaan baru."},
{kat:"Bisnis & Ekonomi", kanji:"交渉", kana:"こうしょう", romaji:"koushou", arti:"negosiasi", contohJp:"価格の交渉をしている。", contohRomaji:"Kakaku no koushou o shite iru.", contohId:"Sedang bernegosiasi soal harga."},
{kat:"Bisnis & Ekonomi", kanji:"提携", kana:"ていけい", romaji:"teikei", arti:"kerja sama, aliansi", contohJp:"他社と業務提携を結んだ。", contohRomaji:"Tasha to gyoumu teikei o musunda.", contohId:"Menjalin aliansi bisnis dengan perusahaan lain."},
{kat:"Bisnis & Ekonomi", kanji:"合併", kana:"がっぺい", romaji:"gappei", arti:"merger, penggabungan", contohJp:"二つの会社が合併した。", contohRomaji:"Futatsu no kaisha ga gappei shita.", contohId:"Dua perusahaan melakukan merger."},
{kat:"Bisnis & Ekonomi", kanji:"買収", kana:"ばいしゅう", romaji:"baishuu", arti:"akuisisi", contohJp:"大企業に買収された。", contohRomaji:"Daikigyou ni baishuu sareta.", contohId:"Diakuisisi oleh perusahaan besar."},
{kat:"Bisnis & Ekonomi", kanji:"倒産", kana:"とうさん", romaji:"tousan", arti:"bangkrut", contohJp:"その会社は倒産した。", contohRomaji:"Sono kaisha wa tousan shita.", contohId:"Perusahaan itu bangkrut."},
{kat:"Bisnis & Ekonomi", kanji:"生産性", kana:"せいさんせい", romaji:"seisansei", arti:"produktivitas", contohJp:"生産性を向上させたい。", contohRomaji:"Seisansei o koujou sasetai.", contohId:"Ingin meningkatkan produktivitas."},
{kat:"Bisnis & Ekonomi", kanji:"効率", kana:"こうりつ", romaji:"kouritsu", arti:"efisiensi", contohJp:"作業の効率を上げる。", contohRomaji:"Sagyou no kouritsu o ageru.", contohId:"Meningkatkan efisiensi pekerjaan."},
{kat:"Bisnis & Ekonomi", kanji:"消費者", kana:"しょうひしゃ", romaji:"shouhisha", arti:"konsumen", contohJp:"消費者のニーズに応える。", contohRomaji:"Shouhisha no niizu ni kotaeru.", contohId:"Memenuhi kebutuhan konsumen."},
{kat:"Bisnis & Ekonomi", kanji:"為替", kana:"かわせ", romaji:"kawase", arti:"nilai tukar", contohJp:"為替の変動が激しい。", contohRomaji:"Kawase no hendou ga hageshii.", contohId:"Fluktuasi nilai tukar sangat tajam."},
{kat:"Bisnis & Ekonomi", kanji:"株価", kana:"かぶか", romaji:"kabuka", arti:"harga saham", contohJp:"株価が急落した。", contohRomaji:"Kabuka ga kyuuraku shita.", contohId:"Harga saham anjlok tajam."},
{kat:"Bisnis & Ekonomi", kanji:"投資", kana:"とうし", romaji:"toushi", arti:"investasi", contohJp:"不動産に投資している。", contohRomaji:"Fudousan ni toushi shite iru.", contohId:"Berinvestasi di properti."},
{kat:"Bisnis & Ekonomi", kanji:"負担", kana:"ふたん", romaji:"futan", arti:"beban (biaya)", contohJp:"費用の負担が大きい。", contohRomaji:"Hiyou no futan ga ookii.", contohId:"Beban biayanya besar."},
{kat:"Bisnis & Ekonomi", kanji:"費用対効果", kana:"ひようたいこうか", romaji:"hiyou-tai-kouka", arti:"efektivitas biaya", contohJp:"費用対効果を考えて決めた。", contohRomaji:"Hiyou-tai-kouka o kangaete kimeta.", contohId:"Memutuskan dengan mempertimbangkan efektivitas biaya."},

// ================= 5. KATA BENDA: SOSIAL & POLITIK =================
{kat:"Sosial & Politik", kanji:"世論", kana:"せろん", romaji:"seron", arti:"opini publik", contohJp:"世論の反応が気になる。", contohRomaji:"Seron no hannou ga ki ni naru.", contohId:"Khawatir dengan reaksi opini publik."},
{kat:"Sosial & Politik", kanji:"選挙", kana:"せんきょ", romaji:"senkyo", arti:"pemilu", contohJp:"来月選挙が行われる。", contohRomaji:"Raigetsu senkyo ga okonawareru.", contohId:"Pemilu akan diadakan bulan depan."},
{kat:"Sosial & Politik", kanji:"議論", kana:"ぎろん", romaji:"giron", arti:"diskusi, perdebatan", contohJp:"活発な議論が交わされた。", contohRomaji:"Kappatsu na giron ga kawasareta.", contohId:"Terjadi diskusi yang aktif."},
{kat:"Sosial & Politik", kanji:"対立", kana:"たいりつ", romaji:"tairitsu", arti:"konflik, pertentangan", contohJp:"意見の対立が生じた。", contohRomaji:"Iken no tairitsu ga shoujita.", contohId:"Muncul pertentangan pendapat."},
{kat:"Sosial & Politik", kanji:"合意", kana:"ごうい", romaji:"goui", arti:"kesepakatan", contohJp:"両国は合意に達した。", contohRomaji:"Ryoukoku wa goui ni tasshita.", contohId:"Kedua negara mencapai kesepakatan."},
{kat:"Sosial & Politik", kanji:"妥協", kana:"だきょう", romaji:"dakyou", arti:"kompromi", contohJp:"妥協の余地がない。", contohRomaji:"Dakyou no yochi ga nai.", contohId:"Tidak ada ruang untuk kompromi."},
{kat:"Sosial & Politik", kanji:"規制", kana:"きせい", romaji:"kisei", arti:"regulasi", contohJp:"新しい規制が導入された。", contohRomaji:"Atarashii kisei ga dounyuu sareta.", contohId:"Regulasi baru diperkenalkan."},
{kat:"Sosial & Politik", kanji:"制裁", kana:"せいさい", romaji:"seisai", arti:"sanksi", contohJp:"経済制裁が科された。", contohRomaji:"Keizai seisai ga kasareta.", contohId:"Sanksi ekonomi dijatuhkan."},
{kat:"Sosial & Politik", kanji:"格差", kana:"かくさ", romaji:"kakusa", arti:"kesenjangan", contohJp:"所得格差が広がっている。", contohRomaji:"Shotoku kakusa ga hirogatte iru.", contohId:"Kesenjangan pendapatan semakin melebar."},
{kat:"Sosial & Politik", kanji:"貧困", kana:"ひんこん", romaji:"hinkon", arti:"kemiskinan", contohJp:"貧困問題を解決したい。", contohRomaji:"Hinkon mondai o kaiketsu shitai.", contohId:"Ingin menyelesaikan masalah kemiskinan."},
{kat:"Sosial & Politik", kanji:"福祉", kana:"ふくし", romaji:"fukushi", arti:"kesejahteraan", contohJp:"福祉制度を充実させる。", contohRomaji:"Fukushi seido o juujitsu saseru.", contohId:"Menyempurnakan sistem kesejahteraan."},
{kat:"Sosial & Politik", kanji:"介護", kana:"かいご", romaji:"kaigo", arti:"perawatan lansia/disabilitas", contohJp:"祖母の介護をしている。", contohRomaji:"Sobo no kaigo o shite iru.", contohId:"Merawat nenek."},
{kat:"Sosial & Politik", kanji:"少子高齢化", kana:"しょうしこうれいか", romaji:"shoushi koureika", arti:"penurunan kelahiran & penuaan populasi", contohJp:"少子高齢化が社会問題になっている。", contohRomaji:"Shoushi koureika ga shakai mondai ni natte iru.", contohId:"Penurunan kelahiran & penuaan populasi menjadi masalah sosial."},
{kat:"Sosial & Politik", kanji:"移民", kana:"いみん", romaji:"imin", arti:"imigran", contohJp:"移民政策について議論する。", contohRomaji:"Imin seisaku ni tsuite giron suru.", contohId:"Mendiskusikan kebijakan imigran."},
{kat:"Sosial & Politik", kanji:"難民", kana:"なんみん", romaji:"nanmin", arti:"pengungsi", contohJp:"難民を支援する団体がある。", contohRomaji:"Nanmin o shien suru dantai ga aru.", contohId:"Ada organisasi yang mendukung pengungsi."},
{kat:"Sosial & Politik", kanji:"人権", kana:"じんけん", romaji:"jinken", arti:"HAM", contohJp:"人権を尊重すべきだ。", contohRomaji:"Jinken o sonchou subeki da.", contohId:"HAM harus dihormati."},
{kat:"Sosial & Politik", kanji:"偏見", kana:"へんけん", romaji:"henken", arti:"prasangka", contohJp:"偏見を持たないようにする。", contohRomaji:"Henken o motanai you ni suru.", contohId:"Berusaha tidak memiliki prasangka."},
{kat:"Sosial & Politik", kanji:"風潮", kana:"ふうちょう", romaji:"fuuchou", arti:"tren sosial, arus zaman", contohJp:"最近の風潮を反映している。", contohRomaji:"Saikin no fuuchou o hanei shite iru.", contohId:"Mencerminkan tren sosial belakangan ini."},
{kat:"Sosial & Politik", kanji:"世代", kana:"せだい", romaji:"sedai", arti:"generasi", contohJp:"世代によって考え方が違う。", contohRomaji:"Sedai ni yotte kangaekata ga chigau.", contohId:"Cara berpikir berbeda menurut generasi."},
{kat:"Sosial & Politik", kanji:"価値観", kana:"かちかん", romaji:"kachikan", arti:"pandangan nilai", contohJp:"価値観の違いを認め合う。", contohRomaji:"Kachikan no chigai o mitomeau.", contohId:"Saling mengakui perbedaan pandangan nilai."},
{kat:"Sosial & Politik", kanji:"倫理", kana:"りんり", romaji:"rinri", arti:"etika", contohJp:"企業倫理が問われている。", contohRomaji:"Kigyou rinri ga towarete iru.", contohId:"Etika perusahaan sedang dipertanyakan."},
{kat:"Sosial & Politik", kanji:"責任感", kana:"せきにんかん", romaji:"sekininkan", arti:"rasa tanggung jawab", contohJp:"強い責任感を持っている。", contohRomaji:"Tsuyoi sekininkan o motte iru.", contohId:"Memiliki rasa tanggung jawab yang kuat."},
{kat:"Sosial & Politik", kanji:"意識調査", kana:"いしきちょうさ", romaji:"ishiki chousa", arti:"survei kesadaran", contohJp:"意識調査の結果が発表された。", contohRomaji:"Ishiki chousa no kekka ga happyou sareta.", contohId:"Hasil survei kesadaran diumumkan."},
{kat:"Sosial & Politik", kanji:"世間", kana:"せけん", romaji:"seken", arti:"masyarakat umum", contohJp:"世間の目が気になる。", contohRomaji:"Seken no me ga ki ni naru.", contohId:"Khawatir dengan pandangan masyarakat umum."},

// ================= 6. KATA KETERANGAN =================
{kat:"Kata Keterangan", kanji:"あくまで", kana:"あくまで", romaji:"akumade", arti:"sampai akhir, tetap (pendirian)", contohJp:"これはあくまで私の意見です。", contohRomaji:"Kore wa akumade watashi no iken desu.", contohId:"Ini tetap hanya pendapat saya pribadi."},
{kat:"Kata Keterangan", kanji:"あいにく", kana:"あいにく", romaji:"ainiku", arti:"sayangnya (kebetulan buruk)", contohJp:"あいにく、その日は都合が悪い。", contohRomaji:"Ainiku, sono hi wa tsugou ga warui.", contohId:"Sayangnya, hari itu saya tidak bisa."},
{kat:"Kata Keterangan", kanji:"いっそ", kana:"いっそ", romaji:"isso", arti:"lebih baik (drastis)", contohJp:"いっそ全部やめてしまおうか。", contohRomaji:"Isso zenbu yamete shimaou ka.", contohId:"Lebih baik berhenti semuanya saja ya."},
{kat:"Kata Keterangan", kanji:"いわば", kana:"いわば", romaji:"iwaba", arti:"bisa dikatakan", contohJp:"彼はいわば私の恩師だ。", contohRomaji:"Kare wa iwaba watashi no onshi da.", contohId:"Dia bisa dikatakan guru berjasa bagi saya."},
{kat:"Kata Keterangan", kanji:"せめて", kana:"せめて", romaji:"semete", arti:"setidaknya", contohJp:"せめて電話ぐらいしてほしい。", contohRomaji:"Semete denwa gurai shite hoshii.", contohId:"Setidaknya saya ingin ditelepon."},
{kat:"Kata Keterangan", kanji:"なにしろ", kana:"なにしろ", romaji:"nanishiro", arti:"bagaimanapun juga", contohJp:"なにしろ初めてのことなので緊張する。", contohRomaji:"Nanishiro hajimete no koto na node kinchou suru.", contohId:"Bagaimanapun juga ini pertama kali jadi gugup."},
{kat:"Kata Keterangan", kanji:"まさか", kana:"まさか", romaji:"masaka", arti:"masa sih, tidak mungkin", contohJp:"まさか彼が来るとは思わなかった。", contohRomaji:"Masaka kare ga kuru to wa omowanakatta.", contohId:"Tidak menyangka sama sekali dia akan datang."},
{kat:"Kata Keterangan", kanji:"もはや", kana:"もはや", romaji:"mohaya", arti:"sudah tidak lagi", contohJp:"もはや後戻りはできない。", contohRomaji:"Mohaya atomodori wa dekinai.", contohId:"Sudah tidak bisa kembali lagi."},
{kat:"Kata Keterangan", kanji:"わずかに", kana:"わずかに", romaji:"wazuka ni", arti:"sedikit sekali", contohJp:"わずかに差が出た。", contohRomaji:"Wazuka ni sa ga deta.", contohId:"Muncul perbedaan yang sedikit sekali."},
{kat:"Kata Keterangan", kanji:"おのずと", kana:"おのずと", romaji:"onozuto", arti:"dengan sendirinya", contohJp:"努力すればおのずと結果が出る。", contohRomaji:"Doryoku sureba onozuto kekka ga deru.", contohId:"Kalau berusaha, hasilnya akan keluar dengan sendirinya."},
{kat:"Kata Keterangan", kanji:"あらかじめ", kana:"あらかじめ", romaji:"arakajime", arti:"sebelumnya, lebih dulu", contohJp:"あらかじめ連絡してください。", contohRomaji:"Arakajime renraku shite kudasai.", contohId:"Tolong hubungi terlebih dahulu."},
{kat:"Kata Keterangan", kanji:"いちいち", kana:"いちいち", romaji:"ichiichi", arti:"satu per satu (dengan jengkel)", contohJp:"いちいち文句を言わないで。", contohRomaji:"Ichiichi monku o iwanaide.", contohId:"Jangan mengeluh satu per satu."},
{kat:"Kata Keterangan", kanji:"つくづく", kana:"つくづく", romaji:"tsukuzuku", arti:"benar-benar merasakan", contohJp:"つくづく自分の未熟さを感じた。", contohRomaji:"Tsukuzuku jibun no mijukusa o kanjita.", contohId:"Benar-benar merasakan kekurangan diri sendiri."},
{kat:"Kata Keterangan", kanji:"てっきり", kana:"てっきり", romaji:"tekkiri", arti:"pasti saja (padahal salah duga)", contohJp:"てっきり休みだと思っていた。", contohRomaji:"Tekkiri yasumi da to omotte ita.", contohId:"Saya pikir pasti libur (ternyata tidak)."},
{kat:"Kata Keterangan", kanji:"とっさに", kana:"とっさに", romaji:"tossa ni", arti:"secara refleks", contohJp:"とっさに手が出た。", contohRomaji:"Tossa ni te ga deta.", contohId:"Tangan bergerak secara refleks."},
{kat:"Kata Keterangan", kanji:"なんとか", kana:"なんとか", romaji:"nantoka", arti:"entah bagaimana (berhasil)", contohJp:"なんとか間に合った。", contohRomaji:"Nantoka maniatta.", contohId:"Entah bagaimana berhasil tepat waktu."},
{kat:"Kata Keterangan", kanji:"まもなく", kana:"まもなく", romaji:"mamonaku", arti:"segera, tak lama lagi", contohJp:"まもなく電車が到着します。", contohRomaji:"Mamonaku densha ga touchaku shimasu.", contohId:"Kereta akan segera tiba."},
{kat:"Kata Keterangan", kanji:"もっぱら", kana:"もっぱら", romaji:"moppara", arti:"semata-mata, khusus", contohJp:"もっぱら仕事に専念している。", contohRomaji:"Moppara shigoto ni sennen shite iru.", contohId:"Berkonsentrasi semata-mata pada pekerjaan."},
{kat:"Kata Keterangan", kanji:"やむを得ず", kana:"やむをえず", romaji:"yamu o ezu", arti:"terpaksa", contohJp:"やむを得ず中止した。", contohRomaji:"Yamu o ezu chuushi shita.", contohId:"Terpaksa membatalkan."},
{kat:"Kata Keterangan", kanji:"果たして", kana:"はたして", romaji:"hatashite", arti:"benarkah, apakah betul", contohJp:"果たして成功するだろうか。", contohRomaji:"Hatashite seikou suru darou ka.", contohId:"Apakah benar-benar akan berhasil ya."},

// ================= 7. KATA SAMBUNG & UNGKAPAN =================
{kat:"Kata Sambung", kanji:"それにしては", kana:"それにしては", romaji:"sore ni shite wa", arti:"kalau dipikir-pikir (tidak sesuai)", contohJp:"彼は日本に来たばかりだ。それにしては日本語が上手だ。", contohRomaji:"Kare wa nihon ni kita bakari da. Sore ni shite wa nihongo ga jouzu da.", contohId:"Dia baru datang ke Jepang. Padahal begitu, bahasa Jepangnya sudah lancar."},
{kat:"Kata Sambung", kanji:"それにひきかえ", kana:"それにひきかえ", romaji:"sore ni hikikae", arti:"berbeda dengan itu", contohJp:"兄は真面目だ。それにひきかえ弟は怠け者だ。", contohRomaji:"Ani wa majime da. Sore ni hikikae otouto wa namakemono da.", contohId:"Kakak rajin. Berbeda dengan itu, adik pemalas."},
{kat:"Kata Sambung", kanji:"かえって", kana:"かえって", romaji:"kaette", arti:"malah sebaliknya", contohJp:"薬を飲んだら、かえって具合が悪くなった。", contohRomaji:"Kusuri o nondara, kaette guai ga waruku natta.", contohId:"Setelah minum obat, malah tambah tidak enak badan."},
{kat:"Kata Sambung", kanji:"なにより", kana:"なにより", romaji:"nani yori", arti:"yang paling (penting)", contohJp:"健康がなにより大切だ。", contohRomaji:"Kenkou ga nani yori taisetsu da.", contohId:"Kesehatan adalah yang paling penting."},
{kat:"Kata Sambung", kanji:"ひいては", kana:"ひいては", romaji:"hiite wa", arti:"bahkan lebih jauh lagi", contohJp:"個人の努力が、ひいては社会全体の利益になる。", contohRomaji:"Kojin no doryoku ga, hiite wa shakai zentai no rieki ni naru.", contohId:"Usaha individu, bahkan lebih jauh, menjadi manfaat bagi seluruh masyarakat."},
{kat:"Kata Sambung", kanji:"ただでさえ", kana:"ただでさえ", romaji:"tada de sae", arti:"biasanya saja (sudah begitu, apalagi)", contohJp:"ただでさえ忙しいのに、仕事が増えた。", contohRomaji:"Tada de sae isogashii noni, shigoto ga fueta.", contohId:"Biasanya saja sudah sibuk, malah pekerjaan bertambah."},
{kat:"Kata Sambung", kanji:"とはいえ", kana:"とはいえ", romaji:"to wa ie", arti:"meskipun begitu", contohJp:"忙しい。とはいえ、休みも必要だ。", contohRomaji:"Isogashii. To wa ie, yasumi mo hitsuyou da.", contohId:"Sibuk. Meskipun begitu, istirahat juga perlu."},
{kat:"Kata Sambung", kanji:"とりわけ", kana:"とりわけ", romaji:"toriwake", arti:"terutama", contohJp:"今年はとりわけ暑い。", contohRomaji:"Kotoshi wa toriwake atsui.", contohId:"Tahun ini terutama panas sekali."},
{kat:"Kata Sambung", kanji:"なかでも", kana:"なかでも", romaji:"naka demo", arti:"di antaranya, terutama", contohJp:"果物の中でもいちごが好きだ。", contohRomaji:"Kudamono no naka demo ichigo ga suki da.", contohId:"Di antara buah-buahan, saya paling suka stroberi."},
{kat:"Kata Sambung", kanji:"あたかも", kana:"あたかも", romaji:"atakamo", arti:"seolah-olah", contohJp:"あたかも本当のことのように話す。", contohRomaji:"Atakamo hontou no koto no you ni hanasu.", contohId:"Berbicara seolah-olah itu hal yang nyata."},
{kat:"Kata Sambung", kanji:"いかにも", kana:"いかにも", romaji:"ikanimo", arti:"benar-benar terlihat seperti", contohJp:"いかにも高そうなバッグだ。", contohRomaji:"Ikanimo takasou na baggu da.", contohId:"Tas yang benar-benar terlihat mahal."},
{kat:"Kata Sambung", kanji:"さも", kana:"さも", romaji:"samo", arti:"seolah-olah (meyakinkan)", contohJp:"さも知っているかのように話した。", contohRomaji:"Samo shitte iru ka no you ni hanashita.", contohId:"Berbicara seolah-olah benar-benar tahu."},
{kat:"Kata Sambung", kanji:"ろくに", kana:"ろくに", romaji:"roku ni", arti:"tidak dengan benar/layak", contohJp:"忙しくてろくに休めなかった。", contohRomaji:"Isogashikute roku ni yasumenakatta.", contohId:"Terlalu sibuk sampai tidak sempat istirahat dengan layak."},
{kat:"Kata Sambung", kanji:"まして", kana:"まして", romaji:"mashite", arti:"apalagi", contohJp:"大人でも難しい。まして子供には無理だ。", contohRomaji:"Otona demo muzukashii. Mashite kodomo ni wa muri da.", contohId:"Orang dewasa saja sulit. Apalagi anak-anak, pasti mustahil."},
{kat:"Kata Sambung", kanji:"いわゆる", kana:"いわゆる", romaji:"iwayuru", arti:"yang disebut sebagai", contohJp:"これがいわゆる格差社会だ。", contohRomaji:"Kore ga iwayuru kakusa shakai da.", contohId:"Inilah yang disebut sebagai masyarakat kesenjangan."},

// ================= 8. KATA SERAPAN =================
{kat:"Kata Serapan", kanji:"インフラ", kana:"インフラ", romaji:"infura", arti:"infrastruktur", contohJp:"インフラの整備が進んでいる。", contohRomaji:"Infura no seibi ga susunde iru.", contohId:"Pembangunan infrastruktur sedang berkembang."},
{kat:"Kata Serapan", kanji:"コンセプト", kana:"コンセプト", romaji:"konseputo", arti:"konsep", contohJp:"新商品のコンセプトを考えた。", contohRomaji:"Shinshouhin no konseputo o kangaeta.", contohId:"Memikirkan konsep produk baru."},
{kat:"Kata Serapan", kanji:"モチベーション", kana:"モチベーション", romaji:"mochibeeshon", arti:"motivasi", contohJp:"モチベーションが上がらない。", contohRomaji:"Mochibeeshon ga agaranai.", contohId:"Motivasi tidak naik-naik."},
{kat:"Kata Serapan", kanji:"リスク", kana:"リスク", romaji:"risuku", arti:"risiko", contohJp:"リスクを最小限に抑える。", contohRomaji:"Risuku o saishougen ni osaeru.", contohId:"Menekan risiko seminimal mungkin."},
{kat:"Kata Serapan", kanji:"スキル", kana:"スキル", romaji:"sukiru", arti:"keahlian", contohJp:"新しいスキルを身につけたい。", contohRomaji:"Atarashii sukiru o mi ni tsuketai.", contohId:"Ingin menguasai keahlian baru."},
{kat:"Kata Serapan", kanji:"キャリア", kana:"キャリア", romaji:"kyaria", arti:"karier", contohJp:"キャリアアップを目指している。", contohRomaji:"Kyaria appu o mezashite iru.", contohId:"Menargetkan peningkatan karier."},
{kat:"Kata Serapan", kanji:"プレッシャー", kana:"プレッシャー", romaji:"puresshaa", arti:"tekanan", contohJp:"プレッシャーに負けそうだ。", contohRomaji:"Puresshaa ni makesou da.", contohId:"Sepertinya akan kalah dari tekanan."},
{kat:"Kata Serapan", kanji:"ノウハウ", kana:"ノウハウ", romaji:"nouhau", arti:"pengetahuan praktis", contohJp:"長年のノウハウを活かす。", contohRomaji:"Naganen no nouhau o ikasu.", contohId:"Memanfaatkan pengetahuan praktis bertahun-tahun."},
{kat:"Kata Serapan", kanji:"フォロー", kana:"フォロー", romaji:"forou", arti:"dukungan, follow up", contohJp:"新人をフォローする。", contohRomaji:"Shinjin o forou suru.", contohId:"Memberi dukungan kepada karyawan baru."},
{kat:"Kata Serapan", kanji:"ネットワーク", kana:"ネットワーク", romaji:"nettowaaku", arti:"jaringan", contohJp:"広いネットワークを持っている。", contohRomaji:"Hiroi nettowaaku o motte iru.", contohId:"Memiliki jaringan yang luas."},
{kat:"Kata Serapan", kanji:"アプローチ", kana:"アプローチ", romaji:"apuroochi", arti:"pendekatan", contohJp:"新しいアプローチを試みる。", contohRomaji:"Atarashii apuroochi o kokoromiru.", contohId:"Mencoba pendekatan baru."},
{kat:"Kata Serapan", kanji:"ジレンマ", kana:"ジレンマ", romaji:"jirenma", arti:"dilema", contohJp:"ジレンマに陥った。", contohRomaji:"Jirenma ni ochiitta.", contohId:"Terjebak dalam dilema."},
{kat:"Kata Serapan", kanji:"モラル", kana:"モラル", romaji:"moraru", arti:"moral", contohJp:"モラルが低下している。", contohRomaji:"Moraru ga teika shite iru.", contohId:"Moral sedang menurun."},
{kat:"Kata Serapan", kanji:"ステータス", kana:"ステータス", romaji:"suteetasu", arti:"status", contohJp:"社会的ステータスを気にする。", contohRomaji:"Shakaiteki suteetasu o ki ni suru.", contohId:"Memedulikan status sosial."},
{kat:"Kata Serapan", kanji:"インパクト", kana:"インパクト", romaji:"inpakuto", arti:"dampak", contohJp:"強いインパクトを与えた。", contohRomaji:"Tsuyoi inpakuto o ataeta.", contohId:"Memberikan dampak yang kuat."},

// ================= 9. IDIOM & UNGKAPAN TETAP =================
{kat:"Idiom", kanji:"気が済む", kana:"きがすむ", romaji:"ki ga sumu", arti:"lega, puas hati", contohJp:"謝るまで気が済まない。", contohRomaji:"Ayamaru made ki ga sumanai.", contohId:"Tidak akan lega sampai meminta maaf."},
{kat:"Idiom", kanji:"気に食わない", kana:"きにくわない", romaji:"ki ni kuwanai", arti:"tidak menyukai", contohJp:"彼のやり方が気に食わない。", contohRomaji:"Kare no yarikata ga ki ni kuwanai.", contohId:"Tidak suka dengan caranya melakukan sesuatu."},
{kat:"Idiom", kanji:"手を焼く", kana:"てをやく", romaji:"te o yaku", arti:"kewalahan menghadapi", contohJp:"子供のいたずらに手を焼いている。", contohRomaji:"Kodomo no itazura ni te o yaite iru.", contohId:"Kewalahan menghadapi kenakalan anak."},
{kat:"Idiom", kanji:"目を通す", kana:"めをとおす", romaji:"me o toosu", arti:"membaca sekilas", contohJp:"資料に目を通しておいた。", contohRomaji:"Shiryou ni me o tooshite oita.", contohId:"Sudah membaca sekilas dokumennya."},
{kat:"Idiom", kanji:"腹を立てる", kana:"はらをたてる", romaji:"hara o tateru", arti:"marah", contohJp:"彼の態度に腹を立てた。", contohRomaji:"Kare no taido ni hara o tateta.", contohId:"Marah dengan sikapnya."},
{kat:"Idiom", kanji:"口を出す", kana:"くちをだす", romaji:"kuchi o dasu", arti:"ikut campur bicara", contohJp:"他人のことに口を出すな。", contohRomaji:"Tanin no koto ni kuchi o dasu na.", contohId:"Jangan ikut campur urusan orang lain."},
{kat:"Idiom", kanji:"顔を出す", kana:"かおをだす", romaji:"kao o dasu", arti:"menampakkan diri", contohJp:"パーティーに顔を出した。", contohRomaji:"Paatii ni kao o dashita.", contohId:"Menampakkan diri di pesta."},
{kat:"Idiom", kanji:"気を配る", kana:"きをくばる", romaji:"ki o kubaru", arti:"memperhatikan dengan seksama", contohJp:"細部にまで気を配る。", contohRomaji:"Saibu ni made ki o kubaru.", contohId:"Memperhatikan sampai ke detail."},
{kat:"Idiom", kanji:"手がかかる", kana:"てがかかる", romaji:"te ga kakaru", arti:"merepotkan (butuh usaha)", contohJp:"この作業は手がかかる。", contohRomaji:"Kono sagyou wa te ga kakaru.", contohId:"Pekerjaan ini butuh banyak usaha."},
{kat:"Idiom", kanji:"骨が折れる", kana:"ほねがおれる", romaji:"hone ga oreru", arti:"susah payah", contohJp:"この仕事は骨が折れる。", contohRomaji:"Kono shigoto wa hone ga oreru.", contohId:"Pekerjaan ini susah payah."},
{kat:"Idiom", kanji:"目に見えて", kana:"めにみえて", romaji:"me ni miete", arti:"terlihat jelas (perubahan)", contohJp:"目に見えて上達した。", contohRomaji:"Me ni miete joutatsu shita.", contohId:"Kemajuannya terlihat jelas."},
{kat:"Idiom", kanji:"気が重い", kana:"きがおもい", romaji:"ki ga omoi", arti:"berat hati", contohJp:"明日の会議を思うと気が重い。", contohRomaji:"Ashita no kaigi o omou to ki ga omoi.", contohId:"Berat hati memikirkan rapat besok."},
{kat:"Idiom", kanji:"頭を抱える", kana:"あたまをかかえる", romaji:"atama o kakaeru", arti:"pusing memikirkan", contohJp:"問題が多くて頭を抱えている。", contohRomaji:"Mondai ga ookute atama o kakaete iru.", contohId:"Pusing memikirkan banyaknya masalah."},
{kat:"Idiom", kanji:"板につく", kana:"いたにつく", romaji:"ita ni tsuku", arti:"jadi mahir/cocok dengan perannya", contohJp:"新しい仕事がだいぶ板についてきた。", contohRomaji:"Atarashii shigoto ga daibu ita ni tsuite kita.", contohId:"Sudah mulai mahir dengan pekerjaan barunya."},
{kat:"Idiom", kanji:"図に乗る", kana:"ずにのる", romaji:"zu ni noru", arti:"besar kepala, kelewat batas", contohJp:"褒められて図に乗ってはいけない。", contohRomaji:"Homerarete zu ni notte wa ikenai.", contohId:"Jangan jadi besar kepala karena dipuji."},

// ================= 10. KATA BENDA ABSTRAK & AKADEMIS =================
{kat:"Abstrak & Akademis", kanji:"概念", kana:"がいねん", romaji:"gainen", arti:"konsep", contohJp:"新しい概念を導入する。", contohRomaji:"Atarashii gainen o dounyuu suru.", contohId:"Memperkenalkan konsep baru."},
{kat:"Abstrak & Akademis", kanji:"要素", kana:"ようそ", romaji:"youso", arti:"elemen, unsur", contohJp:"成功の要素は何ですか。", contohRomaji:"Seikou no youso wa nan desu ka.", contohId:"Apa saja elemen dari kesuksesan?"},
{kat:"Abstrak & Akademis", kanji:"要因", kana:"よういん", romaji:"youin", arti:"faktor penyebab", contohJp:"事故の要因を調べる。", contohRomaji:"Jiko no youin o shiraberu.", contohId:"Menyelidiki faktor penyebab kecelakaan."},
{kat:"Abstrak & Akademis", kanji:"特徴", kana:"とくちょう", romaji:"tokuchou", arti:"ciri khas", contohJp:"この製品の特徴を説明する。", contohRomaji:"Kono seihin no tokuchou o setsumei suru.", contohId:"Menjelaskan ciri khas produk ini."},
{kat:"Abstrak & Akademis", kanji:"根拠", kana:"こんきょ", romaji:"konkyo", arti:"dasar, landasan (argumen)", contohJp:"根拠のない噂だ。", contohRomaji:"Konkyo no nai uwasa da.", contohId:"Itu rumor tanpa dasar."},
{kat:"Abstrak & Akademis", kanji:"前提", kana:"ぜんてい", romaji:"zentei", arti:"premis, prasyarat", contohJp:"その前提が間違っている。", contohRomaji:"Sono zentei ga machigatte iru.", contohId:"Premis itu keliru."},
{kat:"Abstrak & Akademis", kanji:"観点", kana:"かんてん", romaji:"kanten", arti:"sudut pandang", contohJp:"別の観点から考えてみる。", contohRomaji:"Betsu no kanten kara kangaete miru.", contohId:"Mencoba berpikir dari sudut pandang lain."},
{kat:"Abstrak & Akademis", kanji:"視点", kana:"してん", romaji:"shiten", arti:"perspektif", contohJp:"新しい視点を提供する。", contohRomaji:"Atarashii shiten o teikyou suru.", contohId:"Menyediakan perspektif baru."},
{kat:"Abstrak & Akademis", kanji:"手段", kana:"しゅだん", romaji:"shudan", arti:"cara, sarana", contohJp:"目的のためには手段を選ばない。", contohRomaji:"Mokuteki no tame ni wa shudan o erabanai.", contohId:"Demi tujuan, tidak memilih-milih cara."},
{kat:"Abstrak & Akademis", kanji:"過程", kana:"かてい", romaji:"katei", arti:"proses", contohJp:"成長の過程を見守る。", contohRomaji:"Seichou no katei o mimamoru.", contohId:"Mengawasi proses pertumbuhan."},
{kat:"Abstrak & Akademis", kanji:"結論", kana:"けつろん", romaji:"ketsuron", arti:"kesimpulan", contohJp:"まだ結論が出ていない。", contohRomaji:"Mada ketsuron ga dete inai.", contohId:"Belum ada kesimpulan."},
{kat:"Abstrak & Akademis", kanji:"矛盾", kana:"むじゅん", romaji:"mujun", arti:"kontradiksi", contohJp:"話に矛盾がある。", contohRomaji:"Hanashi ni mujun ga aru.", contohId:"Ada kontradiksi dalam ceritanya."},
{kat:"Abstrak & Akademis", kanji:"仮説", kana:"かせつ", romaji:"kasetsu", arti:"hipotesis", contohJp:"仮説を検証する。", contohRomaji:"Kasetsu o kenshou suru.", contohId:"Memverifikasi hipotesis."},
{kat:"Abstrak & Akademis", kanji:"検証", kana:"けんしょう", romaji:"kenshou", arti:"verifikasi", contohJp:"データを検証する必要がある。", contohRomaji:"Deeta o kenshou suru hitsuyou ga aru.", contohId:"Perlu memverifikasi data."},
{kat:"Abstrak & Akademis", kanji:"分析", kana:"ぶんせき", romaji:"bunseki", arti:"analisis", contohJp:"結果を分析する。", contohRomaji:"Kekka o bunseki suru.", contohId:"Menganalisis hasil."},
{kat:"Abstrak & Akademis", kanji:"傾倒", kana:"けいとう", romaji:"keitou", arti:"kecenderungan condong", contohJp:"彼はその思想に傾倒している。", contohRomaji:"Kare wa sono shisou ni keitou shite iru.", contohId:"Dia condong pada pemikiran itu."},
{kat:"Abstrak & Akademis", kanji:"普及", kana:"ふきゅう", romaji:"fukyuu", arti:"penyebaran, pemasyarakatan", contohJp:"スマホが急速に普及した。", contohRomaji:"Sumaho ga kyuusoku ni fukyuu shita.", contohId:"Smartphone tersebar dengan cepat."},
{kat:"Abstrak & Akademis", kanji:"促進", kana:"そくしん", romaji:"sokushin", arti:"percepatan, pendorongan", contohJp:"経済成長を促進する。", contohRomaji:"Keizai seichou o sokushin suru.", contohId:"Mendorong pertumbuhan ekonomi."},
{kat:"Abstrak & Akademis", kanji:"抑制", kana:"よくせい", romaji:"yokusei", arti:"penekanan, pengendalian", contohJp:"感情を抑制する。", contohRomaji:"Kanjou o yokusei suru.", contohId:"Mengendalikan emosi."},
];
