// ===================================================================
// Qategori Nihongo - Reading (読解) JLPT N2
// Furigana: {漢字|かんじ} (kata dalam kurung kurawal, bacaan setelah |)
// tipe: tanbun (bacaan pendek), chuubun (menengah), jouhou (pencarian informasi)
// ===================================================================
window.N2_READING = [

{id:"n2r01", tipe:"tanbun", topik:"Memo kantor",
 judul:"{社内|しゃない}{連絡|れんらく}：{会議室|かいぎしつ}の{利用|りよう}について",
 teks:"{来月|らいげつ}から、{会議室|かいぎしつ}の{予約|よやく}は{社内|しゃない}システムを{通|つう}じて{行|おこな}うことになりました。これまでは{紙|かみ}の{表|ひょう}に{名前|なまえ}を{書|か}き{込|こ}む{方式|ほうしき}でしたが、{重複|ちょうふく}した{予約|よやく}が{後|あと}を{絶|た}たなかったため、{改善|かいぜん}することにしました。なお、{利用|りよう}しない{場合|ばあい}は、{開始|かいし}の{一時間|いちじかん}{前|まえ}までに{必|かなら}ず{取|と}り{消|け}してください。{無断|むだん}でキャンセルした{場合|ばあい}、{一か月|いっかげつ}{間|かん}{予約|よやく}ができなくなります。",
 terjemahan:"Mulai bulan depan, pemesanan ruang rapat dilakukan melalui sistem internal. Sebelumnya dengan menulis nama di tabel kertas, tetapi karena pemesanan ganda tak ada habisnya, kami memutuskan memperbaikinya. Jika tidak jadi memakai, harap batalkan paling lambat satu jam sebelum mulai. Jika membatalkan tanpa pemberitahuan, Anda tidak dapat memesan selama satu bulan.",
 soal:[
  {q:"{会議室|かいぎしつ}の{予約|よやく}の{方法|ほうほう}は、どうなりますか。", opt:["{紙|かみ}の{表|ひょう}に{書|か}く","{社内|しゃない}システムで{行|おこな}う","{電話|でんわ}で{頼|たの}む","{受付|うけつけ}で{頼|たの}む"], correct:1, exp:"来月から社内システムを通じて行う → lewat sistem internal."},
  {q:"{方法|ほうほう}を{変|か}える{理由|りゆう}は{何|なん}ですか。", opt:["{紙|かみ}が{足|た}りないから","{予約|よやく}が{重|かさ}なることが{多|おお}かったから","システムが{安|やす}いから","{会議室|かいぎしつ}が{減|へ}ったから"], correct:1, exp:"重複した予約が後を絶たなかったため → pemesanan ganda terus terjadi."},
  {q:"{無断|むだん}でキャンセルすると、どうなりますか。", opt:["{罰金|ばっきん}を{払|はら}う","{一か月|いっかげつ}{予約|よやく}できない","{上司|じょうし}に{報告|ほうこく}される","{何|なに}も{起|お}こらない"], correct:1, exp:"一か月間予約ができなくなります."}
 ]},

{id:"n2r02", tipe:"tanbun", topik:"Surat pembaca",
 judul:"{在宅|ざいたく}{勤務|きんむ}について{思|おも}うこと",
 teks:"{在宅|ざいたく}{勤務|きんむ}が{広|ひろ}まって{三年|さんねん}になる。{通勤|つうきん}の{負担|ふたん}が{減|へ}り、{家族|かぞく}と{過|す}ごす{時間|じかん}も{増|ふ}えたのは{確|たし}かだ。しかし、{仕事|しごと}と{生活|せいかつ}の{境目|さかいめ}が{曖昧|あいまい}になり、{夜遅|よるおそ}くまでメールを{確認|かくにん}してしまう{人|ひと}も{少|すく}なくない。{便利|べんり}さの{裏|うら}に、{新|あたら}しい{問題|もんだい}が{隠|かく}れていることを{忘|わす}れてはならない。{会社|かいしゃ}は{制度|せいど}を{作|つく}るだけでなく、{働|はたら}く{人|ひと}が{休|やす}める{環境|かんきょう}を{整|ととの}える{必要|ひつよう}がある。",
 terjemahan:"Sudah tiga tahun kerja dari rumah meluas. Memang beban perjalanan berkurang dan waktu bersama keluarga bertambah. Namun, batas antara kerja dan kehidupan menjadi kabur, dan tak sedikit orang yang mengecek email hingga larut malam. Kita tak boleh lupa bahwa di balik kemudahan tersembunyi masalah baru. Perusahaan tidak cukup hanya membuat sistem, tetapi perlu menyiapkan lingkungan agar pekerja bisa beristirahat.",
 soal:[
  {q:"{筆者|ひっしゃ}は{在宅|ざいたく}{勤務|きんむ}の{良|よ}い{点|てん}として{何|なに}を{挙|あ}げていますか。", opt:["{給料|きゅうりょう}が{上|あ}がること","{通勤|つうきん}の{負担|ふたん}が{減|へ}ること","{仕事|しごと}が{減|へ}ること","{会議|かいぎ}がなくなること"], correct:1, exp:"通勤の負担が減り、家族と過ごす時間が増えた."},
  {q:"{筆者|ひっしゃ}が{問題|もんだい}だと{考|かんが}えているのは{何|なん}ですか。", opt:["{仕事|しごと}と{生活|せいかつ}の{境目|さかいめ}が{曖昧|あいまい}になること","{通勤|つうきん}が{長|なが}いこと","{家族|かぞく}と{話|はな}せないこと","{会社|かいしゃ}に{行|い}けないこと"], correct:0, exp:"仕事と生活の境目が曖昧になり、夜遅くまでメールを確認する."},
  {q:"{筆者|ひっしゃ}は{会社|かいしゃ}に{何|なに}を{求|もと}めていますか。", opt:["{制度|せいど}をやめること","{休|やす}める{環境|かんきょう}を{整|ととの}えること","{給料|きゅうりょう}を{上|あ}げること","{出社|しゅっしゃ}させること"], correct:1, exp:"働く人が休める環境を整える必要がある."}
 ]},

{id:"n2r03", tipe:"tanbun", topik:"Surel bisnis",
 judul:"お{詫|わ}びとご{報告|ほうこく}",
 teks:"{株式会社|かぶしきがいしゃ}ABC　{山田|やまだ}{様|さま}\nいつもお{世話|せわ}になっております。{先日|せんじつ}ご{注文|ちゅうもん}いただいた{商品|しょうひん}が、{予定|よてい}の{日|ひ}までに{届|とど}かず、{大変|たいへん}ご{迷惑|めいわく}をおかけしました。{調査|ちょうさ}したところ、{倉庫|そうこ}での{在庫|ざいこ}の{確認|かくにん}にミスがあったことが{分|わ}かりました。{商品|しょうひん}は{明日|あした}の{午前中|ごぜんちゅう}にお{届|とど}けいたします。{今後|こんご}、このようなことがないよう、{確認|かくにん}の{手順|てじゅん}を{見直|みなお}してまいります。\n{東京商事|とうきょうしょうじ}　{佐藤|さとう}",
 terjemahan:"Kepada Bapak/Ibu Yamada, PT ABC. Terima kasih atas kerja samanya. Barang yang Anda pesan tempo hari tidak tiba pada hari yang dijadwalkan, dan kami sangat memohon maaf atas ketidaknyamanan. Setelah diselidiki, diketahui ada kesalahan dalam pengecekan stok di gudang. Barang akan kami antar besok pagi. Ke depannya, agar hal seperti ini tidak terulang, kami akan meninjau ulang prosedur pengecekan. Sato, Tokyo Shoji.",
 soal:[
  {q:"{商品|しょうひん}が{届|とど}かなかった{原因|げんいん}は{何|なん}ですか。", opt:["{注文|ちゅうもん}を{忘|わす}れたから","{倉庫|そうこ}で{在庫|ざいこ}の{確認|かくにん}を{間違|まちが}えたから","{天気|てんき}が{悪|わる}かったから","{住所|じゅうしょ}が{違|ちが}ったから"], correct:1, exp:"倉庫での在庫の確認にミスがあった."},
  {q:"{商品|しょうひん}はいつ{届|とど}きますか。", opt:["{今日|きょう}の{夜|よる}","{明日|あした}の{午前中|ごぜんちゅう}","{来週|らいしゅう}","{未定|みてい}"], correct:1, exp:"商品は明日の午前中にお届けいたします."},
  {q:"{佐藤|さとう}さんは{今後|こんご}、{何|なに}をしますか。", opt:["{確認|かくにん}の{手順|てじゅん}を{見直|みなお}す","{倉庫|そうこ}を{移|うつ}す","{値段|ねだん}を{下|さ}げる","{取引|とりひき}をやめる"], correct:0, exp:"確認の手順を見直してまいります."}
 ]},

{id:"n2r04", tipe:"tanbun", topik:"Pengumuman apartemen",
 judul:"エレベーター{点検|てんけん}のお{知|し}らせ",
 teks:"{管理|かんり}{組合|くみあい}より、お{知|し}らせいたします。{法律|ほうりつ}で{定|さだ}められた{点検|てんけん}のため、{来週|らいしゅう}の{水曜日|すいようび}は{午前|ごぜん}9{時|じ}から{午後|ごご}3{時|じ}まで、すべてのエレベーターが{使用|しよう}できません。{階段|かいだん}をご{利用|りよう}ください。なお、{大|おお}きな{荷物|にもつ}の{搬入|はんにゅう}や{引|ひ}っ{越|こ}しは、その{日|ひ}を{避|さ}けるようお{願|ねが}いします。{車|くるま}いすをご{利用|りよう}の{方|かた}は、{管理|かんり}{室|しつ}までご{連絡|れんらく}ください。",
 terjemahan:"Pemberitahuan dari pengelola. Karena pemeriksaan yang ditetapkan undang-undang, pada Rabu depan pukul 9 pagi sampai 3 sore semua lift tidak dapat digunakan. Mohon gunakan tangga. Selain itu, mohon hindari hari tersebut untuk memasukkan barang besar atau pindahan. Pengguna kursi roda mohon menghubungi ruang pengelola.",
 soal:[
  {q:"エレベーターが{使|つか}えないのは、いつですか。", opt:["{来週|らいしゅう}の{水曜日|すいようび}の{午前|ごぜん}9{時|じ}から{午後|ごご}3{時|じ}まで","{来週|らいしゅう}の{水曜日|すいようび}の{一日中|いちにちじゅう}","{今週|こんしゅう}の{水曜日|すいようび}","{毎日|まいにち}{午後|ごご}3{時|じ}から"], correct:0, exp:"来週の水曜日の午前9時から午後3時まで."},
  {q:"{点検|てんけん}をする{理由|りゆう}は{何|なん}ですか。", opt:["エレベーターが{壊|こわ}れたから","{法律|ほうりつ}で{決|き}まっているから","{新|あたら}しくするから","{住民|じゅうみん}が{頼|たの}んだから"], correct:1, exp:"法律で定められた点検のため."},
  {q:"{車|くるま}いすの{人|ひと}は、どうすればいいですか。", opt:["{管理|かんり}{室|しつ}に{連絡|れんらく}する","{階段|かいだん}を{使|つか}う","{家|いえ}で{待|ま}つ","{引|ひ}っ{越|こ}しをする"], correct:0, exp:"車いすをご利用の方は、管理室までご連絡ください."}
 ]},

{id:"n2r05", tipe:"chuubun", topik:"Esai",
 judul:"{習慣|しゅうかん}の{力|ちから}",
 teks:"{新年|しんねん}に{立|た}てた{目標|もくひょう}が、{三日坊主|みっかぼうず}で{終|お}わった{経験|けいけん}は{誰|だれ}にでもあるだろう。{意志|いし}が{弱|よわ}いからだと{考|かんが}えがちだが、{実際|じっさい}はそうではない。{心理学|しんりがく}の{研究|けんきゅう}によれば、{人|ひと}は{意志|いし}の{力|ちから}よりも、{習慣|しゅうかん}によって{行動|こうどう}している{部分|ぶぶん}が{大|おお}きい。{大切|たいせつ}なのは、{最初|さいしょ}から{大|おお}きな{目標|もくひょう}を{掲|かか}げないことだ。たとえば、{毎日|まいにち}{一時間|いちじかん}{走|はし}ると{決|き}めるより、まず{玄関|げんかん}で{靴|くつ}を{履|は}くだけでもよい。{小|ちい}さな{行動|こうどう}を{繰|く}り{返|かえ}すうちに、それは{自然|しぜん}な{習慣|しゅうかん}となり、{気|き}づけば{大|おお}きな{成果|せいか}につながっているものである。",
 terjemahan:"Siapa pun pasti pernah mengalami target tahun baru yang berakhir sebagai semangat tiga hari. Kita cenderung mengira karena kemauan lemah, tetapi sebenarnya tidak. Menurut penelitian psikologi, bagian perilaku manusia yang digerakkan oleh kebiasaan lebih besar daripada kekuatan kemauan. Yang penting adalah tidak mengusung target besar sejak awal. Misalnya, daripada memutuskan berlari satu jam tiap hari, cukup dulu memakai sepatu di pintu masuk. Saat tindakan kecil diulang, itu menjadi kebiasaan alami, dan tanpa sadar terhubung dengan hasil besar.",
 soal:[
  {q:"{筆者|ひっしゃ}は、{目標|もくひょう}が{続|つづ}かない{理由|りゆう}をどう{考|かんが}えていますか。", opt:["{意志|いし}が{弱|よわ}いからではない","{意志|いし}が{弱|よわ}いからだ","{時間|じかん}がないからだ","{目標|もくひょう}が{小|ちい}さいからだ"], correct:0, exp:"意志が弱いからだと考えがちだが、実際はそうではない."},
  {q:"{人|ひと}の{行動|こうどう}について、{心理学|しんりがく}の{研究|けんきゅう}は{何|なに}を{示|しめ}していますか。", opt:["{意志|いし}の{力|ちから}がすべてである","{習慣|しゅうかん}による{部分|ぶぶん}が{大|おお}きい","{環境|かんきょう}は{関係|かんけい}ない","{年齢|ねんれい}で{決|き}まる"], correct:1, exp:"意志の力よりも、習慣によって行動している部分が大きい."},
  {q:"{筆者|ひっしゃ}が{勧|すす}めている{方法|ほうほう}はどれですか。", opt:["{最初|さいしょ}から{大|おお}きな{目標|もくひょう}を{立|た}てる","{小|ちい}さな{行動|こうどう}から{始|はじ}める","{他|ほか}の{人|ひと}に{頼|たの}む","{毎日|まいにち}{違|ちが}うことをする"], correct:1, exp:"まず玄関で靴を履くだけでもよい → mulai dari tindakan kecil."}
 ]},

{id:"n2r06", tipe:"chuubun", topik:"Lingkungan",
 judul:"レジ{袋|ぶくろ}{有料化|ゆうりょうか}のその{後|あと}",
 teks:"レジ{袋|ぶくろ}が{有料|ゆうりょう}になって{数年|すうねん}が{経|た}った。{当初|とうしょ}は{不満|ふまん}の{声|こえ}も{多|おお}かったが、{今|いま}ではマイバッグを{持|も}ち{歩|ある}く{人|ひと}が{大半|たいはん}を{占|し}めるようになった。ある{調査|ちょうさ}によると、レジ{袋|ぶくろ}の{使用量|しようりょう}は{制度|せいど}の{開始|かいし}{前|まえ}に{比|くら}べて{七割|ななわり}{近|ちか}く{減|へ}ったという。{一方|いっぽう}で、{専門家|せんもんか}は「{袋|ふくろ}を{減|へ}らしただけでは、{環境|かんきょう}{問題|もんだい}は{解決|かいけつ}しない」と{指摘|してき}する。プラスチックごみ{全体|ぜんたい}の{中|なか}で、レジ{袋|ぶくろ}が{占|し}める{割合|わりあい}はわずかだからだ。{大切|たいせつ}なのは、この{制度|せいど}をきっかけに、{私|わたし}たちが{身|み}の{回|まわ}りのごみに{目|め}を{向|む}けることだろう。",
 terjemahan:"Sudah beberapa tahun sejak kantong plastik kasir berbayar. Awalnya banyak keluhan, tetapi kini sebagian besar orang membawa tas sendiri. Menurut suatu survei, penggunaan kantong plastik berkurang hampir 70 persen dibanding sebelum sistem dimulai. Di sisi lain, pakar menunjuk bahwa hanya mengurangi kantong tidak menyelesaikan masalah lingkungan, karena porsi kantong plastik dalam seluruh sampah plastik sangat kecil. Yang penting, lewat sistem ini kita mulai memperhatikan sampah di sekitar kita.",
 soal:[
  {q:"レジ{袋|ぶくろ}の{使用量|しようりょう}は、どうなりましたか。", opt:["{増|ふ}えた","{変|か}わらない","{七割|ななわり}{近|ちか}く{減|へ}った","{半分|はんぶん}になった"], correct:2, exp:"七割近く減ったという."},
  {q:"{専門家|せんもんか}は{何|なに}を{指摘|してき}していますか。", opt:["{袋|ふくろ}を{減|へ}らすだけでは{十分|じゅうぶん}ではない","{制度|せいど}は{失敗|しっぱい}した","{袋|ふくろ}の{値段|ねだん}が{高|たか}い","{環境|かんきょう}{問題|もんだい}はなくなった"], correct:0, exp:"袋を減らしただけでは、環境問題は解決しない."},
  {q:"{筆者|ひっしゃ}は、この{制度|せいど}の{意味|いみ}を{何|なん}だと{考|かんが}えていますか。", opt:["ごみに{関心|かんしん}を{持|も}つきっかけになること","{お金|かね}が{集|あつ}まること","{店|みせ}が{得|とく}をすること","{袋|ふくろ}がなくなること"], correct:0, exp:"身の回りのごみに目を向けるきっかけ."}
 ]},

{id:"n2r07", tipe:"chuubun", topik:"Sains",
 judul:"{睡眠|すいみん}と{記憶|きおく}",
 teks:"{勉強|べんきょう}した{内容|ないよう}を{忘|わす}れないためには、どうすればよいのだろうか。{実験|じっけん}では、{学生|がくせい}を{二つ|ふたつ}のグループに{分|わ}け、{同|おな}じ{単語|たんご}を{覚|おぼ}えさせた。{一方|いっぽう}のグループは{その後|そのご}{八時間|はちじかん}{眠|ねむ}り、もう{一方|いっぽう}は{起|お}きたままで{過|す}ごした。{翌日|よくじつ}テストをしたところ、{眠|ねむ}ったグループの{成績|せいせき}のほうが{明|あき}らかに{良|よ}かった。{睡眠|すいみん}{中|ちゅう}に、{脳|のう}が{情報|じょうほう}を{整理|せいり}し、{記憶|きおく}として{定着|ていちゃく}させるためだと{考|かんが}えられている。{試験|しけん}{前|まえ}に{徹夜|てつや}をするのは、かえって{逆効果|ぎゃくこうか}になりかねない。",
 terjemahan:"Bagaimana agar tidak melupakan isi yang dipelajari? Dalam eksperimen, mahasiswa dibagi dua kelompok dan diminta menghafal kosakata yang sama. Satu kelompok tidur delapan jam setelahnya, kelompok lain tetap terjaga. Saat dites keesokan harinya, nilai kelompok yang tidur jelas lebih baik. Diperkirakan karena saat tidur otak merapikan informasi dan memantapkannya sebagai ingatan. Begadang sebelum ujian justru bisa berbalik merugikan.",
 soal:[
  {q:"{実験|じっけん}で、{二つ|ふたつ}のグループは{何|なに}が{違|ちが}いましたか。", opt:["{覚|おぼ}えた{単語|たんご}","{覚|おぼ}えた{後|あと}に{眠|ねむ}ったかどうか","{勉強|べんきょう}した{時間|じかん}","テストの{内容|ないよう}"], correct:1, exp:"一方は八時間眠り、もう一方は起きたまま."},
  {q:"{結果|けっか}は、どうでしたか。", opt:["{眠|ねむ}ったグループのほうが{良|よ}かった","{起|お}きていたグループのほうが{良|よ}かった","{差|さ}はなかった","テストはできなかった"], correct:0, exp:"眠ったグループの成績のほうが明らかに良かった."},
  {q:"{筆者|ひっしゃ}は{試験|しけん}{前|まえ}の{徹夜|てつや}についてどう{考|かんが}えていますか。", opt:["{効果|こうか}がある","{逆効果|ぎゃくこうか}になることがある","{必要|ひつよう}だ","{関係|かんけい}ない"], correct:1, exp:"かえって逆効果になりかねない."}
 ]},

{id:"n2r08", tipe:"chuubun", topik:"Bahasa & budaya",
 judul:"{方言|ほうげん}の{魅力|みりょく}",
 teks:"{標準語|ひょうじゅんご}が{普及|ふきゅう}した{現在|げんざい}、{若|わか}い{世代|せだい}の{間|あいだ}で{方言|ほうげん}を{使|つか}う{人|ひと}は{減|へ}りつつある。しかし、{方言|ほうげん}にはその{土地|とち}の{歴史|れきし}や{文化|ぶんか}が{詰|つ}まっている。たとえば、{雪|ゆき}の{多|おお}い{地方|ちほう}には、{雪|ゆき}の{状態|じょうたい}を{細|こま}かく{区別|くべつ}する{言葉|ことば}が{数多|かずおお}く{残|のこ}っている。また、{方言|ほうげん}は{親|した}しみやすさを{生|う}む。{初|はじ}めて{会|あ}った{人|ひと}でも、{同|おな}じ{方言|ほうげん}で{話|はな}すだけで、{距離|きょり}が{縮|ちぢ}まることがある。{最近|さいきん}では、{方言|ほうげん}を{地域|ちいき}の{宝|たから}として{守|まも}ろうとする{取|と}り{組|く}みも{各地|かくち}で{行|おこな}われている。",
 terjemahan:"Di masa kini ketika bahasa baku telah meluas, pengguna dialek di kalangan generasi muda terus berkurang. Namun, dialek memuat sejarah dan budaya daerahnya. Misalnya di daerah bersalju banyak tersisa kata yang membedakan keadaan salju secara terperinci. Dialek juga menumbuhkan keakraban; bahkan dengan orang yang baru bertemu, hanya dengan berbicara dalam dialek yang sama jarak bisa mendekat. Belakangan di berbagai tempat dilakukan upaya menjaga dialek sebagai harta daerah.",
 soal:[
  {q:"{若|わか}い{世代|せだい}の{方言|ほうげん}について、{正|ただ}しいのはどれですか。", opt:["{増|ふ}えている","{減|へ}りつつある","{変|か}わらない","{禁止|きんし}されている"], correct:1, exp:"方言を使う人は減りつつある."},
  {q:"{雪|ゆき}の{多|おお}い{地方|ちほう}の{例|れい}は、{何|なに}を{示|しめ}していますか。", opt:["{方言|ほうげん}は{難|むずか}しいこと","{方言|ほうげん}に{土地|とち}の{文化|ぶんか}が{表|あらわ}れていること","{雪|ゆき}は{危険|きけん}なこと","{標準語|ひょうじゅんご}が{便利|べんり}なこと"], correct:1, exp:"方言にはその土地の歴史や文化が詰まっている."},
  {q:"{最近|さいきん}、{各地|かくち}で{行|おこな}われていることは{何|なん}ですか。", opt:["{方言|ほうげん}をなくす{運動|うんどう}","{方言|ほうげん}を{守|まも}ろうとする{取|と}り{組|く}み","{標準語|ひょうじゅんご}の{試験|しけん}","{方言|ほうげん}の{禁止|きんし}"], correct:1, exp:"方言を地域の宝として守ろうとする取り組み."}
 ]},

{id:"n2r09", tipe:"jouhou", topik:"Brosur pameran",
 judul:"{国際|こくさい}{食品|しょくひん}{展示会|てんじかい}のご{案内|あんない}",
 teks:"【{開催|かいさい}{日時|にちじ}】{十一月|じゅういちがつ}{五日|いつか}（{金|きん}）〜{七日|なのか}（{日|にち}）　{午前|ごぜん}10{時|じ}〜{午後|ごご}5{時|じ}（{最終日|さいしゅうび}は{午後|ごご}4{時|じ}まで）\n【{会場|かいじょう}】{東京|とうきょう}{国際|こくさい}{展示場|てんじじょう}　{東|ひがし}ホール\n【{入場料|にゅうじょうりょう}】{一般|いっぱん}　2,000{円|えん}　{学生|がくせい}　1,000{円|えん}（{学生証|がくせいしょう}が{必要|ひつよう}）　{中学生|ちゅうがくせい}{以下|いか}　{無料|むりょう}\n【{事前|じぜん}{登録|とうろく}】{公式|こうしき}サイトから{登録|とうろく}すると、{入場料|にゅうじょうりょう}が500{円|えん}{引|ひ}きになります。\n【{注意|ちゅうい}】{会場|かいじょう}{内|ない}での{試食|ししょく}は{一人|ひとり}{三|みっ}つまで。ペットの{同伴|どうはん}はできません。",
 terjemahan:"[Waktu] 5 November (Jum) – 7 (Min), 10.00–17.00 (hari terakhir sampai 16.00)\n[Tempat] Aula Timur, Tokyo International Exhibition Hall\n[Tiket] Umum 2.000 yen; mahasiswa 1.000 yen (perlu kartu mahasiswa); SMP ke bawah gratis\n[Pra-pendaftaran] Mendaftar lewat situs resmi mendapat potongan 500 yen.\n[Perhatian] Mencicipi di dalam area maksimal tiga per orang. Tidak boleh membawa hewan peliharaan.",
 soal:[
  {q:"{最終日|さいしゅうび}は、{何時|なんじ}まで{開|あ}いていますか。", opt:["{午後|ごご}4{時|じ}","{午後|ごご}5{時|じ}","{午前|ごぜん}10{時|じ}","{午後|ごご}6{時|じ}"], correct:0, exp:"最終日は午後4時まで."},
  {q:"{大学生|だいがくせい}が{事前|じぜん}{登録|とうろく}をして{入場|にゅうじょう}すると、いくらですか。", opt:["2,000{円|えん}","1,000{円|えん}","500{円|えん}","{無料|むりょう}"], correct:2, exp:"学生1,000円 − 500円 = 500円."},
  {q:"{会場|かいじょう}でしてはいけないことは{何|なん}ですか。", opt:["{試食|ししょく}をすること","ペットを{連|つ}れて{入|はい}ること","{写真|しゃしん}を{撮|と}ること","{学生証|がくせいしょう}を{見|み}せること"], correct:1, exp:"ペットの同伴はできません."}
 ]},

{id:"n2r10", tipe:"jouhou", topik:"Panduan program",
 judul:"{新入|しんにゅう}{社員|しゃいん}{研修|けんしゅう}プログラム",
 teks:"【{第一週|だいいっしゅう}】ビジネスマナー・{社内|しゃない}ルールの{説明|せつめい}（{全員|ぜんいん}{参加|さんか}）\n【{第二週|だいにしゅう}】{部署|ぶしょ}{別|べつ}の{実習|じっしゅう}（{配属|はいぞく}{予定|よてい}の{部署|ぶしょ}で{行|おこな}う）\n【{第三週|だいさんしゅう}】{営業|えいぎょう}{同行|どうこう}・{現場|げんば}{見学|けんがく}（{希望|きぼう}{者|しゃ}のみ）\n【{報告|ほうこく}】{各週|かくしゅう}の{金曜日|きんようび}までにレポートを{提出|ていしゅつ}してください。\n【{欠席|けっせき}】{病気|びょうき}など、やむを{得|え}ない{場合|ばあい}は、{前日|ぜんじつ}までに{人事部|じんじぶ}に{連絡|れんらく}してください。",
 terjemahan:"[Minggu 1] Penjelasan tata krama bisnis dan aturan perusahaan (semua peserta)\n[Minggu 2] Praktik per departemen (dilakukan di departemen penempatan)\n[Minggu 3] Mendampingi penjualan dan kunjungan lapangan (hanya peminat)\n[Laporan] Kumpulkan laporan paling lambat Jumat tiap minggu.\n[Absen] Jika terpaksa, misalnya sakit, hubungi bagian SDM paling lambat sehari sebelumnya.",
 soal:[
  {q:"{第二週|だいにしゅう}の{実習|じっしゅう}は、どこで{行|おこな}いますか。", opt:["{全員|ぜんいん}{同|おな}じ{部署|ぶしょ}","{配属|はいぞく}{予定|よてい}の{部署|ぶしょ}","{人事部|じんじぶ}","{取引先|とりひきさき}"], correct:1, exp:"配属予定の部署で行う."},
  {q:"{第三週|だいさんしゅう}のプログラムに{参加|さんか}するのは{誰|だれ}ですか。", opt:["{全員|ぜんいん}","{希望|きぼう}する{人|ひと}だけ","{営業部|えいぎょうぶ}の{人|ひと}だけ","{誰|だれ}も{参加|さんか}しない"], correct:1, exp:"希望者のみ."},
  {q:"{病気|びょうき}で{休|やす}む{場合|ばあい}は、どうしますか。", opt:["{当日|とうじつ}の{夜|よる}に{連絡|れんらく}する","{前日|ぜんじつ}までに{人事部|じんじぶ}に{連絡|れんらく}する","{連絡|れんらく}しなくてよい","レポートを{出|だ}す"], correct:1, exp:"前日までに人事部に連絡してください."}
 ]}

];

// Arti per kotoba untuk popup Reading. Kunci: kata|bacaan (sama dengan markup {kata|bacaan}).
window.N2_READING_GLOSS = {
  "お金|かね": "uang",
  "その後|そのご": "setelah itu",
  "一か月|いっかげつ": "satu bulan",
  "一人|ひとり": "satu orang",
  "一方|いっぽう": "di sisi lain",
  "一日中|いちにちじゅう": "sepanjang hari",
  "一時間|いちじかん": "satu jam",
  "一般|いっぱん": "umum",
  "七割|ななわり": "70 persen",
  "七日|なのか": "tanggal 7",
  "三|みっ": "tiga (三つ)",
  "三年|さんねん": "tiga tahun",
  "三日坊主|みっかぼうず": "semangat tiga hari",
  "上|あ": "naik",
  "上司|じょうし": "atasan",
  "下|さ": "menurunkan",
  "不満|ふまん": "tidak puas",
  "世代|せだい": "generasi",
  "世話|せわ": "merawat, mengurus",
  "中|ちゅう": "selama",
  "中|なか": "dalam",
  "中学生|ちゅうがくせい": "siswa SMP",
  "予定|よてい": "rencana, jadwal",
  "予約|よやく": "reservasi",
  "事前|じぜん": "sebelumnya",
  "二つ|ふたつ": "dua (benda)",
  "五日|いつか": "tanggal 5",
  "人|ひと": "orang",
  "人事部|じんじぶ": "bagian SDM",
  "今|いま": "sekarang",
  "今後|こんご": "mulai sekarang, ke depannya",
  "今日|きょう": "hari ini",
  "今週|こんしゅう": "minggu ini",
  "仕事|しごと": "pekerjaan",
  "他|ほか": "lain",
  "以下|いか": "di bawah, ke bawah",
  "休|やす": "libur, istirahat (休む)",
  "会|あ": "bertemu (会う)",
  "会場|かいじょう": "tempat acara",
  "会社|かいしゃ": "perusahaan",
  "会議|かいぎ": "rapat",
  "会議室|かいぎしつ": "ruang rapat",
  "住所|じゅうしょ": "alamat",
  "住民|じゅうみん": "penduduk",
  "佐藤|さとう": "Sato (nama)",
  "何|なに": "apa",
  "何|なん": "apa (何ですか)",
  "何時|なんじ": "jam berapa",
  "作|つく": "membuat (作る)",
  "使|つか": "menggunakan (使う)",
  "使用|しよう": "penggunaan",
  "使用量|しようりょう": "jumlah pemakaian",
  "例|れい": "contoh",
  "便利|べんり": "praktis",
  "倉庫|そうこ": "gudang",
  "値段|ねだん": "harga",
  "働|はたら": "bekerja (働く)",
  "先日|せんじつ": "tempo hari",
  "入|はい": "masuk (入る)",
  "入場|にゅうじょう": "masuk",
  "入場料|にゅうじょうりょう": "tiket masuk",
  "全体|ぜんたい": "keseluruhan",
  "全員|ぜんいん": "semua anggota",
  "八時間|はちじかん": "delapan jam",
  "公式|こうしき": "resmi",
  "内|ない": "dalam",
  "内容|ないよう": "isi",
  "円|えん": "yen",
  "写真|しゃしん": "foto",
  "出|だ": "mengeluarkan",
  "出社|しゅっしゃ": "berangkat ke kantor",
  "分|わ": "dibagi (使い分ける)",
  "初|はじ": "pertama (初めて)",
  "別|べつ": "menurut/lain",
  "利用|りよう": "penggunaan",
  "制度|せいど": "sistem",
  "前|まえ": "sebelum, depan",
  "前日|ぜんじつ": "hari sebelumnya",
  "割合|わりあい": "proporsi, persentase",
  "力|ちから": "kekuatan",
  "効果|こうか": "efek",
  "勉強|べんきょう": "belajar",
  "勤務|きんむ": "jam kerja, bertugas",
  "勧|すす": "menganjurkan",
  "区別|くべつ": "pembedaan",
  "十一月|じゅういちがつ": "November",
  "十分|じゅうぶん": "cukup",
  "午前|ごぜん": "pagi (sebelum tengah hari)",
  "午前中|ごぜんちゅう": "pada pagi hari",
  "午後|ごご": "siang/sore (setelah tengah hari)",
  "半分|はんぶん": "setengah",
  "単語|たんご": "kosakata",
  "占|し": "menempati (proporsi)",
  "危険|きけん": "berbahaya (nomina/sifat)",
  "原因|げんいん": "penyebab",
  "参加|さんか": "ikut serta",
  "取|と": "mengambil (取り消す: membatalkan)",
  "取引|とりひき": "transaksi",
  "取引先|とりひきさき": "mitra bisnis",
  "受付|うけつけ": "resepsionis",
  "各地|かくち": "berbagai tempat",
  "各週|かくしゅう": "tiap minggu",
  "同|おな": "sama (同じ)",
  "同伴|どうはん": "membawa serta",
  "同行|どうこう": "menyertai",
  "名前|なまえ": "nama",
  "向|む": "menghadap",
  "商品|しょうひん": "produk",
  "問題|もんだい": "masalah",
  "営業|えいぎょう": "penjualan, buka usaha",
  "営業部|えいぎょうぶ": "departemen penjualan",
  "回|まわ": "sekeliling",
  "国際|こくさい": "internasional",
  "土地|とち": "daerah/tanah",
  "在宅|ざいたく": "di rumah",
  "在庫|ざいこ": "stok",
  "地域|ちいき": "kawasan",
  "地方|ちほう": "daerah",
  "報告|ほうこく": "laporan",
  "場合|ばあい": "kasus, jika",
  "境目|さかいめ": "batas",
  "増|ふ": "bertambah (増える)",
  "壊|こわ": "rusak (壊れる)",
  "声|こえ": "suara",
  "変|か": "berubah (変わる)",
  "多|おお": "banyak (多い)",
  "夜|よる": "malam",
  "夜遅|よるおそ": "larut malam",
  "大|おお": "besar (大きい)",
  "大切|たいせつ": "penting, berharga",
  "大半|たいはん": "sebagian besar",
  "大変|たいへん": "repot, berat",
  "大学生|だいがくせい": "mahasiswa",
  "天気|てんき": "cuaca",
  "失敗|しっぱい": "kegagalan",
  "始|はじ": "memulai (始める)",
  "学生|がくせい": "pelajar, mahasiswa",
  "学生証|がくせいしょう": "kartu mahasiswa",
  "守|まも": "menaati, menjaga (守る)",
  "安|やす": "murah (安い)",
  "定|さだ": "menetapkan",
  "定着|ていちゃく": "menetap",
  "宝|たから": "harta",
  "実習|じっしゅう": "praktik",
  "実際|じっさい": "kenyataan",
  "実験|じっけん": "eksperimen",
  "室|しつ": "ruang",
  "家|いえ": "rumah",
  "家族|かぞく": "keluarga",
  "専門家|せんもんか": "pakar",
  "小|ちい": "kecil (小さい)",
  "少|すく": "sedikit (少ない)",
  "届|とど": "sampai (届く)",
  "展示会|てんじかい": "pameran",
  "展示場|てんじじょう": "gedung pameran",
  "履|は": "memakai (alas kaki)",
  "山田|やまだ": "Yamada (nama keluarga)",
  "差|さ": "selisih",
  "希望|きぼう": "harapan",
  "年齢|ねんれい": "usia",
  "広|ひろ": "luas (広い)",
  "店|みせ": "toko",
  "引|ひ": "menarik; 引っ越す = pindah rumah",
  "弱|よわ": "lemah",
  "当初|とうしょ": "pada awalnya",
  "当日|とうじつ": "hari H",
  "待|ま": "menunggu",
  "後|あと": "setelah",
  "得|え": "mendapat (やむを得ない)",
  "得|とく": "untung",
  "徹夜|てつや": "begadang",
  "心理学|しんりがく": "psikologi",
  "必|かなら": "pasti (必ず)",
  "必要|ひつよう": "perlu",
  "忘|わす": "lupa (忘れる)",
  "思|おも": "berpikir, merasa (思う)",
  "悪|わる": "buruk",
  "情報|じょうほう": "informasi",
  "意味|いみ": "arti",
  "意志|いし": "kemauan",
  "成果|せいか": "hasil",
  "成績|せいせき": "nilai",
  "手順|てじゅん": "prosedur",
  "払|はら": "membayar (払う)",
  "持|も": "membawa, memiliki (持つ)",
  "指摘|してき": "menunjukkan",
  "挙|あ": "mengemukakan",
  "掲|かか": "mengusung",
  "提出|ていしゅつ": "pengumpulan",
  "搬入|はんにゅう": "memasukkan barang",
  "撮|と": "memotret",
  "改善|かいぜん": "perbaikan",
  "数多|かずおお": "banyak sekali",
  "数年|すうねん": "beberapa tahun",
  "整|ととの": "menyiapkan",
  "整理|せいり": "merapikan",
  "文化|ぶんか": "budaya",
  "新|あたら": "baru (新しい)",
  "新入|しんにゅう": "baru masuk",
  "新年|しんねん": "tahun baru",
  "方|かた": "orang (hormat)",
  "方式|ほうしき": "metode",
  "方法|ほうほう": "cara",
  "方言|ほうげん": "dialek",
  "日|にち": "tanggal (〜日)",
  "日|ひ": "hari, tanggal",
  "日時|にちじ": "tanggal dan waktu",
  "明|あき": "jelas (明らか)",
  "明日|あした": "besok",
  "時|じ": "jam (pukul)",
  "時間|じかん": "waktu",
  "普及|ふきゅう": "penyebaran, pemasyarakatan",
  "曖昧|あいまい": "ambigu, tidak jelas",
  "書|か": "menulis (書く)",
  "最初|さいしょ": "pertama, awal",
  "最終日|さいしゅうび": "hari terakhir",
  "最近|さいきん": "belakangan ini",
  "有料|ゆうりょう": "berbayar",
  "有料化|ゆうりょうか": "menjadi berbayar",
  "未定|みてい": "belum ditentukan",
  "来月|らいげつ": "bulan depan",
  "来週|らいしゅう": "minggu depan",
  "東|ひがし": "timur",
  "東京|とうきょう": "Tokyo",
  "東京商事|とうきょうしょうじ": "Tokyo Shoji (nama perusahaan)",
  "株式会社|かぶしきがいしゃ": "perseroan (PT)",
  "案内|あんない": "panduan, informasi",
  "様|さま": "Tuan/Nyonya",
  "標準語|ひょうじゅんご": "bahasa baku",
  "欠席|けっせき": "ketidakhadiran",
  "正|ただ": "benar (正しい)",
  "歩|ある": "berjalan (歩く)",
  "歴史|れきし": "sejarah",
  "残|のこ": "tersisa",
  "毎日|まいにち": "setiap hari",
  "比|くら": "membandingkan",
  "気|き": "perasaan, semangat (気がする = merasa)",
  "水曜日|すいようび": "hari Rabu",
  "求|もと": "menuntut",
  "決|き": "memutuskan",
  "法律|ほうりつ": "hukum",
  "注意|ちゅうい": "perhatian, peringatan",
  "注文|ちゅうもん": "pesanan",
  "消|け": "menghapus",
  "減|へ": "berkurang, mengurangi (減らす)",
  "点|てん": "poin",
  "点検|てんけん": "pemeriksaan",
  "無料|むりょう": "gratis",
  "無断|むだん": "tanpa izin",
  "状態|じょうたい": "keadaan",
  "玄関|げんかん": "pintu masuk",
  "現在|げんざい": "saat ini",
  "現場|げんば": "lokasi kejadian",
  "理由|りゆう": "alasan",
  "環境|かんきょう": "lingkungan",
  "生|う": "melahirkan",
  "生活|せいかつ": "kehidupan",
  "病気|びょうき": "penyakit",
  "登録|とうろく": "pendaftaran",
  "目|め": "mata",
  "目標|もくひょう": "target",
  "眠|ねむ": "mengantuk (眠い・眠る)",
  "睡眠|すいみん": "tidur",
  "知|し": "memberi tahu (知らせ・知らせる)",
  "研修|けんしゅう": "pelatihan",
  "研究|けんきゅう": "penelitian",
  "確|たし": "pasti",
  "確認|かくにん": "pemeriksaan",
  "示|しめ": "menunjukkan",
  "社内|しゃない": "dalam perusahaan",
  "社員|しゃいん": "pegawai",
  "禁止|きんし": "larangan",
  "私|わたし": "saya",
  "移|うつ": "memindahkan",
  "立|た": "menyusun (target)",
  "第一週|だいいっしゅう": "minggu pertama",
  "第三週|だいさんしゅう": "minggu ketiga",
  "第二週|だいにしゅう": "minggu kedua",
  "筆者|ひっしゃ": "penulis",
  "管理|かんり": "pengelolaan",
  "紙|かみ": "kertas",
  "細|こま": "rinci",
  "終|お": "selesai (終わる)",
  "組|く": "menyusun (取り組み: upaya)",
  "組合|くみあい": "perhimpunan",
  "経|た": "berlalu",
  "経験|けいけん": "pengalaman",
  "結果|けっか": "hasil",
  "給料|きゅうりょう": "gaji",
  "絶|た": "terputus/habis",
  "続|つづ": "berlanjut (続く)",
  "縮|ちぢ": "menyusut",
  "繰|く": "mengulang",
  "罰金|ばっきん": "denda",
  "翌日|よくじつ": "keesokan hari",
  "習慣|しゅうかん": "kebiasaan",
  "考|かんが": "berpikir (考える)",
  "者|しゃ": "orang",
  "脳|のう": "otak",
  "自然|しぜん": "alam",
  "良|よ": "baik (良い)",
  "若|わか": "muda",
  "荷物|にもつ": "barang bawaan",
  "行|い": "pergi (行く)",
  "行|おこな": "melakukan",
  "行動|こうどう": "tindakan",
  "表|あらわ": "menyatakan",
  "表|ひょう": "tabel",
  "袋|ふくろ": "kantong",
  "袋|ぶくろ": "kantong",
  "裏|うら": "belakang",
  "見|み": "melihat (見る)",
  "見学|けんがく": "kunjungan belajar",
  "見直|みなお": "meninjau ulang",
  "覚|おぼ": "menghafal, mengingat (覚える)",
  "親|した": "akrab",
  "解決|かいけつ": "penyelesaian",
  "言葉|ことば": "kata, ucapan",
  "記憶|きおく": "ingatan",
  "試食|ししょく": "mencicipi",
  "試験|しけん": "ujian",
  "詫|わ": "permintaan maaf",
  "詰|つ": "penuh terisi",
  "話|はな": "berbicara",
  "説明|せつめい": "penjelasan",
  "誰|だれ": "siapa",
  "調査|ちょうさ": "penyelidikan",
  "負担|ふたん": "beban (biaya)",
  "走|はし": "berlari (走る)",
  "起|お": "terjadi (起きる)",
  "越|こ": "melewati; 引っ越す = pindah rumah",
  "足|た": "cukup",
  "距離|きょり": "jarak",
  "身|み": "tubuh (身の回り: sekitar diri)",
  "車|くるま": "mobil",
  "込|こ": "masuk, mendaftar (申し込み)",
  "近|ちか": "dekat (近く・近い)",
  "返|かえ": "mengembalikan (返す)",
  "迷惑|めいわく": "gangguan",
  "逆効果|ぎゃくこうか": "efek berlawanan",
  "通|つう": "melalui (通じて)",
  "通勤|つうきん": "pulang-pergi kerja",
  "連|つ": "membawa",
  "連絡|れんらく": "menghubungi, kontak",
  "運動|うんどう": "olahraga",
  "過|す": "melewati (過ぎる)",
  "違|ちが": "berbeda",
  "避|さ": "menghindari",
  "部分|ぶぶん": "bagian",
  "部署|ぶしょ": "bagian, departemen",
  "配属|はいぞく": "penempatan",
  "重|かさ": "bertumpuk",
  "重複|ちょうふく": "tumpang tindih",
  "金|きん": "Jumat",
  "金曜日|きんようび": "hari Jumat",
  "長|なが": "panjang, lama (長い)",
  "開|あ": "terbuka, buka (開く)",
  "開催|かいさい": "penyelenggaraan",
  "開始|かいし": "permulaan",
  "間|あいだ": "selama, di antara",
  "間|かん": "selama",
  "間違|まちが": "salah",
  "関係|かんけい": "hubungan",
  "関心|かんしん": "minat",
  "階段|かいだん": "tangga",
  "隠|かく": "tersembunyi",
  "集|あつ": "berkumpul",
  "難|むずか": "sulit (難しい)",
  "雪|ゆき": "salju",
  "電話|でんわ": "telepon",
  "靴|くつ": "sepatu",
  "頼|たの": "meminta, memesan (頼む/頼まれる)",
  "願|ねが": "memohon (お願いします)",
  "食品|しょくひん": "produk makanan",
  "高|たか": "tinggi, mahal (高い)",
  "魅力|みりょく": "daya tarik"
};
