// ===================================================================
// Qategori Nihongo - Reading (読解) JLPT N1
// Furigana: {漢字|かんじ} (kata dalam kurung kurawal, bacaan setelah |)
// tipe: tanbun (bacaan pendek), chuubun (menengah), jouhou (pencarian informasi)
// ===================================================================
window.N1_READING = [

{id:"n1r01", tipe:"tanbun", topik:"Opini",
 judul:"{効率|こうりつ}と{余白|よはく}",
 teks:"{現代|げんだい}の{職場|しょくば}では、{無駄|むだ}を{省|はぶ}き、{効率|こうりつ}を{高|たか}めることが{絶対|ぜったい}の{善|ぜん}とされがちだ。しかし、すべての{時間|じかん}を{成果|せいか}に{結|むす}びつけようとする{姿勢|しせい}は、かえって{創造性|そうぞうせい}を{損|そこ}なう{恐|おそ}れがある。{新|あたら}しい{発想|はっそう}は、{一見|いっけん}{無意味|むいみ}に{思|おも}える{雑談|ざつだん}や{散歩|さんぽ}の{最中|さいちゅう}に{生|う}まれることが{少|すく}なくないからだ。{余白|よはく}のない{計画|けいかく}は、{予期|よき}せぬ{事態|じたい}への{対応力|たいおうりょく}をも{奪|うば}ってしまう。{効率|こうりつ}を{追|お}い{求|もと}めるあまり、{本来|ほんらい}の{目的|もくてき}を{見失|みうしな}っては{本末転倒|ほんまつてんとう}と{言|い}わざるを{得|え}ない。",
 terjemahan:"Di tempat kerja modern, menghilangkan pemborosan dan meningkatkan efisiensi cenderung dianggap kebaikan mutlak. Namun sikap yang berusaha mengaitkan seluruh waktu dengan hasil justru dikhawatirkan merusak kreativitas. Ide baru tak jarang lahir di tengah obrolan atau jalan-jalan yang sekilas tampak tak bermakna. Rencana tanpa ruang longgar juga merampas daya tanggap terhadap keadaan tak terduga. Jika karena mengejar efisiensi kita kehilangan tujuan semula, maka itu terpaksa disebut membalik prioritas.",
 soal:[
  {q:"{筆者|ひっしゃ}は、{効率|こうりつ}を{重視|じゅうし}しすぎることをどう{考|かんが}えていますか。", opt:["{創造性|そうぞうせい}を{損|そこ}なう{可能性|かのうせい}がある","{必ず|かならず}{成果|せいか}につながる","{誰|だれ}にとっても{必要|ひつよう}だ","{職場|しょくば}の{雰囲気|ふんいき}を{良|よ}くする"], correct:0, exp:"かえって創造性を損なう恐れがある."},
  {q:"{新|あたら}しい{発想|はっそう}は、どんな{時|とき}に{生|う}まれやすいと{述|の}べていますか。", opt:["{会議|かいぎ}の{最中|さいちゅう}","{無意味|むいみ}に{見|み}える{雑談|ざつだん}や{散歩|さんぽ}の{時|とき}","{残業|ざんぎょう}の{時|とき}","{計画|けいかく}を{立|た}てる{時|とき}"], correct:1, exp:"一見無意味に思える雑談や散歩の最中に生まれることが少なくない."},
  {q:"「{本末転倒|ほんまつてんとう}」とは、ここでは{何|なに}を{指|さ}していますか。", opt:["{目的|もくてき}を{見失|みうしな}って{手段|しゅだん}にとらわれること","{計画|けいかく}を{立|た}てないこと","{成果|せいか}を{出|だ}しすぎること","{他人|たにん}に{頼|たよ}ること"], correct:0, exp:"効率を追い求めるあまり本来の目的を見失うこと."}
 ]},

{id:"n1r02", tipe:"tanbun", topik:"Berita",
 judul:"{高齢化|こうれいか}と{地方|ちほう}{鉄道|てつどう}",
 teks:"{地方|ちほう}の{鉄道|てつどう}{路線|ろせん}は、{人口|じんこう}{減少|げんしょう}に{伴|ともな}う{利用者|りようしゃ}の{減少|げんしょう}により、{存続|そんぞく}の{危機|きき}に{直面|ちょくめん}している。{赤字|あかじ}{路線|ろせん}を{廃止|はいし}すべきだという{意見|いけん}がある{一方|いっぽう}、{高齢者|こうれいしゃ}や{学生|がくせい}にとって{欠|か}かせない{足|あし}であることも{事実|じじつ}だ。{自治体|じちたい}は、{運行|うんこう}{本数|ほんすう}を{減|へ}らしつつバスと{連携|れんけい}させるなど、{地域|ちいき}の{実情|じつじょう}に{合|あ}った{方策|ほうさく}を{模索|もさく}している。{単純|たんじゅん}な{採算|さいさん}だけで{判断|はんだん}せず、{地域|ちいき}{全体|ぜんたい}の{活力|かつりょく}を{維持|いじ}する{視点|してん}が{求|もと}められている。",
 terjemahan:"Jalur kereta daerah menghadapi ancaman kelangsungan akibat penurunan penumpang seiring menyusutnya penduduk. Ada pendapat bahwa jalur merugi harus dihapus, tetapi memang fakta bahwa jalur itu sarana vital bagi lansia dan pelajar. Pemerintah daerah menjajaki langkah sesuai kondisi setempat, misalnya mengurangi frekuensi sambil mengaitkannya dengan bus. Dibutuhkan sudut pandang untuk menjaga vitalitas seluruh daerah, tak hanya menilai untung rugi sederhana.",
 soal:[
  {q:"{地方|ちほう}{鉄道|てつどう}が{危機|きき}にある{原因|げんいん}は{何|なん}ですか。", opt:["{事故|じこ}が{多|おお}いこと","{利用者|りようしゃ}が{減|へ}っていること","{運賃|うんちん}が{安|やす}いこと","{駅|えき}が{古|ふる}いこと"], correct:1, exp:"人口減少に伴う利用者の減少."},
  {q:"{自治体|じちたい}は、どのような{対応|たいおう}を{試|こころ}みていますか。", opt:["{路線|ろせん}をすべて{廃止|はいし}する","{運行|うんこう}{本数|ほんすう}を{減|へ}らしてバスと{連携|れんけい}させる","{運賃|うんちん}を{二倍|にばい}にする","{何|なに}もしない"], correct:1, exp:"運行本数を減らしつつバスと連携させる."},
  {q:"{筆者|ひっしゃ}の{考|かんが}えに{近|ちか}いのはどれですか。", opt:["{採算|さいさん}だけで{判断|はんだん}すべきだ","{地域|ちいき}{全体|ぜんたい}の{活力|かつりょく}を{見|み}る{視点|してん}が{必要|ひつよう}だ","{鉄道|てつどう}は{全部|ぜんぶ}{残|のこ}すべきだ","バスは{不要|ふよう}だ"], correct:1, exp:"地域全体の活力を維持する視点が求められている."}
 ]},

{id:"n1r03", tipe:"tanbun", topik:"Kritik",
 judul:"{情報|じょうほう}{過多|かた}の{時代|じだい}に",
 teks:"インターネットの{普及|ふきゅう}により、{私|わたし}たちはかつてないほど{大量|たいりょう}の{情報|じょうほう}に{触|ふ}れられるようになった。だが、{情報|じょうほう}が{増|ふ}えたからといって、{物事|ものごと}の{理解|りかい}が{深|ふか}まるとは{限|かぎ}らない。むしろ、{断片的|だんぺんてき}な{知識|ちしき}を{寄|よ}せ{集|あつ}めただけで{分|わ}かった{気|き}になる{危険|きけん}が{高|たか}まっている。{重要|じゅうよう}なのは、{情報|じょうほう}の{量|りょう}ではなく、それを{批判的|ひはんてき}に{吟味|ぎんみ}し、{自|みずか}らの{頭|あたま}で{考|かんが}え{抜|ぬ}く{力|ちから}である。",
 terjemahan:"Dengan meluasnya internet, kita dapat menyentuh informasi dalam jumlah yang belum pernah ada. Namun, bertambahnya informasi tak berarti pemahaman semakin dalam. Justru bahaya merasa paham hanya dengan mengumpulkan pengetahuan serpihan makin meningkat. Yang penting bukan jumlah informasi, melainkan kemampuan menelaahnya secara kritis dan memikirkannya hingga tuntas dengan kepala sendiri.",
 soal:[
  {q:"{筆者|ひっしゃ}が{指摘|してき}している{危険|きけん}は{何|なん}ですか。", opt:["{情報|じょうほう}が{手|て}に{入|はい}らないこと","{断片的|だんぺんてき}な{知識|ちしき}で{分|わ}かった{気|き}になること","インターネットが{使|つか}えないこと","{学校|がっこう}に{行|い}かなくなること"], correct:1, exp:"断片的な知識を寄せ集めただけで分かった気になる危険."},
  {q:"{筆者|ひっしゃ}が{重要|じゅうよう}だと{考|かんが}えているのは{何|なん}ですか。", opt:["{情報|じょうほう}の{量|りょう}","{批判的|ひはんてき}に{吟味|ぎんみ}して{自分|じぶん}で{考|かんが}える{力|ちから}","{検索|けんさく}の{速|はや}さ","{他人|たにん}の{意見|いけん}に{従|したが}うこと"], correct:1, exp:"情報を批判的に吟味し、自らの頭で考え抜く力."}
 ]},

{id:"n1r04", tipe:"tanbun", topik:"Surel resmi",
 judul:"{契約|けいやく}{更新|こうしん}に{関|かん}するお{願|ねが}い",
 teks:"拝啓　{時下|じか}ますますご{清栄|せいえい}のこととお{慶|よろこ}び{申|もう}し{上|あ}げます。さて、貴社との{業務|ぎょうむ}{委託|いたく}{契約|けいやく}は、{来月末|らいげつまつ}をもって{満了|まんりょう}いたします。つきましては、{更新|こうしん}に{先立|さきだ}ち、{条件|じょうけん}の{見直|みなお}しについて{協議|きょうぎ}の{場|ば}を{設|もう}けさせていただきたく、ご{多忙|たぼう}のところ{恐縮|きょうしゅく}ですが、{来週|らいしゅう}{中|ちゅう}にご{都合|つごう}の{良|よ}い{日時|にちじ}をお{知|し}らせいただければ{幸|さいわ}いです。なお、{更新|こうしん}の{意思|いし}がない{場合|ばあい}は、その{旨|むね}を{書面|しょめん}にてご{連絡|れんらく}ください。　敬具",
 terjemahan:"Dengan hormat, semoga Bapak/Ibu senantiasa dalam keadaan sehat. Kontrak alih daya pekerjaan dengan perusahaan Anda akan berakhir pada akhir bulan depan. Sehubungan dengan itu, sebelum pembaruan, kami ingin mengadakan pertemuan membahas peninjauan syarat; mohon maaf mengganggu kesibukan, kami berharap Anda memberi tahu waktu yang sesuai dalam minggu depan. Bila tidak berniat memperbarui, mohon kabari secara tertulis. Hormat kami.",
 soal:[
  {q:"この{手紙|てがみ}の{目的|もくてき}は{何|なん}ですか。", opt:["{契約|けいやく}を{解除|かいじょ}すること","{更新|こうしん}の{前|まえ}に{条件|じょうけん}を{話|はな}し{合|あ}う{日|ひ}を{決|き}めたい","{新|あたら}しい{取引|とりひき}を{始|はじ}めたい","{支払|しはら}いを{催促|さいそく}したい"], correct:1, exp:"更新に先立ち、条件の見直しについて協議の場を設けたい."},
  {q:"{相手|あいて}は、いつまでに{返事|へんじ}をすればよいですか。", opt:["{来月末|らいげつまつ}","{来週中|らいしゅうちゅう}","{今日中|きょうじゅう}","{決|き}まっていない"], correct:1, exp:"来週中にご都合の良い日時をお知らせ."},
  {q:"{更新|こうしん}しない{場合|ばあい}は、どうしますか。", opt:["{何|なに}もしなくてよい","{書面|しょめん}で{連絡|れんらく}する","{電話|でんわ}で{断|ことわ}る","{来月末|らいげつまつ}まで{待|ま}つ"], correct:1, exp:"その旨を書面にてご連絡ください."}
 ]},

{id:"n1r05", tipe:"chuubun", topik:"Esai",
 judul:"{翻訳|ほんやく}の{限界|げんかい}",
 teks:"{翻訳|ほんやく}とは、ある{言語|げんご}で{書|か}かれた{内容|ないよう}を{別|べつ}の{言語|げんご}に{置|お}き{換|か}える{作業|さぎょう}だと{考|かんが}えられがちだ。しかし、{実際|じっさい}には{単語|たんご}を{一対一|いちたいいち}で{対応|たいおう}させれば{済|す}むほど{単純|たんじゅん}ではない。たとえば、{日本語|にほんご}の「もったいない」には、{物|もの}を{大切|たいせつ}にする{心|こころ}と{惜|お}しむ{気持|きも}ちが{同時|どうじ}に{含|ふく}まれており、{他|ほか}の{言語|げんご}に{一語|いちご}で{訳|やく}すのは{難|むずか}しい。{翻訳者|ほんやくしゃ}は、{言葉|ことば}の{背後|はいご}にある{文化|ぶんか}や{感情|かんじょう}までを{汲|く}み{取|と}り、{読者|どくしゃ}に{伝|つた}わる{形|かたち}に{再構築|さいこうちく}しなければならない。その{意味|いみ}で、{翻訳|ほんやく}は{単|たん}なる{置|お}き{換|か}えではなく、{一種|いっしゅ}の{創作|そうさく}であるとも{言|い}える。",
 terjemahan:"Terjemahan sering dianggap pekerjaan mengalihkan isi yang ditulis dalam suatu bahasa ke bahasa lain. Namun kenyataannya tidak sesederhana sekadar mencocokkan kata satu lawan satu. Misalnya, 'mottainai' dalam bahasa Jepang mengandung sekaligus hati yang menghargai benda dan rasa sayang atas pemborosan, sehingga sulit diterjemahkan dengan satu kata di bahasa lain. Penerjemah harus menangkap budaya dan perasaan di balik kata, lalu menyusunnya kembali dalam bentuk yang sampai kepada pembaca. Dalam arti itu, terjemahan bukan sekadar penggantian, melainkan semacam penciptaan.",
 soal:[
  {q:"{筆者|ひっしゃ}は、{翻訳|ほんやく}についてどう{考|かんが}えていますか。", opt:["{単語|たんご}を{置|お}き{換|か}えるだけでよい","{単純|たんじゅん}な{置|お}き{換|か}えではない","{機械|きかい}に{任|まか}せるべきだ","{必要|ひつよう}ない"], correct:1, exp:"単語を一対一で対応させれば済むほど単純ではない."},
  {q:"「もったいない」は{何|なに}の{例|れい}として{挙|あ}げられていますか。", opt:["{簡単|かんたん}に{訳|やく}せる{言葉|ことば}","{一語|いちご}で{訳|やく}しにくい{言葉|ことば}","{古|ふる}い{言葉|ことば}","{新|あたら}しい{言葉|ことば}"], correct:1, exp:"他の言語に一語で訳すのは難しい例."},
  {q:"{翻訳者|ほんやくしゃ}に{求|もと}められることは{何|なん}ですか。", opt:["{文化|ぶんか}や{感情|かんじょう}を{汲|く}み{取|と}って{再構築|さいこうちく}する","{原文|げんぶん}を{変|か}えない","{辞書|じしょ}を{使|つか}わない","{速|はや}く{訳|やく}す"], correct:0, exp:"言葉の背後にある文化や感情を汲み取り、再構築する."}
 ]},

{id:"n1r06", tipe:"chuubun", topik:"Ekonomi",
 judul:"{賃金|ちんぎん}{上昇|じょうしょう}と{物価|ぶっか}",
 teks:"{近年|きんねん}、{企業|きぎょう}が{従業員|じゅうぎょういん}の{賃金|ちんぎん}を{引|ひ}き{上|あ}げる{動|うご}きが{広|ひろ}がっている。{背景|はいけい}には、{深刻|しんこく}な{人手|ひとで}{不足|ぶそく}がある。{優秀|ゆうしゅう}な{人材|じんざい}を{確保|かくほ}するには、{待遇|たいぐう}の{改善|かいぜん}が{避|さ}けて{通|とお}れないからだ。しかし、{賃金|ちんぎん}が{上|あ}がっても、それを{上回|うわまわ}る{勢|いきお}いで{物価|ぶっか}が{上昇|じょうしょう}すれば、{家計|かけい}の{実質|じっしつ}的な{購買力|こうばいりょく}はむしろ{低下|ていか}してしまう。{専門家|せんもんか}は、{賃金|ちんぎん}と{物価|ぶっか}が{好循環|こうじゅんかん}を{描|えが}くためには、{企業|きぎょう}の{生産性|せいさんせい}の{向上|こうじょう}が{不可欠|ふかけつ}だと{指摘|してき}する。{単|たん}なる{価格|かかく}{転嫁|てんか}では、{一時的|いちじてき}な{賃上|ちんあ}げに{終|お}わりかねない。",
 terjemahan:"Belakangan ini gerakan perusahaan menaikkan upah karyawan meluas. Latar belakangnya adalah kekurangan tenaga kerja yang serius, karena untuk mendapatkan SDM unggul, perbaikan perlakuan tak terhindarkan. Namun, meski upah naik, bila harga naik lebih cepat, daya beli riil rumah tangga justru menurun. Pakar menunjuk bahwa agar upah dan harga membentuk lingkaran baik, peningkatan produktivitas perusahaan mutlak. Sekadar membebankan ke harga bisa berakhir hanya sebagai kenaikan upah sementara.",
 soal:[
  {q:"{企業|きぎょう}が{賃金|ちんぎん}を{上|あ}げている{背景|はいけい}は{何|なん}ですか。", opt:["{利益|りえき}が{減|へ}ったから","{人手|ひとで}{不足|ぶそく}があるから","{法律|ほうりつ}が{変|か}わったから","{景気|けいき}が{悪|わる}いから"], correct:1, exp:"背景には深刻な人手不足がある."},
  {q:"{物価|ぶっか}の{上昇|じょうしょう}が{賃金|ちんぎん}を{上回|うわまわ}ると、どうなりますか。", opt:["{購買力|こうばいりょく}が{上|あ}がる","{購買力|こうばいりょく}が{下|さ}がる","{変|か}わらない","{貯金|ちょきん}が{増|ふ}える"], correct:1, exp:"実質的な購買力はむしろ低下してしまう."},
  {q:"{専門家|せんもんか}が{不可欠|ふかけつ}だと{言|い}っているのは{何|なん}ですか。", opt:["{価格|かかく}を{上|あ}げること","{企業|きぎょう}の{生産性|せいさんせい}の{向上|こうじょう}","{輸入|ゆにゅう}を{減|へ}らすこと","{税金|ぜいきん}を{上|あ}げること"], correct:1, exp:"企業の生産性の向上が不可欠."}
 ]},

{id:"n1r07", tipe:"chuubun", topik:"Sains",
 judul:"AIと{創造性|そうぞうせい}",
 teks:"{人工知能|じんこうちのう}が{絵|え}を{描|か}き、{文章|ぶんしょう}を{書|か}く{時代|じだい}になった。これを{受|う}けて、「{人間|にんげん}の{創造性|そうぞうせい}はもはや{不要|ふよう}になるのか」という{議論|ぎろん}が{起|お}きている。{確|たし}かに、AIは{膨大|ぼうだい}なデータからパターンを{学|まな}び、それらしい{作品|さくひん}を{生|う}み{出|だ}すことに{長|た}けている。だが、{何|なに}を{美|うつく}しいと{感|かん}じ、{何|なに}を{伝|つた}えたいと{願|ねが}うかという{動機|どうき}は、{人間|にんげん}{自身|じしん}の{経験|けいけん}に{根差|ねざ}している。AIを{脅威|きょうい}と{見|み}るか、{道具|どうぐ}として{使|つか}いこなすか。問われているのは、{技術|ぎじゅつ}そのものよりも、それを{使|つか}う{人間|にんげん}の{姿勢|しせい}であろう。",
 terjemahan:"Telah tiba zaman ketika kecerdasan buatan menggambar dan menulis. Menanggapinya muncul perdebatan apakah kreativitas manusia akan tidak diperlukan lagi. Memang AI mahir mempelajari pola dari data raksasa dan menghasilkan karya yang mirip asli. Namun motif tentang apa yang dirasa indah dan apa yang ingin disampaikan berakar pada pengalaman manusia sendiri. Apakah AI dipandang sebagai ancaman atau dimanfaatkan sebagai alat? Yang dipertanyakan mungkin bukan teknologinya, melainkan sikap manusia yang memakainya.",
 soal:[
  {q:"AIが{得意|とくい}なことは{何|なん}ですか。", opt:["{自分|じぶん}の{経験|けいけん}から{作品|さくひん}を{作|つく}ること","データからパターンを{学|まな}んで{作品|さくひん}を{作|つく}ること","{美|うつく}しさを{感|かん}じること","{伝|つた}えたい{気持|きも}ちを{持|も}つこと"], correct:1, exp:"膨大なデータからパターンを学び、作品を生み出すことに長けている."},
  {q:"{人間|にんげん}の{創造性|そうぞうせい}の{動機|どうき}は{何|なに}に{根差|ねざ}していますか。", opt:["{技術|ぎじゅつ}","{人間|にんげん}{自身|じしん}の{経験|けいけん}","{お金|かね}","AI"], correct:1, exp:"人間自身の経験に根差している."},
  {q:"{筆者|ひっしゃ}は{何|なに}が{問|と}われていると{考|かんが}えていますか。", opt:["{技術|ぎじゅつ}の{性能|せいのう}","{使|つか}う{人間|にんげん}の{姿勢|しせい}","AIの{値段|ねだん}","{作品|さくひん}の{数|かず}"], correct:1, exp:"技術そのものよりも、それを使う人間の姿勢."}
 ]},

{id:"n1r08", tipe:"chuubun", topik:"Budaya",
 judul:"{沈黙|ちんもく}の{文化|ぶんか}",
 teks:"{日本|にほん}の{会話|かいわ}では、{沈黙|ちんもく}は{必|かなら}ずしも{気|き}まずいものではない。{相手|あいて}の{言葉|ことば}を{受|う}け{止|と}め、{考|かんが}える{間|ま}として{尊重|そんちょう}される{場面|ばめん}も{多|おお}い。{欧米|おうべい}では{会話|かいわ}が{途切|とぎ}れること{自体|じたい}を{避|さ}けようとする{傾向|けいこう}が{強|つよ}いと{言|い}われ、この{違|ちが}いが{異文化|いぶんか}{間|かん}の{誤解|ごかい}を{招|まね}くことがある。{一方|いっぽう}が{誠実|せいじつ}に{考|かんが}えているつもりの{沈黙|ちんもく}が、もう{一方|いっぽう}には{無関心|むかんしん}や{拒絶|きょぜつ}と{映|うつ}るのである。{互|たが}いの{前提|ぜんてい}が{異|こと}なることを{理解|りかい}したうえで{対話|たいわ}に{臨|のぞ}む{姿勢|しせい}が、{国際|こくさい}{交流|こうりゅう}には{欠|か}かせない。",
 terjemahan:"Dalam percakapan Jepang, keheningan belum tentu canggung. Banyak situasi di mana keheningan dihargai sebagai jeda untuk menerima kata lawan bicara dan berpikir. Di Barat dikatakan kecenderungan menghindari terputusnya percakapan kuat, dan perbedaan ini dapat menimbulkan salah paham antarbudaya. Keheningan yang di satu pihak dimaksudkan sebagai berpikir tulus, di pihak lain tampak sebagai ketidakpedulian atau penolakan. Sikap menghadapi dialog dengan memahami bahwa premis masing-masing berbeda sangat diperlukan dalam pertukaran internasional.",
 soal:[
  {q:"{日本|にほん}の{会話|かいわ}で、{沈黙|ちんもく}はどのように{捉|とら}えられることがありますか。", opt:["{必|かなら}ず{気|き}まずいもの","{考|かんが}える{間|ま}として{尊重|そんちょう}される","{失礼|しつれい}なこと","{怒|おこ}りの{表|あらわ}れ"], correct:1, exp:"相手の言葉を受け止め、考える間として尊重される."},
  {q:"{異文化|いぶんか}{間|かん}の{誤解|ごかい}は、なぜ{起|お}こりますか。", opt:["{言語|げんご}が{違|ちが}うから","{沈黙|ちんもく}の{受|う}け{止|と}め{方|かた}が{違|ちが}うから","{声|こえ}が{小|ちい}さいから","{時間|じかん}がないから"], correct:1, exp:"一方の誠実な沈黙が、他方には無関心や拒絶に映る."},
  {q:"{国際|こくさい}{交流|こうりゅう}に{欠|か}かせないことは{何|なん}ですか。", opt:["{沈黙|ちんもく}を{避|さ}けること","{互|たが}いの{前提|ぜんてい}の{違|ちが}いを{理解|りかい}して{対話|たいわ}すること","{同|おな}じ{言語|げんご}で{話|はな}すこと","{早|はや}く{話|はな}すこと"], correct:1, exp:"互いの前提が異なることを理解したうえで対話に臨む姿勢."}
 ]},

{id:"n1r09", tipe:"jouhou", topik:"Panduan",
 judul:"{奨学金|しょうがくきん}の{募集|ぼしゅう}{要項|ようこう}",
 teks:"【{対象|たいしょう}】{大学院|だいがくいん}の{修士|しゅうし}{課程|かてい}に{在籍|ざいせき}する{留学生|りゅうがくせい}（{成績|せいせき}{上位|じょうい}{三割|さんわり}{以内|いない}）\n【{給付|きゅうふ}{額|がく}】{月額|げつがく}{八万円|はちまんえん}（{返還|へんかん}{不要|ふよう}）　【{期間|きかん}】{最長|さいちょう}{二年|にねん}\n【{応募|おうぼ}{書類|しょるい}】{申請書|しんせいしょ}、{成績|せいせき}{証明書|しょうめいしょ}、{指導|しどう}{教員|きょういん}の{推薦書|すいせんしょ}、{研究|けんきゅう}{計画書|けいかくしょ}\n【{締切|しめきり}】{十一月|じゅういちがつ}{三十日|さんじゅうにち}（{消印|けしいん}{有効|ゆうこう}）\n【{注意|ちゅうい}】{他|ほか}の{奨学金|しょうがくきん}と{併給|へいきゅう}する{場合|ばあい}は、{事前|じぜん}に{申告|しんこく}すること。{虚偽|きょぎ}の{記載|きさい}が{判明|はんめい}した{場合|ばあい}は、{採用|さいよう}を{取|と}り{消|け}す。",
 terjemahan:"[Sasaran] Mahasiswa asing program magister yang terdaftar (nilai 30 persen teratas)\n[Besaran] 80.000 yen/bulan (tak perlu dikembalikan) [Masa] maksimal 2 tahun\n[Berkas] Formulir, transkrip, surat rekomendasi dosen pembimbing, rencana penelitian\n[Batas] 30 November (cap pos berlaku)\n[Catatan] Bila menerima beasiswa lain bersamaan, laporkan lebih dulu. Bila ditemukan data palsu, penerimaan dibatalkan.",
 soal:[
  {q:"この{奨学金|しょうがくきん}に{応募|おうぼ}できるのは{誰|だれ}ですか。", opt:["{日本人|にほんじん}の{学部生|がくぶせい}","{成績|せいせき}が{上位|じょうい}の{修士|しゅうし}{課程|かてい}の{留学生|りゅうがくせい}","{博士|はくし}{課程|かてい}の{学生|がくせい}","{誰|だれ}でもよい"], correct:1, exp:"修士課程に在籍する留学生で成績上位三割以内."},
  {q:"{必要|ひつよう}な{書類|しょるい}でないものはどれですか。", opt:["{申請書|しんせいしょ}","{推薦書|すいせんしょ}","{健康|けんこう}{診断書|しんだんしょ}","{研究|けんきゅう}{計画書|けいかくしょ}"], correct:2, exp:"健康診断書は応募書類に含まれていない."},
  {q:"{虚偽|きょぎ}の{記載|きさい}が{見|み}つかったら、どうなりますか。", opt:["{注意|ちゅうい}される","{採用|さいよう}が{取|と}り{消|け}される","{金額|きんがく}が{減|へ}る","{何|なに}もない"], correct:1, exp:"採用を取り消す."}
 ]},

{id:"n1r10", tipe:"jouhou", topik:"Pengumuman",
 judul:"{市民|しみん}{講座|こうざ}「{防災|ぼうさい}と{地域|ちいき}の{絆|きずな}」",
 teks:"【{日時|にちじ}】{十二月|じゅうにがつ}{十日|とおか}（{土|ど}）　{午後|ごご}1{時|じ}〜4{時|じ}\n【{会場|かいじょう}】{市民|しみん}{文化|ぶんか}{会館|かいかん}　{大|だい}ホール（{定員|ていいん}{三百名|さんびゃくめい}・{先着|せんちゃく}{順|じゅん}）\n【{内容|ないよう}】　{第一部|だいいちぶ}　{講演|こうえん}「{過去|かこ}の{災害|さいがい}から{学|まな}ぶ」\n　　　　　　{第二部|だいにぶ}　{体験|たいけん}{型|がた}{訓練|くんれん}（{応急|おうきゅう}{処置|しょち}・{避難所|ひなんじょ}{運営|うんえい}）\n【{参加費|さんかひ}】{無料|むりょう}（{事前|じぜん}{申込|もうしこみ}{必要|ひつよう}）\n【{備考|びこう}】{動|うご}きやすい{服装|ふくそう}でお{越|こ}しください。{託児|たくじ}{希望|きぼう}の{方|かた}は、{一週間|いっしゅうかん}{前|まえ}までにお{申|もう}し{出|で}ください。",
 terjemahan:"[Waktu] 10 Desember (Sab), 13.00–16.00\n[Tempat] Aula Besar Balai Budaya Kota (kapasitas 300, siapa cepat dapat)\n[Isi] Bagian 1: Ceramah 'Belajar dari bencana masa lalu'; Bagian 2: Latihan praktik (pertolongan pertama, pengelolaan pos pengungsian)\n[Biaya] Gratis (wajib mendaftar lebih dulu)\n[Catatan] Mohon datang dengan pakaian yang leluasa bergerak. Yang menginginkan penitipan anak, mohon mengajukan paling lambat seminggu sebelumnya.",
 soal:[
  {q:"この{講座|こうざ}に{参加|さんか}するために、{必要|ひつよう}なことは{何|なん}ですか。", opt:["{参加費|さんかひ}を{払|はら}う","{事前|じぜん}に{申|もう}し{込|こ}む","{推薦|すいせん}をもらう","{何|なに}も{要|い}らない"], correct:1, exp:"参加費は無料だが、事前申込が必要."},
  {q:"{第二部|だいにぶ}では、{何|なに}をしますか。", opt:["{講演|こうえん}を{聞|き}く","{体験|たいけん}{型|がた}の{訓練|くんれん}をする","{試験|しけん}を{受|う}ける","{食事|しょくじ}をする"], correct:1, exp:"体験型訓練（応急処置・避難所運営）."},
  {q:"{子|こ}どもを{預|あず}けたい{人|ひと}は、どうすればいいですか。", opt:["{当日|とうじつ}{申|もう}し{出|で}る","{一週間|いっしゅうかん}{前|まえ}までに{申|もう}し{出|で}る","{預|あず}けられない","{前日|ぜんじつ}に{電話|でんわ}する"], correct:1, exp:"託児希望の方は、一週間前までにお申し出ください."}
 ]}

];

// Arti per kotoba untuk popup Reading. Kunci: kata|bacaan (sama dengan markup {kata|bacaan}).
window.N1_READING_GLOSS = {
  "お金|かね": "uang",
  "一対一|いちたいいち": "satu lawan satu",
  "一方|いっぽう": "di sisi lain",
  "一時的|いちじてき": "sementara",
  "一種|いっしゅ": "semacam",
  "一見|いっけん": "sekilas",
  "一語|いちご": "satu kata",
  "一週間|いっしゅうかん": "satu minggu",
  "三割|さんわり": "30 persen",
  "三十日|さんじゅうにち": "tanggal 30",
  "三百名|さんびゃくめい": "300 orang",
  "上|あ": "naik",
  "上位|じょうい": "peringkat atas",
  "上回|うわまわ": "melampaui",
  "上昇|じょうしょう": "kenaikan",
  "下|さ": "turun",
  "不可欠|ふかけつ": "sangat penting, tak tergantikan",
  "不要|ふよう": "tak perlu",
  "不足|ぶそく": "kekurangan",
  "中|ちゅう": "selama",
  "予期|よき": "memperkirakan",
  "事前|じぜん": "sebelumnya",
  "事実|じじつ": "fakta",
  "事態|じたい": "keadaan",
  "事故|じこ": "kecelakaan",
  "二倍|にばい": "dua kali lipat",
  "二年|にねん": "dua tahun",
  "互|たが": "satu sama lain",
  "交流|こうりゅう": "pertukaran",
  "人|ひと": "orang",
  "人口|じんこう": "populasi",
  "人工知能|じんこうちのう": "kecerdasan buatan",
  "人手|ひとで": "tenaga kerja",
  "人材|じんざい": "SDM",
  "人間|にんげん": "manusia",
  "今日中|きょうじゅう": "hari ini juga",
  "他|ほか": "lain",
  "他人|たにん": "orang lain",
  "以内|いない": "dalam",
  "任|まか": "mempercayakan (任される)",
  "企業|きぎょう": "perusahaan",
  "会場|かいじょう": "tempat acara",
  "会話|かいわ": "percakapan",
  "会議|かいぎ": "rapat",
  "会館|かいかん": "balai",
  "伝|つた": "menyampaikan",
  "伴|ともな": "menyertai",
  "低下|ていか": "penurunan",
  "体験|たいけん": "pengalaman langsung",
  "何|なに": "apa",
  "何|なん": "apa (何ですか)",
  "余白|よはく": "ruang longgar",
  "作|つく": "membuat (作る)",
  "作品|さくひん": "karya",
  "作業|さぎょう": "pekerjaan",
  "併給|へいきゅう": "menerima bersamaan",
  "使|つか": "menggunakan (使う)",
  "例|れい": "contoh",
  "価格|かかく": "harga",
  "修士|しゅうし": "magister",
  "値段|ねだん": "harga",
  "健康|けんこう": "kesehatan",
  "備考|びこう": "catatan",
  "催促|さいそく": "menagih",
  "傾向|けいこう": "kecenderungan, tren",
  "優秀|ゆうしゅう": "unggul",
  "先着|せんちゃく": "siapa cepat",
  "先立|さきだ": "mendahului",
  "入|はい": "masuk (入る)",
  "全体|ぜんたい": "keseluruhan",
  "全部|ぜんぶ": "semuanya",
  "八万円|はちまんえん": "80.000 yen",
  "内容|ないよう": "isi",
  "再構築|さいこうちく": "menyusun ulang",
  "処置|しょち": "penanganan",
  "出|だ": "mengeluarkan",
  "出|で": "keluar, hadir (出る)",
  "分|わ": "dibagi (使い分ける)",
  "判断|はんだん": "penilaian",
  "判明|はんめい": "terungkap",
  "別|べつ": "lain",
  "利用者|りようしゃ": "pengguna",
  "利益|りえき": "laba",
  "前|まえ": "sebelum, depan",
  "前提|ぜんてい": "premis, prasyarat",
  "前日|ぜんじつ": "hari sebelumnya",
  "創作|そうさく": "penciptaan",
  "創造性|そうぞうせい": "kreativitas",
  "力|ちから": "kekuatan",
  "効率|こうりつ": "efisiensi",
  "動|うご": "bergerak, menyala (動く)",
  "動機|どうき": "motif",
  "募集|ぼしゅう": "rekrutmen",
  "勢|いきお": "semangat/laju",
  "十一月|じゅういちがつ": "November",
  "十二月|じゅうにがつ": "Desember",
  "十日|とおか": "tanggal 10",
  "午後|ごご": "siang/sore (setelah tengah hari)",
  "協議|きょうぎ": "musyawarah",
  "単|たん": "sekadar",
  "単純|たんじゅん": "sederhana",
  "単語|たんご": "kosakata",
  "博士|はくし": "doktor",
  "危機|きき": "krisis",
  "危険|きけん": "berbahaya (nomina/sifat)",
  "原因|げんいん": "penyebab",
  "原文|げんぶん": "teks asli",
  "参加|さんか": "ikut serta",
  "参加費|さんかひ": "biaya peserta",
  "取|と": "mengambil",
  "取引|とりひき": "transaksi",
  "受|う": "menerima",
  "古|ふる": "tua",
  "可能性|かのうせい": "kemungkinan",
  "合|あ": "cocok (合う)",
  "同|おな": "sama (同じ)",
  "同時|どうじ": "pada saat yang sama",
  "向上|こうじょう": "peningkatan",
  "吟味|ぎんみ": "menelaah",
  "含|ふく": "termasuk, mencakup (含まれる)",
  "問|と": "menanyakan",
  "善|ぜん": "kebaikan",
  "国際|こくさい": "internasional",
  "土|ど": "Sabtu",
  "在籍|ざいせき": "terdaftar",
  "地域|ちいき": "kawasan",
  "地方|ちほう": "daerah",
  "型|がた": "tipe",
  "場|ば": "tempat/forum",
  "場合|ばあい": "kasus, jika",
  "場面|ばめん": "situasi, adegan",
  "増|ふ": "bertambah (増える)",
  "声|こえ": "suara",
  "変|か": "berubah (変わる)",
  "多|おお": "banyak (多い)",
  "多忙|たぼう": "kesibukan",
  "大|だい": "besar",
  "大切|たいせつ": "penting, berharga",
  "大学院|だいがくいん": "pascasarjana",
  "大量|たいりょう": "jumlah besar",
  "失礼|しつれい": "tidak sopan",
  "契約|けいやく": "kontrak",
  "奨学金|しょうがくきん": "beasiswa",
  "奪|うば": "merampas",
  "好循環|こうじゅんかん": "lingkaran baik",
  "始|はじ": "memulai (始める)",
  "委託|いたく": "alih daya",
  "姿勢|しせい": "sikap/postur",
  "子|こ": "anak (子ども)",
  "存続|そんぞく": "kelangsungan",
  "学|まな": "belajar (学ぶ)",
  "学校|がっこう": "sekolah",
  "学生|がくせい": "pelajar, mahasiswa",
  "学部生|がくぶせい": "mahasiswa S1",
  "安|やす": "murah (安い)",
  "定員|ていいん": "kapasitas",
  "実情|じつじょう": "keadaan sebenarnya",
  "実質|じっしつ": "riil",
  "実際|じっさい": "kenyataan",
  "家計|かけい": "keuangan rumah tangga",
  "寄|よ": "mengumpulkan",
  "対応|たいおう": "penanganan",
  "対応力|たいおうりょく": "daya tanggap",
  "対話|たいわ": "dialog",
  "対象|たいしょう": "sasaran",
  "専門家|せんもんか": "pakar",
  "尊重|そんちょう": "menghormati",
  "小|ちい": "kecil (小さい)",
  "少|すく": "sedikit (少ない)",
  "市民|しみん": "warga kota",
  "希望|きぼう": "harapan",
  "幸|さいわ": "beruntung",
  "広|ひろ": "luas (広い)",
  "廃止|はいし": "penghapusan",
  "引|ひ": "menarik; 引っ越す = pindah rumah",
  "強|つよ": "kuat (強い)",
  "当日|とうじつ": "hari H",
  "形|かたち": "bentuk",
  "待|ま": "menunggu",
  "待遇|たいぐう": "perlakuan/gaji",
  "従|したが": "menurut",
  "従業員|じゅうぎょういん": "karyawan",
  "得|え": "dapat (言わざるを得ない)",
  "得意|とくい": "andalan",
  "心|こころ": "hati",
  "必|かなら": "pasti (必ず)",
  "必ず|かならず": "pasti",
  "必要|ひつよう": "perlu",
  "応募|おうぼ": "melamar",
  "応急|おうきゅう": "darurat",
  "怒|おこ": "marah",
  "思|おも": "berpikir, merasa (思う)",
  "性能|せいのう": "kinerja",
  "恐|おそ": "kekhawatiran (恐れ)",
  "恐縮|きょうしゅく": "merasa sungkan",
  "悪|わる": "buruk",
  "情報|じょうほう": "informasi",
  "惜|お": "menyayangkan",
  "意味|いみ": "arti",
  "意思|いし": "niat",
  "意見|いけん": "pendapat",
  "感|かん": "kesan, sensasi (感じ)",
  "感情|かんじょう": "emosi",
  "慶|よろこ": "bergembira",
  "成果|せいか": "hasil",
  "成績|せいせき": "nilai",
  "手|て": "tangan",
  "手段|しゅだん": "cara, sarana",
  "手紙|てがみ": "surat",
  "払|はら": "membayar (払う)",
  "批判的|ひはんてき": "kritis",
  "技術|ぎじゅつ": "teknologi",
  "抜|ぬ": "tuntas (考え抜く)",
  "拒絶|きょぜつ": "menolak keras",
  "招|まね": "mengundang/menimbulkan",
  "持|も": "membawa, memiliki (持つ)",
  "指|さ": "menunjuk",
  "指導|しどう": "bimbingan",
  "指摘|してき": "menunjukkan",
  "挙|あ": "mengemukakan",
  "捉|とら": "menangkap/menafsirkan",
  "採用|さいよう": "perekrutan",
  "採算|さいさん": "untung rugi",
  "推薦|すいせん": "rekomendasi",
  "推薦書|すいせんしょ": "surat rekomendasi",
  "描|えが": "menggambarkan",
  "描|か": "menggambar",
  "換|か": "mengganti",
  "損|そこ": "merusak",
  "支払|しはら": "pembayaran",
  "改善|かいぜん": "perbaikan",
  "教員|きょういん": "pengajar",
  "散歩|さんぽ": "jalan santai",
  "数|かず": "jumlah",
  "文化|ぶんか": "budaya",
  "文章|ぶんしょう": "teks, tulisan",
  "断|ことわ": "menolak",
  "断片的|だんぺんてき": "serpihan",
  "新|あたら": "baru (新しい)",
  "方|かた": "cara/orang",
  "方策|ほうさく": "langkah",
  "日|ひ": "hari, tanggal",
  "日時|にちじ": "tanggal dan waktu",
  "日本|にほん": "Jepang",
  "日本人|にほんじん": "orang Jepang",
  "日本語|にほんご": "bahasa Jepang",
  "旨|むね": "maksud",
  "早|はや": "awal, cepat (早い)",
  "映|うつ": "tampak",
  "時|じ": "jam (pukul)",
  "時|とき": "saat, ketika",
  "時下|じか": "saat ini (surat)",
  "時代|じだい": "zaman",
  "時間|じかん": "waktu",
  "普及|ふきゅう": "penyebaran, pemasyarakatan",
  "景気|けいき": "kondisi ekonomi",
  "更新|こうしん": "pembaruan",
  "書|か": "menulis (書く)",
  "書面|しょめん": "tertulis",
  "書類|しょるい": "berkas",
  "最中|さいちゅう": "sedang",
  "最長|さいちょう": "terpanjang",
  "月額|げつがく": "jumlah per bulan",
  "有効|ゆうこう": "efektif, berlaku",
  "服装|ふくそう": "pakaian",
  "期間|きかん": "periode",
  "本数|ほんすう": "jumlah (frekuensi)",
  "本末転倒|ほんまつてんとう": "membalik prioritas",
  "本来|ほんらい": "semula",
  "条件|じょうけん": "syarat",
  "来月末|らいげつまつ": "akhir bulan depan",
  "来週|らいしゅう": "minggu depan",
  "来週中|らいしゅうちゅう": "dalam minggu depan",
  "根差|ねざ": "berakar",
  "検索|けんさく": "pencarian",
  "業務|ぎょうむ": "pekerjaan",
  "模索|もさく": "menjajaki",
  "機械|きかい": "mesin",
  "欠|か": "kurang (欠かせない: tak tergantikan)",
  "欧米|おうべい": "Barat",
  "止|と": "menerima (受け止める)",
  "残|のこ": "tersisa",
  "残業|ざんぎょう": "lembur",
  "気|き": "perasaan, semangat (気がする = merasa)",
  "気持|きも": "perasaan (気持ち)",
  "求|もと": "menuntut/mengejar",
  "汲|く": "menimba/menangkap",
  "決|き": "memutuskan",
  "沈黙|ちんもく": "keheningan",
  "法律|ほうりつ": "hukum",
  "注意|ちゅうい": "perhatian, peringatan",
  "活力|かつりょく": "vitalitas",
  "消|け": "menghapus",
  "消印|けしいん": "cap pos",
  "深|ふか": "dalam",
  "深刻|しんこく": "serius, gawat",
  "清栄|せいえい": "sehat sejahtera",
  "済|す": "selesai",
  "減|へ": "berkurang, mengurangi (減らす)",
  "減少|げんしょう": "penurunan",
  "満了|まんりょう": "berakhir",
  "災害|さいがい": "bencana",
  "無意味|むいみ": "tak bermakna",
  "無料|むりょう": "gratis",
  "無関心|むかんしん": "tidak peduli",
  "無駄|むだ": "sia-sia",
  "物|もの": "benda, barang (飲み物 = minuman)",
  "物事|ものごと": "segala hal",
  "物価|ぶっか": "harga barang",
  "現代|げんだい": "zaman sekarang",
  "理解|りかい": "pemahaman",
  "生|う": "lahir",
  "生産性|せいさんせい": "produktivitas",
  "申|もう": "mengajukan (申し込み)",
  "申告|しんこく": "melaporkan",
  "申請書|しんせいしょ": "formulir permohonan",
  "申込|もうしこみ": "pendaftaran",
  "留学生|りゅうがくせい": "mahasiswa asing",
  "異|こと": "berbeda",
  "異文化|いぶんか": "budaya berbeda",
  "発想|はっそう": "gagasan",
  "目的|もくてき": "tujuan",
  "直面|ちょくめん": "menghadapi",
  "相手|あいて": "lawan/mitra",
  "省|はぶ": "menghilangkan",
  "知|し": "memberi tahu (知らせ・知らせる)",
  "知識|ちしき": "pengetahuan",
  "研究|けんきゅう": "penelitian",
  "確|たし": "pasti",
  "確保|かくほ": "mengamankan",
  "私|わたし": "saya",
  "税金|ぜいきん": "pajak",
  "立|た": "menyusun/berdiri",
  "第一部|だいいちぶ": "bagian pertama",
  "第二部|だいにぶ": "bagian kedua",
  "筆者|ひっしゃ": "penulis",
  "簡単|かんたん": "mudah, sederhana",
  "終|お": "selesai (終わる)",
  "絆|きずな": "ikatan",
  "経験|けいけん": "pengalaman",
  "結|むす": "mengaitkan",
  "給付|きゅうふ": "pemberian",
  "絵|え": "lukisan",
  "絶対|ぜったい": "mutlak",
  "維持|いじ": "mempertahankan",
  "締切|しめきり": "batas akhir",
  "置|お": "menaruh",
  "美|うつく": "indah",
  "翻訳|ほんやく": "terjemahan",
  "翻訳者|ほんやくしゃ": "penerjemah",
  "考|かんが": "berpikir (考える)",
  "聞|き": "mendengar (聞く)",
  "職場|しょくば": "tempat kerja",
  "背後|はいご": "di balik",
  "背景|はいけい": "latar belakang",
  "脅威|きょうい": "ancaman",
  "膨大|ぼうだい": "sangat banyak",
  "臨|のぞ": "menghadapi",
  "自|みずか": "diri sendiri",
  "自体|じたい": "itu sendiri",
  "自分|じぶん": "diri sendiri",
  "自治体|じちたい": "pemda",
  "自身|じしん": "diri sendiri",
  "良|よ": "baik (良い)",
  "虚偽|きょぎ": "palsu",
  "行|い": "pergi (行く)",
  "表|あらわ": "tampak/menyatakan",
  "要|い": "perlu (要る)",
  "要項|ようこう": "pedoman",
  "見|み": "melihat (見る)",
  "見失|みうしな": "kehilangan arah",
  "見直|みなお": "meninjau ulang",
  "視点|してん": "sudut pandang",
  "解除|かいじょ": "pembatalan",
  "触|ふ": "menyentuh",
  "言|い": "berkata (言う)",
  "言葉|ことば": "kata, ucapan",
  "言語|げんご": "bahasa",
  "計画|けいかく": "rencana",
  "計画書|けいかくしょ": "rencana tertulis",
  "訓練|くんれん": "latihan",
  "託児|たくじ": "penitipan anak",
  "記載|きさい": "pencantuman",
  "設|もう": "mengadakan",
  "訳|やく": "menerjemahkan",
  "診断書|しんだんしょ": "surat keterangan dokter",
  "証明書|しょうめいしょ": "surat keterangan",
  "試|こころ": "mencoba",
  "試験|しけん": "ujian",
  "話|はな": "berbicara",
  "誠実|せいじつ": "jujur, tulus",
  "誤解|ごかい": "salah paham",
  "読者|どくしゃ": "pembaca",
  "誰|だれ": "siapa",
  "課程|かてい": "program",
  "講座|こうざ": "kursus",
  "講演|こうえん": "ceramah",
  "議論|ぎろん": "diskusi, perdebatan",
  "貯金|ちょきん": "tabungan",
  "賃上|ちんあ": "kenaikan upah",
  "賃金|ちんぎん": "upah",
  "購買力|こうばいりょく": "daya beli",
  "赤字|あかじ": "defisit, rugi",
  "起|お": "terjadi (起きる)",
  "越|こ": "melewati; 引っ越す = pindah rumah",
  "足|あし": "kaki",
  "路線|ろせん": "jalur",
  "転嫁|てんか": "membebankan",
  "輸入|ゆにゅう": "impor",
  "辞書|じしょ": "kamus",
  "込|こ": "masuk, mendaftar (申し込み)",
  "近|ちか": "dekat (近く・近い)",
  "近年|きんねん": "belakangan ini",
  "返事|へんじ": "balasan, jawaban",
  "返還|へんかん": "pengembalian",
  "述|の": "menyatakan",
  "追|お": "mengejar",
  "途切|とぎ": "terputus",
  "通|とお": "melewati",
  "速|はや": "cepat (速く・速い)",
  "連携|れんけい": "kaitan kerja sama",
  "連絡|れんらく": "menghubungi, kontak",
  "運営|うんえい": "pengelolaan",
  "運行|うんこう": "pengoperasian",
  "運賃|うんちん": "ongkos",
  "過去|かこ": "masa lalu",
  "過多|かた": "berlebihan",
  "道具|どうぐ": "peralatan",
  "違|ちが": "berbeda",
  "避|さ": "menghindari",
  "避難所|ひなんじょ": "pos pengungsian",
  "都合|つごう": "kondisi/keperluan (waktu luang)",
  "重要|じゅうよう": "penting",
  "重視|じゅうし": "mengutamakan",
  "量|りょう": "jumlah, kuantitas",
  "金額|きんがく": "nominal",
  "鉄道|てつどう": "kereta api",
  "長|た": "mahir (長ける)",
  "間|かん": "antara",
  "間|ま": "jeda",
  "関|かん": "mengenai",
  "防災|ぼうさい": "penanggulangan bencana",
  "限|かぎ": "terbatas",
  "限界|げんかい": "batas",
  "集|あつ": "berkumpul",
  "雑談|ざつだん": "obrolan ringan",
  "難|むずか": "sulit (難しい)",
  "雰囲気|ふんいき": "suasana",
  "電話|でんわ": "telepon",
  "順|じゅん": "urutan",
  "預|あず": "menitipkan",
  "頭|あたま": "kepala",
  "頼|たよ": "bergantung",
  "額|がく": "jumlah",
  "願|ねが": "memohon (お願いします)",
  "食事|しょくじ": "makan",
  "駅|えき": "stasiun",
  "高|たか": "tinggi, mahal (高い)",
  "高齢化|こうれいか": "penuaan populasi",
  "高齢者|こうれいしゃ": "lansia"
};
